class CfgPatches
{
    class v105_MA5_301X
    {
        author= "N4_Logistics_Team"; 
        url="https://discord.gg/105thstb-arma";
        units[]={};
        weapons[]=
        {
            "v105_NEST_MACA",
            "v105_NEST_MACA_GL",
            "v105_M301X",
        };
        magazines[]={};
        requiredVersion=0.1;
        requiredAddons[]=
        {
            "OPTRE_Core",
            "OPTRE_Weapons",
            "V_SO_Weapons",
            "OPTRE_Weapons_Sniper",
            "OPTRE_UNSC_Units",
            "OPTRE_MJOLNIR",
            "OPTRE_MJOLNIR_data_anims",
            "OPTRE_Ins_Units",
            "ace_common",
            "ace_explosives",
            "ace_medical_engine",
            "ace_medical_treatment",
            "A3_Data_F",
            "OPTRE_Weapons_Items",
            "OPTRE_ACE_Compat"
        };
    };
};
class WeaponSlotsInfo;
class MuzzleSlot;
class CowsSlot;
class PointerSlot;
class Mode_SemiAuto;
class Mode_Burst;
class Mode_FullAuto;
class UGL_F;
class UnderBarrelSlot;
class ItemInfo;
class OpticsModes;
class Snip;
class OPTRE_MA5B;
class OPTRE_MA5BGL;
class OPTRE_MA5K;
class CfgWeapons
{
    class v105_M301X: UGL_F
    {
        dlc							= "SO";
        author						= "Howard, Fireteam Zulu";
        scope						= 2;
        scopeArsenal				= 2;
        displayName 				= "M301X Grenade Launcher";
        descriptionShort 			= "M301X GL";
        baseWeapon 					= "v105_M301X";
        magazines[] = 
        {
            // 105th
            "v105_Whistler_Grenade",
            // Specialized Ordnance
            "UGL_FlareBlue_F",
            "3Rnd_UGL_8Gauge_Pellets",
            "3Rnd_UGL_8Gauge_Slugs",
            "3Rnd_UGL_8Gauge_Beanbags",
            "3Rnd_UGL_FlareBlue_F",
            // Standard
            "1Rnd_HE_Grenade_shell",
            "UGL_FlareWhite_F",
            "UGL_FlareGreen_F",
            "UGL_FlareRed_F",
            "UGL_FlareYellow_F",
            "UGL_FlareCIR_F",
            "1Rnd_Smoke_Grenade_shell",
            "1Rnd_SmokeRed_Grenade_shell",
            "1Rnd_SmokeGreen_Grenade_shell",
            "1Rnd_SmokeYellow_Grenade_shell",
            "1Rnd_SmokePurple_Grenade_shell",
            "1Rnd_SmokeBlue_Grenade_shell",
            "1Rnd_SmokeOrange_Grenade_shell",
            "3Rnd_HE_Grenade_shell",
            "3Rnd_UGL_FlareWhite_F",
            "3Rnd_UGL_FlareGreen_F",
            "3Rnd_UGL_FlareRed_F",
            "3Rnd_UGL_FlareYellow_F",
            "3Rnd_UGL_FlareCIR_F",
            "3Rnd_Smoke_Grenade_shell",
            "3Rnd_SmokeRed_Grenade_shell",
            "3Rnd_SmokeGreen_Grenade_shell",
            "3Rnd_SmokeYellow_Grenade_shell",
            "3Rnd_SmokePurple_Grenade_shell",
            "3Rnd_SmokeBlue_Grenade_shell",
            "3Rnd_SmokeOrange_Grenade_shell"
        };
        cameraDir 					= "OP_look";
        discreteDistanceInitIndex 	= 0;
        reloadAction 				= "GestureReloadMXUGL";
        useExternalOptic 			= 0;
        useModelOptics 				= 0;
        discreteDistance[] = 
        {
            100,
            200,
            300
        };
        discreteDistanceCameraPoint[] = 
        {
            "OP_eye",
            "OP_eye2",
            "OP_eye3"
        };
    };
    class OPTRE_MA5C: OPTRE_MA5B
    {
        //dlc							= "SO";
        //author						= "Fireteam Zulu";
        scope						= 2;
        scopeArsenal				= 2;
        displayName					= "MA5CX ICWS Assault Rifle";
        magazines[] = 
        {
            "HOW_32Rnd_762x51_IRDM_Mag",
            // ^ New Mags Above ^
            "OPTRE_32Rnd_762x51_Mag",
            "OPTRE_32Rnd_762x51_Mag_Tracer",
            "OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
            "OPTRE_32Rnd_762x51_Mag_AP",
            "OPTRE_32Rnd_762x51_Mag_APT",
            "OPTRE_32Rnd_762x51_Mag_JHP",
            "OPTRE_32Rnd_762x51_Mag_JHPT",
            "OPTRE_32Rnd_762x51_Mag_SS",
            "OPTRE_32Rnd_762x51_Mag_SST"
        };
        HUD_TotalPosibleBullet 		= 32;
        class Single: Mode_SemiAuto
        {
            sounds[]=
            {
                "StandardSound",
                "SilencedSound"
            };
            class BaseSoundModeType
            {
                weaponSoundEffect="DefaultRifle";
                closure1[]={};
                closure2[]={};
                soundClosure[]=
                {
                    "closure1",
                    0.5,
                    "closure2",
                    0.5
                };
            };
            class StandardSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-01.ogg",
                    "db5",
                    1,
                    2000
                };
                begin2[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-02.ogg",
                    "db5",
                    1,
                    2000
                };
                begin3[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-03.ogg",
                    "db5",
                    1,
                    2000
                };
                begin4[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-04.ogg",
                    "db5",
                    1,
                    2000
                };
                begin5[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-05.ogg",
                    "db5",
                    1,
                    2000
                };
                begin6[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-06.ogg",
                    "db5",
                    1,
                    2000
                };
                begin7[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-07.ogg",
                    "db5",
                    1,
                    2000
                };
                begin8[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-08.ogg",
                    "db5",
                    1,
                    2000
                };
                begin9[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-09.ogg",
                    "db5",
                    1,
                    2000
                };
                begin10[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-10.ogg",
                    "db5",
                    1,
                    2000
                };
                begin11[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-11.ogg",
                    "db5",
                    1,
                    2000
                };
                begin12[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-12.ogg",
                    "db5",
                    1,
                    2000
                };
                begin13[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-13.ogg",
                    "db5",
                    1,
                    2000
                };
                soundBegin[]=
                {
                    "begin1",
                    0.07,
                    "begin2",
                    0.07,
                    "begin3",
                    0.07,
                    "begin4",
                    0.07,
                    "begin5",
                    0.07,
                    "begin6",
                    0.07,
                    "begin7",
                    0.07,
                    "begin8",
                    0.07,
                    "begin9",
                    0.07,
                    "begin10",
                    0.07,
                    "begin11",
                    0.07,
                    "begin12",
                    0.07,
                    "begin13",
                    0.090000004
                };
            };
            class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};   
            reloadTime 				= 0.095;
        };
        class FullAuto: Mode_FullAuto
        {
            sounds[]=
            {
                "StandardSound",
                "SilencedSound"
            };
            class BaseSoundModeType
            {
                weaponSoundEffect="DefaultRifle";
                closure1[]={};
                closure2[]={};
                soundClosure[]=
                {
                    "closure1",
                    0.5,
                    "closure2",
                    0.5
                };
            };
            class StandardSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-01.ogg",
                    "db5",
                    1,
                    2000
                };
                begin2[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-02.ogg",
                    "db5",
                    1,
                    2000
                };
                begin3[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-03.ogg",
                    "db5",
                    1,
                    2000
                };
                begin4[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-04.ogg",
                    "db5",
                    1,
                    2000
                };
                begin5[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-05.ogg",
                    "db5",
                    1,
                    2000
                };
                begin6[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-06.ogg",
                    "db5",
                    1,
                    2000
                };
                begin7[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-07.ogg",
                    "db5",
                    1,
                    2000
                };
                begin8[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-08.ogg",
                    "db5",
                    1,
                    2000
                };
                begin9[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-09.ogg",
                    "db5",
                    1,
                    2000
                };
                begin10[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-10.ogg",
                    "db5",
                    1,
                    2000
                };
                begin11[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-11.ogg",
                    "db5",
                    1,
                    2000
                };
                begin12[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-12.ogg",
                    "db5",
                    1,
                    2000
                };
                begin13[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-13.ogg",
                    "db5",
                    1,
                    2000
                };
                soundBegin[]=
                {
                    "begin1",
                    0.07,
                    "begin2",
                    0.07,
                    "begin3",
                    0.07,
                    "begin4",
                    0.07,
                    "begin5",
                    0.07,
                    "begin6",
                    0.07,
                    "begin7",
                    0.07,
                    "begin8",
                    0.07,
                    "begin9",
                    0.07,
                    "begin10",
                    0.07,
                    "begin11",
                    0.07,
                    "begin12",
                    0.07,
                    "begin13",
                    0.090000004
                };
            };
            class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
            reloadTime 				= 0.095;
        };

    };
    class OPTRE_MA5CGL: OPTRE_MA5BGL
    {
        //dlc							= "SO";
        //author						= "Fireteam Zulu";
        scope						= 2;
        scopeArsenal				= 2;
        displayName					= "MA5CX + M301 GL Assault Rifle";
        muzzles[] = {"this","v105_M301X"};
        class v105_M301X:v105_M301X{};
        magazines[] = 
        {
            "HOW_32Rnd_762x51_IRDM_Mag",
            // ^ New Mags Above ^
            "OPTRE_32Rnd_762x51_Mag",
            "OPTRE_32Rnd_762x51_Mag_Tracer",
            "OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
            "OPTRE_32Rnd_762x51_Mag_AP",
            "OPTRE_32Rnd_762x51_Mag_APT",
            "OPTRE_32Rnd_762x51_Mag_JHP",
            "OPTRE_32Rnd_762x51_Mag_JHPT",
            "OPTRE_32Rnd_762x51_Mag_SS",
            "OPTRE_32Rnd_762x51_Mag_SST"
        };
        HUD_TotalPosibleBullet 		= 32;
        class Single: Mode_SemiAuto
        {
            sounds[]=
            {
                "StandardSound",
                "SilencedSound"
            };
            class BaseSoundModeType
            {
                weaponSoundEffect="DefaultRifle";
                closure1[]={};
                closure2[]={};
                soundClosure[]=
                {
                    "closure1",
                    0.5,
                    "closure2",
                    0.5
                };
            };
            class StandardSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-01.ogg",
                    "db5",
                    1,
                    2000
                };
                begin2[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-02.ogg",
                    "db5",
                    1,
                    2000
                };
                begin3[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-03.ogg",
                    "db5",
                    1,
                    2000
                };
                begin4[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-04.ogg",
                    "db5",
                    1,
                    2000
                };
                begin5[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-05.ogg",
                    "db5",
                    1,
                    2000
                };
                begin6[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-06.ogg",
                    "db5",
                    1,
                    2000
                };
                begin7[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-07.ogg",
                    "db5",
                    1,
                    2000
                };
                begin8[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-08.ogg",
                    "db5",
                    1,
                    2000
                };
                begin9[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-09.ogg",
                    "db5",
                    1,
                    2000
                };
                begin10[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-10.ogg",
                    "db5",
                    1,
                    2000
                };
                begin11[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-11.ogg",
                    "db5",
                    1,
                    2000
                };
                begin12[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-12.ogg",
                    "db5",
                    1,
                    2000
                };
                begin13[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-13.ogg",
                    "db5",
                    1,
                    2000
                };
                soundBegin[]=
                {
                    "begin1",
                    0.07,
                    "begin2",
                    0.07,
                    "begin3",
                    0.07,
                    "begin4",
                    0.07,
                    "begin5",
                    0.07,
                    "begin6",
                    0.07,
                    "begin7",
                    0.07,
                    "begin8",
                    0.07,
                    "begin9",
                    0.07,
                    "begin10",
                    0.07,
                    "begin11",
                    0.07,
                    "begin12",
                    0.07,
                    "begin13",
                    0.090000004
                };
            };
            class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};   
            reloadTime 				= 0.095;
        };
        class FullAuto: Mode_FullAuto
        {
            sounds[]=
            {
                "StandardSound",
                "SilencedSound"
            };
            class BaseSoundModeType
            {
                weaponSoundEffect="DefaultRifle";
                closure1[]={};
                closure2[]={};
                soundClosure[]=
                {
                    "closure1",
                    0.5,
                    "closure2",
                    0.5
                };
            };
            class StandardSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-01.ogg",
                    "db5",
                    1,
                    2000
                };
                begin2[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-02.ogg",
                    "db5",
                    1,
                    2000
                };
                begin3[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-03.ogg",
                    "db5",
                    1,
                    2000
                };
                begin4[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-04.ogg",
                    "db5",
                    1,
                    2000
                };
                begin5[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-05.ogg",
                    "db5",
                    1,
                    2000
                };
                begin6[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-06.ogg",
                    "db5",
                    1,
                    2000
                };
                begin7[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-07.ogg",
                    "db5",
                    1,
                    2000
                };
                begin8[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-08.ogg",
                    "db5",
                    1,
                    2000
                };
                begin9[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-09.ogg",
                    "db5",
                    1,
                    2000
                };
                begin10[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-10.ogg",
                    "db5",
                    1,
                    2000
                };
                begin11[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-11.ogg",
                    "db5",
                    1,
                    2000
                };
                begin12[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-12.ogg",
                    "db5",
                    1,
                    2000
                };
                begin13[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-13.ogg",
                    "db5",
                    1,
                    2000
                };
                soundBegin[]=
                {
                    "begin1",
                    0.07,
                    "begin2",
                    0.07,
                    "begin3",
                    0.07,
                    "begin4",
                    0.07,
                    "begin5",
                    0.07,
                    "begin6",
                    0.07,
                    "begin7",
                    0.07,
                    "begin8",
                    0.07,
                    "begin9",
                    0.07,
                    "begin10",
                    0.07,
                    "begin11",
                    0.07,
                    "begin12",
                    0.07,
                    "begin13",
                    0.090000004
                };
            };
            class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
            reloadTime 				= 0.095;
        };
    };
    /*class v105_MA5K: OPTRE_MA5K
    {
        dlc							= "105th";
        author						= "Howard, Fireteam Zulu";
        scope						= 2;
        scopeArsenal				= 2;
        baseWeapon 					= "v105_MA5K";
        displayName					= "[105th] MA5KX ICWS";
        magazines[] = 
        {
            "HOW_32Rnd_762x51_IRDM_Mag",
            // ^ New Mags Above ^
            "OPTRE_32Rnd_762x51_Mag",
            "OPTRE_32Rnd_762x51_Mag_Tracer",
            "OPTRE_32Rnd_762x51_Mag_AP",
            "OPTRE_32Rnd_762x51_Mag_APT",
            "OPTRE_32Rnd_762x51_Mag_JHP",
            "OPTRE_32Rnd_762x51_Mag_JHPT",
            "OPTRE_32Rnd_762x51_Mag_SS",
            "OPTRE_32Rnd_762x51_Mag_UW"
        };
        class Single: Mode_SemiAuto
        {
            reloadTime 				= 0.05;
        };
        class FullAuto: Mode_FullAuto
        {
            reloadTime 				= 0.05;
        };
        class WeaponSlotsInfo: WeaponSlotsInfo
        {
            class MuzzleSlot: MuzzleSlot
            {
                iconPosition[]={0,0.40000001};
        };
        class CowsSlot: CowsSlot
        {
            iconPosition[]={0.5,0.30000001};
            compatibleitems[]=
            {
                "optic_aco_grn",
                "optic_aco",
                "optic_holosight_blk_f",
                "optic_mrco",	
                "optic_yorris",	
                "optic_aco_smg",
                "optic_aco_grn_smg",
                "optic_holosight_smg_blk_f",
                "OPTRE_M7_Sight",
                "OPTRE_M392_Scope",
                "OPTRE_M393_Scope",
                "OPTRE_M393_ACOG",
                "OPTRE_M393_EOTECH",
                "OPTRE_BR55HB_Scope",
                "OPTRE_BMR_Scope"
            };
        };
        class PointerSlot: PointerSlot
        {
            iconPosition[]={0.2,0.40000001};
        };
            mass=50;
        };
    };*/
    class v105_NEST_MACA: OPTRE_MA5B
    {
        dlc							= "105th";
        author						= "Nest";
        scope						= 2;
        scopeArsenal				= 2;
        model = "\OPTRE_Weapons\AR\MA5A.p3d";
        displayName = "[105th] MA5C/FT ICWS (Flat-Top)";
        magazines[]=
        {
            "OPTRE_32Rnd_762x51_Mag", "HOW_32Rnd_762x51_IRDM_Mag",
            "OPTRE_32Rnd_762x51_Mag_Tracer","OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
            "OPTRE_32Rnd_762x51_Mag_AP","OPTRE_32Rnd_762x51_Mag_APT",
            "OPTRE_32Rnd_762x51_Mag_JHP","OPTRE_32Rnd_762x51_Mag_JHPT",
            "OPTRE_32Rnd_762x51_Mag_SS","OPTRE_32Rnd_762x51_Mag_SST"
        };
        baseWeapon="v105_NEST_MACA";
        class WeaponSlotsInfo: WeaponSlotsInfo
        {
            mass=55;
            class CowsSlot: CowsSlot
            {
                compatibleitems[]=
                {
                    "optic_tws",
                    "optic_tws_mg",
                    "optic_NVS",
                    "optic_DMS",
                    "optic_LRPS",
                    "optic_ams",
                    "optic_SOS",
                    "optic_MRCO",
                    "optic_Arco",
                    "optic_aco",
                    "optic_ACO_grn",
                    "optic_aco_smg",
                    "optic_ACO_grn_smg",
                    "optic_hamr",
                    "optic_Holosight",
                    "optic_Holosight_smg",
                    "optic_Hamr_khk_F",
                    "optic_SOS_khk_F",
                    "optic_Arco_ghex_F",
                    "optic_Arco_blk_F",
                    "optic_DMS_ghex_F",
                    "optic_ERCO_blk_F",
                    "optic_LRPS_ghex_F",
                    "optic_LRPS_tna_F",
                    "optic_Holosight_blk_F",
                    "optic_Holosight_khk_F",
                    "optic_Holosight_smg_blk_F",
                    "optic_Holosight_smg_khk_F",
                    "OPTRE_M7_Sight",
                    "OPTRE_M392_Scope",
                    "OPTRE_M393_Scope",
                    "OPTRE_M393_ACOG",
                    "OPTRE_M393_EOTECH",
                    "OPTRE_BR55HB_Scope",
                    "OPTRE_BMR_Scope",
                    "optic_ico_01_black_f",
                    "optic_MRD",
                };					
            };
        };
        modes[]=
        {
            "Single",
            "Burst",
            "FullAuto"
        };
        class Single: Mode_SemiAuto
        {
            sounds[]=
            {
                "StandardSound",
                "SilencedSound"
            };
            class BaseSoundModeType
            {
                weaponSoundEffect="DefaultRifle";
                closure1[]={};
                closure2[]={};
                soundClosure[]=
                {
                    "closure1",
                    0.5,
                    "closure2",
                    0.5
                };
            };
            class StandardSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-01.ogg",
                    "db5",
                    1,
                    2000
                };
                begin2[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-02.ogg",
                    "db5",
                    1,
                    2000
                };
                begin3[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-03.ogg",
                    "db5",
                    1,
                    2000
                };
                begin4[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-04.ogg",
                    "db5",
                    1,
                    2000
                };
                begin5[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-05.ogg",
                    "db5",
                    1,
                    2000
                };
                begin6[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-06.ogg",
                    "db5",
                    1,
                    2000
                };
                begin7[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-07.ogg",
                    "db5",
                    1,
                    2000
                };
                begin8[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-08.ogg",
                    "db5",
                    1,
                    2000
                };
                begin9[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-09.ogg",
                    "db5",
                    1,
                    2000
                };
                begin10[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-10.ogg",
                    "db5",
                    1,
                    2000
                };
                begin11[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-11.ogg",
                    "db5",
                    1,
                    2000
                };
                begin12[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-12.ogg",
                    "db5",
                    1,
                    2000
                };
                begin13[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-13.ogg",
                    "db5",
                    1,
                    2000
                };
                soundBegin[]=
                {
                    "begin1",
                    0.07,
                    "begin2",
                    0.07,
                    "begin3",
                    0.07,
                    "begin4",
                    0.07,
                    "begin5",
                    0.07,
                    "begin6",
                    0.07,
                    "begin7",
                    0.07,
                    "begin8",
                    0.07,
                    "begin9",
                    0.07,
                    "begin10",
                    0.07,
                    "begin11",
                    0.07,
                    "begin12",
                    0.07,
                    "begin13",
                    0.090000004
                };
            };
            class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
		};        
        class FullAuto: Mode_FullAuto
        {
            sounds[]=
            {
                "StandardSound",
                "SilencedSound"
            };
            class BaseSoundModeType
            {
                weaponSoundEffect="DefaultRifle";
                closure1[]={};
                closure2[]={};
                soundClosure[]=
                {
                    "closure1",
                    0.5,
                    "closure2",
                    0.5
                };
            };
            class StandardSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-01.ogg",
                    "db5",
                    1,
                    2000
                };
                begin2[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-02.ogg",
                    "db5",
                    1,
                    2000
                };
                begin3[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-03.ogg",
                    "db5",
                    1,
                    2000
                };
                begin4[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-04.ogg",
                    "db5",
                    1,
                    2000
                };
                begin5[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-05.ogg",
                    "db5",
                    1,
                    2000
                };
                begin6[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-06.ogg",
                    "db5",
                    1,
                    2000
                };
                begin7[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-07.ogg",
                    "db5",
                    1,
                    2000
                };
                begin8[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-08.ogg",
                    "db5",
                    1,
                    2000
                };
                begin9[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-09.ogg",
                    "db5",
                    1,
                    2000
                };
                begin10[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-10.ogg",
                    "db5",
                    1,
                    2000
                };
                begin11[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-11.ogg",
                    "db5",
                    1,
                    2000
                };
                begin12[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-12.ogg",
                    "db5",
                    1,
                    2000
                };
                begin13[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-13.ogg",
                    "db5",
                    1,
                    2000
                };
                soundBegin[]=
                {
                    "begin1",
                    0.07,
                    "begin2",
                    0.07,
                    "begin3",
                    0.07,
                    "begin4",
                    0.07,
                    "begin5",
                    0.07,
                    "begin6",
                    0.07,
                    "begin7",
                    0.07,
                    "begin8",
                    0.07,
                    "begin9",
                    0.07,
                    "begin10",
                    0.07,
                    "begin11",
                    0.07,
                    "begin12",
                    0.07,
                    "begin13",
                    0.090000004
                };
            };
            class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
            reloadTime=0.1;
        };
        class Burst: Mode_Burst
        {	
            burst=2;				
            reloadTime=0.0375;
            sounds[]=
            {
                "StandardSound",
                "SilencedSound"
            };
            class BaseSoundModeType
            {
                weaponSoundEffect="DefaultRifle";
                closure1[]={};
                closure2[]={};
                soundClosure[]=
                {
                    "closure1",
                    0.5,
                    "closure2",
                    0.5
                };
            };
            class StandardSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-01.ogg",
                    "db5",
                    1,
                    2000
                };
                begin2[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-02.ogg",
                    "db5",
                    1,
                    2000
                };
                begin3[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-03.ogg",
                    "db5",
                    1,
                    2000
                };
                begin4[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-04.ogg",
                    "db5",
                    1,
                    2000
                };
                begin5[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-05.ogg",
                    "db5",
                    1,
                    2000
                };
                begin6[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-06.ogg",
                    "db5",
                    1,
                    2000
                };
                begin7[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-07.ogg",
                    "db5",
                    1,
                    2000
                };
                begin8[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-08.ogg",
                    "db5",
                    1,
                    2000
                };
                begin9[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-09.ogg",
                    "db5",
                    1,
                    2000
                };
                begin10[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-10.ogg",
                    "db5",
                    1,
                    2000
                };
                begin11[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-11.ogg",
                    "db5",
                    1,
                    2000
                };
                begin12[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-12.ogg",
                    "db5",
                    1,
                    2000
                };
                begin13[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-13.ogg",
                    "db5",
                    1,
                    2000
                };
                soundBegin[]=
                {
                    "begin1",
                    0.07,
                    "begin2",
                    0.07,
                    "begin3",
                    0.07,
                    "begin4",
                    0.07,
                    "begin5",
                    0.07,
                    "begin6",
                    0.07,
                    "begin7",
                    0.07,
                    "begin8",
                    0.07,
                    "begin9",
                    0.07,
                    "begin10",
                    0.07,
                    "begin11",
                    0.07,
                    "begin12",
                    0.07,
                    "begin13",
                    0.090000004
                };
            };
            class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
            dispersion=0.00008999991;
            recoil="recoil_single_trg";
            recoilProne="recoil_single_prone_trg";
            minRange=2;
            minRangeProbab=0.0099999998;
            midRange=200;
            midRangeProbab=0.0099999998;
            maxRange=400;
            maxRangeProbab=0.0099999998;
            soundBurst=false;				
        };
    };
    class v105_NEST_MACAGL: v105_NEST_MACA
    {
        dlc							= "105th";
        author						= "Nest";
        scope						= 2;
        scopeArsenal				= 2;
        model="\OPTRE_Weapons\AR\MA5AGL.p3d";
        displayName = "[105th] MA5C/FT-GL ICWS (Flat-Top)";
        baseWeapon="v105_NEST_MACAGL";
        muzzles[] = {"this","v105_M301X"};
        class v105_M301X:v105_M301X{};
        magazines[]=
        {
            "OPTRE_32Rnd_762x51_Mag", "HOW_32Rnd_762x51_IRDM_Mag",
            "OPTRE_32Rnd_762x51_Mag_Tracer","OPTRE_32Rnd_762x51_Mag_Tracer_Yellow",
            "OPTRE_32Rnd_762x51_Mag_AP","OPTRE_32Rnd_762x51_Mag_APT",
            "OPTRE_32Rnd_762x51_Mag_JHP","OPTRE_32Rnd_762x51_Mag_JHPT",
            "OPTRE_32Rnd_762x51_Mag_SS","OPTRE_32Rnd_762x51_Mag_SST"
        };
        class WeaponSlotsInfo: WeaponSlotsInfo
        {
            mass=55;
            class CowsSlot: CowsSlot
            {
                compatibleitems[]=
                {
                    "optic_tws",
                    "optic_tws_mg",
                    "optic_NVS",
                    "optic_DMS",
                    "optic_LRPS",
                    "optic_ams",
                    "optic_SOS",
                    "optic_MRCO",
                    "optic_Arco",
                    "optic_aco",
                    "optic_ACO_grn",
                    "optic_aco_smg",
                    "optic_ACO_grn_smg",
                    "optic_hamr",
                    "optic_Holosight",
                    "optic_Holosight_smg",
                    "optic_Hamr_khk_F",
                    "optic_SOS_khk_F",
                    "optic_Arco_ghex_F",
                    "optic_Arco_blk_F",
                    "optic_DMS_ghex_F",
                    "optic_ERCO_blk_F",
                    "optic_LRPS_ghex_F",
                    "optic_LRPS_tna_F",
                    "optic_Holosight_blk_F",
                    "optic_Holosight_khk_F",
                    "optic_Holosight_smg_blk_F",
                    "optic_Holosight_smg_khk_F",
                    "OPTRE_M7_Sight",
                    "OPTRE_M392_Scope",
                    "OPTRE_M393_Scope",
                    "OPTRE_M393_ACOG",
                    "OPTRE_M393_EOTECH",
                    "OPTRE_BR55HB_Scope",
                    "OPTRE_BMR_Scope",
                    "optic_ico_01_black_f",
                    "optic_MRD",
                };
            };
        };					
        modes[]=
        {
            "Single",
            "Burst",
            "FullAuto"
        };
        class Single: Mode_SemiAuto
        {
            sounds[]=
            {
                "StandardSound",
                "SilencedSound"
            };
            class BaseSoundModeType
            {
                weaponSoundEffect="DefaultRifle";
                closure1[]={};
                closure2[]={};
                soundClosure[]=
                {
                    "closure1",
                    0.5,
                    "closure2",
                    0.5
                };
            };
            class StandardSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-01.ogg",
                    "db5",
                    1,
                    2000
                };
                begin2[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-02.ogg",
                    "db5",
                    1,
                    2000
                };
                begin3[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-03.ogg",
                    "db5",
                    1,
                    2000
                };
                begin4[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-04.ogg",
                    "db5",
                    1,
                    2000
                };
                begin5[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-05.ogg",
                    "db5",
                    1,
                    2000
                };
                begin6[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-06.ogg",
                    "db5",
                    1,
                    2000
                };
                begin7[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-07.ogg",
                    "db5",
                    1,
                    2000
                };
                begin8[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-08.ogg",
                    "db5",
                    1,
                    2000
                };
                begin9[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-09.ogg",
                    "db5",
                    1,
                    2000
                };
                begin10[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-10.ogg",
                    "db5",
                    1,
                    2000
                };
                begin11[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-11.ogg",
                    "db5",
                    1,
                    2000
                };
                begin12[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-12.ogg",
                    "db5",
                    1,
                    2000
                };
                begin13[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-13.ogg",
                    "db5",
                    1,
                    2000
                };
                soundBegin[]=
                {
                    "begin1",
                    0.07,
                    "begin2",
                    0.07,
                    "begin3",
                    0.07,
                    "begin4",
                    0.07,
                    "begin5",
                    0.07,
                    "begin6",
                    0.07,
                    "begin7",
                    0.07,
                    "begin8",
                    0.07,
                    "begin9",
                    0.07,
                    "begin10",
                    0.07,
                    "begin11",
                    0.07,
                    "begin12",
                    0.07,
                    "begin13",
                    0.090000004
                };
            };
            class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};   
        };     
        class FullAuto: Mode_FullAuto
        {
            sounds[]=
            {
                "StandardSound",
                "SilencedSound"
            };
            class BaseSoundModeType
            {
                weaponSoundEffect="DefaultRifle";
                closure1[]={};
                closure2[]={};
                soundClosure[]=
                {
                    "closure1",
                    0.5,
                    "closure2",
                    0.5
                };
            };
            class StandardSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-01.ogg",
                    "db5",
                    1,
                    2000
                };
                begin2[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-02.ogg",
                    "db5",
                    1,
                    2000
                };
                begin3[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-03.ogg",
                    "db5",
                    1,
                    2000
                };
                begin4[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-04.ogg",
                    "db5",
                    1,
                    2000
                };
                begin5[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-05.ogg",
                    "db5",
                    1,
                    2000
                };
                begin6[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-06.ogg",
                    "db5",
                    1,
                    2000
                };
                begin7[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-07.ogg",
                    "db5",
                    1,
                    2000
                };
                begin8[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-08.ogg",
                    "db5",
                    1,
                    2000
                };
                begin9[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-09.ogg",
                    "db5",
                    1,
                    2000
                };
                begin10[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-10.ogg",
                    "db5",
                    1,
                    2000
                };
                begin11[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-11.ogg",
                    "db5",
                    1,
                    2000
                };
                begin12[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-12.ogg",
                    "db5",
                    1,
                    2000
                };
                begin13[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-13.ogg",
                    "db5",
                    1,
                    2000
                };
                soundBegin[]=
                {
                    "begin1",
                    0.07,
                    "begin2",
                    0.07,
                    "begin3",
                    0.07,
                    "begin4",
                    0.07,
                    "begin5",
                    0.07,
                    "begin6",
                    0.07,
                    "begin7",
                    0.07,
                    "begin8",
                    0.07,
                    "begin9",
                    0.07,
                    "begin10",
                    0.07,
                    "begin11",
                    0.07,
                    "begin12",
                    0.07,
                    "begin13",
                    0.090000004
                };
            };
            class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};   
            reloadTime=0.1;
        };
        class Burst: Mode_Burst
        {	
            burst=2;				
            reloadTime=0.0375;
            sounds[]=
            {
                "StandardSound",
                "SilencedSound"
            };
            class BaseSoundModeType
            {
                weaponSoundEffect="DefaultRifle";
                closure1[]={};
                closure2[]={};
                soundClosure[]=
                {
                    "closure1",
                    0.5,
                    "closure2",
                    0.5
                };
            };
            class StandardSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-01.ogg",
                    "db5",
                    1,
                    2000
                };
                begin2[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-02.ogg",
                    "db5",
                    1,
                    2000
                };
                begin3[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-03.ogg",
                    "db5",
                    1,
                    2000
                };
                begin4[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-04.ogg",
                    "db5",
                    1,
                    2000
                };
                begin5[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-05.ogg",
                    "db5",
                    1,
                    2000
                };
                begin6[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-06.ogg",
                    "db5",
                    1,
                    2000
                };
                begin7[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-07.ogg",
                    "db5",
                    1,
                    2000
                };
                begin8[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-08.ogg",
                    "db5",
                    1,
                    2000
                };
                begin9[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-09.ogg",
                    "db5",
                    1,
                    2000
                };
                begin10[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-10.ogg",
                    "db5",
                    1,
                    2000
                };
                begin11[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-11.ogg",
                    "db5",
                    1,
                    2000
                };
                begin12[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-12.ogg",
                    "db5",
                    1,
                    2000
                };
                begin13[]=
                {
                    "\OPTRE_Weapons\AR\Data\sounds\MA5C-13.ogg",
                    "db5",
                    1,
                    2000
                };
                soundBegin[]=
                {
                    "begin1",
                    0.07,
                    "begin2",
                    0.07,
                    "begin3",
                    0.07,
                    "begin4",
                    0.07,
                    "begin5",
                    0.07,
                    "begin6",
                    0.07,
                    "begin7",
                    0.07,
                    "begin8",
                    0.07,
                    "begin9",
                    0.07,
                    "begin10",
                    0.07,
                    "begin11",
                    0.07,
                    "begin12",
                    0.07,
                    "begin13",
                    0.090000004
                };
            };
            class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
            dispersion=0.00008999991;
            recoil="recoil_single_trg";
            recoilProne="recoil_single_prone_trg";
            minRange=2;
            minRangeProbab=0.0099999998;
            midRange=200;
            midRangeProbab=0.0099999998;
            maxRange=400;
            maxRangeProbab=0.0099999998;
            soundBurst=false;				
        };
    };
};