/*
    Default Kits

    This is all of the default kits for players when the game loads they will be dynamically added to "default" kits
*/

_kit = [["OPTRE_BR45","","OPTRE_BMR_Laser","OPTRE_BR55HB_Scope",["OPTRE_36Rnd_95x40_Mag_JHP",36],[],"OPTRE_BR45Grip"],[],["OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",["OPTRE_8Rnd_127x40_Mag_AP",8],[],""],["v105_uniform_DigiWoodland_Slim",[["ACE_packingBandage",30],["ACE_elasticBandage",15],["ACE_quikclot",10],["ACE_epinephrine",6],["ACE_adenosine",2],["ACE_morphine",2],["kat_chestSeal",2],["kat_guedel",2],["kat_larynx",1],["ACE_tourniquet",6],["ACE_splint",4],["ACE_MapTools",1],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_EarPlugs",2],["ItemcTabHCam",1],["ACE_CableTie",4],["ACE_EntrenchingTool",1],["ACE_microDAGR",1],["OPTRE_M6_silencer",1],["105th_ACo_Beret",1],["OPTRE_MA5Suppressor",1],["kat_IV_16",4]]],["VES_M52A_MAR_Rifleman_C",[["OPTRE_8Rnd_127x40_Mag_AP",2,8],["ACE_Chemlight_HiBlue",3,1],["ACE_Chemlight_IR",3,1],["OPTRE_M9_Frag",2,1],["ACE_M84",4,1],["OPTRE_M2_Smoke",6,1],["OPTRE_M2_Smoke_Blue",1,1],["OPTRE_M2_Smoke_Purple",1,1],["OPTRE_36Rnd_95x40_Mag_JHP",11,36],["OPTRE_8Rnd_127x40_Mag_NARQ",1,8]]],["OPTRE_UNSC_Rucksack",[["ACE_bodyBag",1],["ACE_wirecutter",1],["ACE_bloodIV",4],["ACE_bloodIV_500",4]]],"ACOMP_MAR","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVG"]];
["[Marine] Rifleman",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [["v105_HOW_M73SAW","","","OPTRE_M393_Scope",["v105_HOW_300Rnd_762x51_Box_Tracer",300],[],"bipod_01_F_blk"],[],["OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",["OPTRE_8Rnd_127x40_Mag_AP",8],[],""],["v105_uniform_DigiWoodland_Slim",[["ACE_packingBandage",30],["ACE_elasticBandage",15],["ACE_quikclot",10],["ACE_epinephrine",6],["ACE_adenosine",2],["ACE_morphine",2],["kat_chestSeal",2],["kat_guedel",2],["kat_larynx",1],["ACE_tourniquet",6],["ACE_splint",4],["ACE_MapTools",1],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_EarPlugs",2],["ItemcTabHCam",1],["ACE_CableTie",4],["ACE_EntrenchingTool",1],["ACE_microDAGR",1],["OPTRE_M6_silencer",1],["105th_ACo_Beret",1],["OPTRE_MA5Suppressor",1],["kat_IV_16",4]]],["VES_M52A_MAR_Rifleman_C",[["ACE_bodyBag",1],["OPTRE_8Rnd_127x40_Mag_AP",2,8],["ACE_Chemlight_HiBlue",3,1],["ACE_Chemlight_IR",3,1],["OPTRE_M9_Frag",2,1],["ACE_M84",4,1],["OPTRE_M2_Smoke",6,1],["OPTRE_M2_Smoke_Blue",1,1],["OPTRE_M2_Smoke_Purple",1,1],["v105_HOW_300Rnd_762x51_Box_Tracer",2,300],["v105_HOW_150Rnd_762x51_Box_Tracer",1,150],["OPTRE_8Rnd_127x40_Mag_NARQ",1,8]]],["OPTRE_UNSC_Rucksack",[["ACE_wirecutter",1],["ACE_bloodIV",3],["ACE_bloodIV_500",3],["v105_HOW_300Rnd_762x51_Box_Tracer",4,300],["v105_HOW_150Rnd_762x51_Box_Tracer",1,150]]],"ACOMP_MAR","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVG"]];
["[Marine] Autorifleman",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [["OPTRE_M7","OPTRE_M7_silencer","OPTRE_M7_Laser","OPTRE_M7_Sight",["OPTRE_60Rnd_5x23mm_Mag_JHP",60],[],""],[],["OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",["OPTRE_8Rnd_127x40_Mag_AP",8],[],""],["v105_uniform_DigiWoodland_Slim",[["ACE_packingBandage",20],["ACE_elasticBandage",30],["ACE_quikclot",10],["ACE_epinephrine",6],["ACE_adenosine",2],["ACE_morphine",2],["kat_chestSeal",2],["kat_guedel",2],["kat_larynx",1],["ACE_tourniquet",6],["ACE_splint",4],["ACE_MapTools",1],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_EarPlugs",2],["ItemcTabHCam",1],["ACE_CableTie",4],["ACE_EntrenchingTool",1],["ACE_microDAGR",1],["OPTRE_M6_silencer",1],["105th_ACo_Beret",1],["ACE_bloodIV",2],["kat_IV_16",4]]],["VES_M52A_MAR_Corpsman_A",[["ACE_bloodIV",6],["OPTRE_8Rnd_127x40_Mag_AP",2,8],["ACE_Chemlight_HiBlue",3,1],["ACE_Chemlight_IR",3,1],["OPTRE_M9_Frag",2,1],["ACE_M84",4,1],["OPTRE_M2_Smoke",6,1],["OPTRE_M2_Smoke_Blue",1,1],["OPTRE_M2_Smoke_Purple",1,1],["OPTRE_60Rnd_5x23mm_Mag_JHP",11,60]]],["v105_HardcaseSatchel_Medical",[["ACE_bodyBag",1],["ACE_surgicalKit",1],["kat_Pulseoximeter",1],["kat_accuvac",1],["kat_guedel",20],["ACE_splint",20],["ACE_tourniquet",20],["ACE_epinephrine",20],["ACE_morphine",20],["ACE_packingBandage",20],["ACE_elasticBandage",20],["ACE_fieldDressing",10],["ACE_quikclot",5],["kat_aatKit",5],["kat_IV_16",10],["kat_IO_FAST",4],["ACE_bloodIV",6],["ACE_bloodIV_250",6],["ACE_bloodIV_500",6]]],"ACOMP_HM_MAR","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVG"]];
["[Marine] Corpsman",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [["OPTRE_M392_DMR","","OPTRE_BMR_Laser","OPTRE_BR55HB_Scope",["HOW_15Rnd_762x51_338_Magnum_Mag",15],[],"bipod_01_F_blk"],[],["OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",["OPTRE_8Rnd_127x40_Mag_AP",8],[],""],["v105_uniform_DigiWoodland_Slim",[["ACE_packingBandage",30],["ACE_elasticBandage",15],["ACE_quikclot",10],["ACE_epinephrine",6],["ACE_adenosine",2],["ACE_morphine",2],["kat_chestSeal",2],["kat_guedel",2],["kat_larynx",1],["ACE_tourniquet",6],["ACE_splint",4],["ACE_MapTools",1],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_EarPlugs",2],["ItemcTabHCam",1],["ACE_CableTie",4],["ACE_EntrenchingTool",1],["ACE_microDAGR",1],["ACE_salineIV_250",6],["OPTRE_M6_silencer",1],["105th_ACo_Beret",1],["OPTRE_MA5Suppressor",1],["kat_IV_16",4]]],["VES_M52A_MAR_Rifleman_C",[["OPTRE_8Rnd_127x40_Mag_AP",2,8],["ACE_Chemlight_HiBlue",3,1],["ACE_Chemlight_IR",3,1],["OPTRE_M9_Frag",2,1],["ACE_M84",4,1],["OPTRE_M2_Smoke",6,1],["OPTRE_M2_Smoke_Blue",1,1],["OPTRE_M2_Smoke_Purple",1,1],["HOW_15Rnd_762x51_338_Magnum_Mag",11,15]]],["OPTRE_UNSC_Rucksack",[["ACE_bodyBag",1],["ACE_salineIV_500",4],["ACE_salineIV",3],["ACE_wirecutter",1],["ACE_ATragMX",1],["ACE_RangeCard",1],["ACE_Kestrel4500",1]]],"ACOMP_MAR","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVG"]];
["[Marine] Marksman",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [["v105_NEST_MACAGL","","","OPTRE_M7_Sight",["OPTRE_32Rnd_762x51_Mag_AP",32],[],""],[],["OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",["OPTRE_8Rnd_127x40_Mag_AP",8],[],""],["v105_uniform_DigiWoodland_Slim",[["ACE_packingBandage",30],["ACE_elasticBandage",15],["ACE_quikclot",10],["ACE_epinephrine",6],["ACE_adenosine",2],["ACE_morphine",2],["kat_chestSeal",2],["kat_guedel",2],["kat_larynx",1],["ACE_tourniquet",6],["ACE_splint",4],["ACE_MapTools",1],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_EarPlugs",2],["ItemcTabHCam",1],["ACE_CableTie",4],["ACE_EntrenchingTool",1],["ACE_microDAGR",1],["OPTRE_M6_silencer",1],["OPTRE_MA5Suppressor",1],["105th_ACo_Beret",1],["kat_IV_16",4]]],["VES_M52A_MAR_Rifleman_C",[["OPTRE_8Rnd_127x40_Mag_AP",2,8],["ACE_Chemlight_HiBlue",3,1],["ACE_Chemlight_IR",3,1],["OPTRE_M9_Frag",2,1],["ACE_M84",4,1],["OPTRE_M2_Smoke",6,1],["OPTRE_M2_Smoke_Blue",1,1],["OPTRE_M2_Smoke_Purple",1,1],["OPTRE_32Rnd_762x51_Mag_AP",11,32],["OPTRE_8Rnd_127x40_Mag_NARQ",1,8]]],["OPTRE_UNSC_Rucksack",[["ACE_bodyBag",1],["ACE_wirecutter",1],["ACE_HuntIR_monitor",1],["ACE_bloodIV",3],["ACE_bloodIV_500",3],["ACE_HuntIR_M203",4,1],["OPTRE_3Rnd_Smoke_Grenade_shell",6,3],["3Rnd_SmokeRed_Grenade_shell",3,3],["ACE_40mm_Flare_white",4,1],["v105_URF_Howler_3RND_Grenade",6,3]]],"ACOMP_MAR","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVG"]];
["[Marine] Grenadier",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [["OPTRE_BR45","","OPTRE_BMR_Laser","OPTRE_BR55HB_Scope",["OPTRE_36Rnd_95x40_Mag_JHP",36],[],"OPTRE_BR45Grip"],["OPTRE_M41_SSR","","","",["OPTRE_M41_Twin_HEAT_Thermal",2],[],""],["OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",["OPTRE_8Rnd_127x40_Mag_AP",8],[],""],["v105_uniform_DigiWoodland_Slim",[["ACE_packingBandage",30],["ACE_elasticBandage",15],["ACE_quikclot",10],["ACE_epinephrine",6],["ACE_adenosine",2],["ACE_morphine",2],["kat_chestSeal",2],["kat_guedel",2],["kat_larynx",1],["ACE_tourniquet",6],["ACE_splint",4],["ACE_MapTools",1],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_EarPlugs",2],["ItemcTabHCam",1],["ACE_CableTie",4],["ACE_EntrenchingTool",1],["ACE_microDAGR",1],["OPTRE_M6_silencer",1],["105th_ACo_Beret",1],["OPTRE_MA5Suppressor",1],["kat_IV_16",4]]],["VES_M52A_MAR_Rifleman_C",[["ACE_bodyBag",1],["ACE_bloodIV",1],["ACE_bloodIV_500",1],["OPTRE_8Rnd_127x40_Mag_AP",2,8],["ACE_Chemlight_HiBlue",3,1],["ACE_Chemlight_IR",3,1],["OPTRE_M9_Frag",2,1],["ACE_M84",4,1],["OPTRE_M2_Smoke",6,1],["OPTRE_M2_Smoke_Blue",1,1],["OPTRE_M2_Smoke_Purple",1,1],["OPTRE_36Rnd_95x40_Mag_JHP",11,36]]],["OPTRE_UNSC_Rucksack",[["ACE_bloodIV_500",2],["ACE_bloodIV",2],["OPTRE_M41_Twin_HEAT_Thermal",3,2],["OPTRE_M41_Twin_HEAT_SACLOS",1,2]]],"ACOMP_MAR","",["OPTRE_Smartfinder","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVG"]];
["[Marine] Missile Specialist",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [["OPTRE_BR45","","OPTRE_BMR_Laser","OPTRE_BR55HB_Scope",["OPTRE_36Rnd_95x40_Mag_JHP",36],[],"OPTRE_BR45Grip"],[],["OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",["OPTRE_8Rnd_127x40_Mag_AP",8],[],""],["v105_uniform_DigiWoodland_Slim",[["ACE_packingBandage",30],["ACE_elasticBandage",20],["ACE_quikclot",10],["ACE_epinephrine",6],["ACE_adenosine",2],["ACE_morphine",2],["kat_chestSeal",2],["kat_guedel",2],["kat_larynx",1],["ACE_tourniquet",6],["ACE_splint",4],["ACE_MapTools",1],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_EarPlugs",2],["ItemcTabHCam",1],["ACE_CableTie",4],["ACE_EntrenchingTool",1],["ACE_microDAGR",1],["OPTRE_M6_silencer",1],["105th_ACo_Beret",1],["OPTRE_MA5Suppressor",1],["kat_IV_16",4]]],["VES_M52A_MAR_Rifleman_C",[["ACE_bodyBag",1],["ACE_wirecutter",1],["ACE_SpraypaintRed",2],["ACE_SpraypaintGreen",1],["ACE_Chemlight_HiBlue",3,1],["ACE_Chemlight_IR",3,1],["OPTRE_M9_Frag",2,1],["ACE_M84",4,1],["OPTRE_M2_Smoke",6,1],["OPTRE_M2_Smoke_Blue",1,1],["OPTRE_M2_Smoke_Purple",1,1],["OPTRE_36Rnd_95x40_Mag_JHP",11,36],["OPTRE_8Rnd_127x40_Mag_AP",2,8],["OPTRE_8Rnd_127x40_Mag_NARQ",1,8]]],["OPTRE_UNSC_Rucksack_Heavy",[["ACE_M26_Clacker",1],["ACE_Fortify",1],["ToolKit",1],["tsp_lockpick",1],["ACE_bloodIV",3],["ACE_bloodIV_500",3],["ACE_DefusalKit",1],["C7_Remote_Mag",6,1],["DemoCharge_Remote_Mag",2,1],["tsp_popperCharge_mag",6,1],[["ACE_VMM3","","","",[],[],""],1]]],"ACOMP_MAR","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","OPTRE_NVG"]];
["[Marine] Combat Engineer",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [["OPTRE_BR55HB","","OPTRE_BMR_Laser","OPTRE_M7_Sight",["OPTRE_36Rnd_95x40_Mag_HPSAP",36],[],""],[],["OPTRE_M6C","OPTRE_M6C_compensator","OPTRE_M6C_Laser","OPTRE_M7_Sight",["OPTRE_12Rnd_127x40_Mag_HVAP",12],[],""],["r105_uniform_ODST",[["ItemcTabHCam",1],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_adenosine",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_tourniquet",4],["kat_chestSeal",3],["kat_guedel",3],["ACE_EarPlugs",2],["ACE_IR_Strobe_Item",2],["ACE_CableTie",4],["ACE_splint",4],["ACE_Flashlight_MX991",1],["kat_bloodIV_O_500",1],["kat_bloodIV_O",1],["kat_bloodIV_O_250",2],["ACE_EntrenchingTool",1],["OPTRE_M6_silencer",1],["ACE_Chemlight_UltraHiOrange",2,1],["OPTRE_M9_Frag",2,1],["ACE_M84",6,1]]],["ODST_Rifleman",[["OPTRE_M2_Smoke",4,1],["OPTRE_M2_Smoke_Blue",2,1],["OPTRE_M2_Smoke_Purple",1,1],["OPTRE_16Rnd_127x40_Mag_NARQ",1,12],["OPTRE_16Rnd_127x40_Mag_HVAP",1,12],["OPTRE_36Rnd_95x40_Mag_HPSAP",10,36]]],["OPTRE_ILCS_Rucksack_Heavy",[]],"VES_CH252D","",["OPTRE_Smartfinder","","","",["Laserbatteries",1],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","ACE_Altimeter","VES_NVG_Collar_VAC"]];
["[ODST] Rifleman",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [["v105_HOW_M247SSW","","","OPTRE_M7_Sight",["HOW_200Rnd_93x64_Mixed_Box",200],[],"bipod_02_F_blk"],[],["OPTRE_M6C","OPTRE_M6C_compensator","OPTRE_M6C_Laser","OPTRE_M7_Sight",["OPTRE_12Rnd_127x40_Mag_HVAP",12],[],""],["r105_uniform_ODST",[["ItemcTabHCam",1],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_adenosine",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_tourniquet",4],["kat_chestSeal",3],["kat_guedel",3],["ACE_EarPlugs",2],["ACE_IR_Strobe_Item",2],["ACE_CableTie",4],["ACE_splint",4],["ACE_Flashlight_MX991",1],["kat_bloodIV_O_500",1],["kat_bloodIV_O",1],["kat_bloodIV_O_250",2],["ACE_EntrenchingTool",1],["OPTRE_M6_silencer",1],["ACE_Chemlight_UltraHiOrange",2,1],["OPTRE_M9_Frag",2,1],["ACE_M84",6,1]]],["ODST_Rifleman",[["OPTRE_M2_Smoke",4,1],["OPTRE_M2_Smoke_Blue",2,1],["OPTRE_M2_Smoke_Purple",1,1],["OPTRE_16Rnd_127x40_Mag_NARQ",1,12],["OPTRE_16Rnd_127x40_Mag_HVAP",1,12],["HOW_200Rnd_93x64_Mixed_Box",3,200]]],["OPTRE_ILCS_Rucksack_Heavy",[["HOW_200Rnd_93x64_Mixed_Box",2,200]]],"VES_CH252D","",["OPTRE_Smartfinder","","","",["Laserbatteries",1],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","ACE_Altimeter","VES_NVG_Collar_VAC"]];
["[ODST] Autorifleman",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [["OPTRE_BR55HB","","OPTRE_BMR_Laser","OPTRE_M7_Sight",["OPTRE_36Rnd_95x40_Mag_HPSAP",36],[],""],["OPTRE_M48_PAW","","","",["OPTRE_1Rnd_50x137_THERMO",1],[],""],["OPTRE_M6C","OPTRE_M6C_compensator","OPTRE_M6C_Laser","OPTRE_M7_Sight",["OPTRE_12Rnd_127x40_Mag_HVAP",12],[],""],["r105_uniform_ODST",[["ItemcTabHCam",1],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_adenosine",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_tourniquet",4],["kat_chestSeal",3],["kat_guedel",3],["ACE_EarPlugs",2],["ACE_IR_Strobe_Item",2],["ACE_CableTie",4],["ACE_splint",4],["ACE_Flashlight_MX991",1],["kat_bloodIV_O_500",1],["kat_bloodIV_O",1],["kat_bloodIV_O_250",2],["ACE_EntrenchingTool",1],["OPTRE_M6_silencer",1],["ACE_Chemlight_UltraHiOrange",2,1],["OPTRE_M9_Frag",2,1],["ACE_M84",6,1]]],["ODST_Demo",[["OPTRE_M2_Smoke",4,1],["OPTRE_M2_Smoke_Blue",2,1],["OPTRE_M2_Smoke_Purple",1,1],["OPTRE_16Rnd_127x40_Mag_NARQ",1,12],["OPTRE_16Rnd_127x40_Mag_HVAP",1,12],["OPTRE_36Rnd_95x40_Mag_HPSAP",10,36],["OPTRE_1Rnd_50x137_HE",2,1]]],["OPTRE_ILCS_Rucksack_Heavy",[["OPTRE_1Rnd_50x137_PEN",2,1],["OPTRE_1Rnd_50x137_THERMO",2,1]]],"VES_CH252D","",["OPTRE_Smartfinder","","","",["Laserbatteries",1],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","ACE_Altimeter","VES_NVG_Collar_VAC"]];
["[ODST] Combat Engineer",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [["OPTRE_BR55HB","","OPTRE_BMR_Laser","OPTRE_M7_Sight",["OPTRE_36Rnd_95x40_Mag_HPSAP",36],[],""],["OPTRE_M41_SSR","","","",["OPTRE_M41_Twin_HEAT",2],[],""],["OPTRE_M6C","OPTRE_M6C_compensator","OPTRE_M6C_Laser","OPTRE_M7_Sight",["OPTRE_12Rnd_127x40_Mag_HVAP",12],[],""],["r105_uniform_ODST",[["ItemcTabHCam",1],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_adenosine",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_tourniquet",4],["kat_chestSeal",3],["kat_guedel",3],["ACE_EarPlugs",2],["ACE_IR_Strobe_Item",2],["ACE_CableTie",4],["ACE_splint",4],["ACE_Flashlight_MX991",1],["kat_bloodIV_O_500",1],["kat_bloodIV_O",1],["kat_bloodIV_O_250",2],["ACE_EntrenchingTool",1],["OPTRE_M6_silencer",1],["ACE_Chemlight_UltraHiOrange",2,1],["OPTRE_M9_Frag",2,1],["ACE_M84",6,1]]],["ODST_Rifleman",[["OPTRE_M2_Smoke",4,1],["OPTRE_M2_Smoke_Blue",2,1],["OPTRE_M2_Smoke_Purple",1,1],["OPTRE_16Rnd_127x40_Mag_NARQ",1,12],["OPTRE_16Rnd_127x40_Mag_HVAP",1,12],["OPTRE_36Rnd_95x40_Mag_HPSAP",10,36]]],["OPTRE_ILCS_Rucksack_Heavy",[["OPTRE_M41_Twin_HEAT_Thermal",2,2],["OPTRE_M41_Twin_HEAT_SACLOS",2,2],["OPTRE_M41_Twin_HEAT_SALH",1,2]]],"VES_CH252D","",["OPTRE_Smartfinder","","","",["Laserbatteries",1],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","ACE_Altimeter","VES_NVG_Collar_VAC"]];
["[ODST] Missile Specialist",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [["OPTRE_M393_DMR","","OPTRE_BMR_Laser","optic_AMS",["HOW_15Rnd_762x51_338_Magnum_Mag",15],[],"bipod_02_F_blk"],[],["OPTRE_M6C","OPTRE_M6C_compensator","OPTRE_M6C_Laser","OPTRE_M7_Sight",["OPTRE_12Rnd_127x40_Mag_HVAP",12],[],""],["r105_uniform_ODST",[["ItemcTabHCam",1],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_adenosine",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_tourniquet",4],["kat_chestSeal",3],["kat_guedel",3],["ACE_EarPlugs",2],["ACE_IR_Strobe_Item",2],["ACE_CableTie",4],["ACE_splint",4],["ACE_Flashlight_MX991",1],["kat_bloodIV_O_500",1],["kat_bloodIV_O",1],["kat_bloodIV_O_250",2],["ACE_EntrenchingTool",1],["OPTRE_M6_silencer",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_Chemlight_UltraHiOrange",2,1],["OPTRE_M9_Frag",2,1],["ACE_M84",6,1]]],["ODST_Sniper",[["OPTRE_M2_Smoke",4,1],["OPTRE_M2_Smoke_Blue",2,1],["OPTRE_M2_Smoke_Purple",1,1],["OPTRE_16Rnd_127x40_Mag_NARQ",1,12],["OPTRE_16Rnd_127x40_Mag_HVAP",1,12],["HOW_15Rnd_762x51_338_Magnum_Mag",12,15],["HOW_15Rnd_762x51_338_APIT_Mag",3,15]]],["OPTRE_ILCS_Rucksack_Heavy",[]],"VES_CH252D","",["OPTRE_Smartfinder","","","",["Laserbatteries",1],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","ACE_Altimeter","VES_NVG_Collar_VAC"]];
["[ODST] Marksman",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [["OPTRE_BR55HB","","OPTRE_BMR_Laser","OPTRE_M7_Sight",["OPTRE_36Rnd_95x40_Mag_HPSAP",36],[],""],[],["OPTRE_M6C","OPTRE_M6C_compensator","OPTRE_M6C_Laser","OPTRE_M7_Sight",["OPTRE_12Rnd_127x40_Mag_HVAP",12],[],""],["r105_uniform_ODST",[["ItemcTabHCam",1],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_adenosine",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_tourniquet",4],["kat_chestSeal",3],["kat_guedel",3],["ACE_EarPlugs",2],["ACE_IR_Strobe_Item",2],["ACE_CableTie",4],["ACE_splint",4],["ACE_Flashlight_MX991",1],["kat_bloodIV_O_500",1],["kat_bloodIV_O",1],["kat_bloodIV_O_250",2],["ACE_EntrenchingTool",1],["OPTRE_M6_silencer",1],["ACE_Chemlight_UltraHiOrange",2,1],["OPTRE_M9_Frag",2,1],["ACE_M84",6,1]]],["ODST_Corpsman",[["ACE_adenosine",3],["ACE_epinephrine",8],["ACE_morphine",3],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_fieldDressing",20],["ACE_tourniquet",2],["ACE_splint",2],["kat_bloodIV_O_500",8],["kat_larynx",16],["OPTRE_M2_Smoke",4,1],["OPTRE_M2_Smoke_Blue",2,1],["OPTRE_M2_Smoke_Purple",1,1],["OPTRE_16Rnd_127x40_Mag_NARQ",1,12],["OPTRE_16Rnd_127x40_Mag_HVAP",1,12],["OPTRE_36Rnd_95x40_Mag_HPSAP",10,36]]],["v105_HardcaseSatchel_Medical",[["kat_larynx",4],["kat_bloodIV_O",8],["kat_accuvac",1],["ACE_surgicalKit",1],["kat_aatKit",5],["ACE_personalAidKit",1]]],"VES_CH252D","",["OPTRE_Smartfinder","","","",["Laserbatteries",1],[],""],["ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","ACE_Altimeter","VES_NVG_Collar_VAC"]];
["[ODST] SARC",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [["OPTRE_M7","OPTRE_M7_silencer","","OPTRE_M7_Sight_v2",["OPTRE_60Rnd_5x23mm_Mag",60],[],""],[],["MatGrp_M6C_Auto","OPTRE_M6C_compensator","OPTRE_M6C_Laser","",["MatGrp_20Rnd_127x40_Mag",20],[],""],["VES_BDU_Evolved_Slim",[["ACE_elasticBandage",8],["ACE_packingBandage",8],["ACE_quikclot",8],["ACE_CableTie",2],["ACE_epinephrine",2],["ACE_IR_Strobe_Item",2],["ACE_Kestrel4500",1],["ACE_tourniquet",4],["ACE_splint",4],["ACE_salineIV_500",2],["ACE_RangeCard",1],["ACE_microDAGR",1],["ACE_morphine",2],["MineDetector",1],["ACE_Clacker",1],["ACE_EntrenchingTool",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ItemcTabHCam",1]]],["VES_M52A_URB_Security_A",[["ACE_surgicalKit",1],["ToolKit",1],["ACE_EarPlugs",3],["kat_guedel",6],["kat_chestSeal",4],["OPTRE_MA5Suppressor",1],["OPTRE_M8_Flare_Blue",1,1],["OPTRE_M8_Flare",1,1],["OPTRE_M9_Frag",5,1],["OPTRE_M2_Smoke",2,1],["OPTRE_M2_Smoke_Blue",1,1],["OPTRE_M2_Smoke_Red",1,1],["ACE_Chemlight_UltraHiOrange",2,1],["OPTRE_60Rnd_5x23mm_Mag_JHP",4,60]]],["B_Parachute",[]],"OPTRE_UNSC_VX16_Helmet_Mask","",["OPTRE_Smartfinder","","","",["Laserbatteries",1],[],""],["","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","VES_NVG_HURS"]];
["[VC497] Pilot",_kit] call ace_arsenal_fnc_addDefaultLoadout;