class CfgPatches {
    class B_UNSCArmy_DES {
        units[] = {
            "B_BUNSCArmyDES_Rifleman_01",
            "B_BUNSCArmyDES_Autorifleman_01",
            "B_BUNSCArmyDES_Grenadier_01",
            "B_BUNSCArmyDES_Squad_Leader_01",
            "B_BUNSCArmyDES_Marksman_01",
            "B_BUNSCArmyDES_Sniper_01",
            "B_BUNSCArmyDES_Crewman_01",
            "B_BUNSCArmyDES_Aviator_01",
            "B_BUNSCArmyDES_Medic_01",
            "B_BUNSCArmyDES_Radio_Telephone_Operator_01",
            "B_BUNSCArmyDES_Warthog_LAAG_01",
            "B_BUNSCArmyDES_Warthog_AA_01",
            "B_BUNSCArmyDES_Rifleman_AT_01",
            "B_BUNSCArmyDES_Rifleman_AA_01",
            "B_BUNSCArmyDES_Warthog_TT_01",
            "B_BUNSCArmyDES_Warthog_Unarmed_01",
            "B_BUNSCArmyDES_D77H_TCI_AV_Pelican_01",
            "B_BUNSCArmyDES_D77H_TCI_AV_Pelican_Jaeger_01",
            "B_BUNSCArmyDES_D77H_TCI_AV_Pelican_Huck_01",
            "B_BUNSCArmyDES_D77H_TCI_AV_Pelican_Roland_01",
            "B_BUNSCArmyDES_Hound_01",
            "B_BUNSCArmyDES_Hound_Unarmed_01",
            "B_BUNSCArmyDES_Falcon_Armed_01",
            "B_BUNSCArmyDES_Scorpion_01",
            "B_BUNSCArmyDES_Sun_Devil_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
        /*    "LM_OPCAN_UNSCA",
            "A3_Characters_F",
            "OPTRE_UNSC_Units",
        //    "lambs_danger",
            "OPTRE_UNSC_Units_Army",
            "OPTRE_Ins_Units_BJ",
            "OPTRE_Ins_Units_URF",
            "OPTRE_MJOLNIR",
            "OPTRE_UNSC_Units_ONI",
        //    "kka3_gestures_ace",
            "A3_Sounds_F",
        //    "3rdView",
            "A3_Sounds_F_Exp",
        //    "jsrs_soundmod_complete_edition",
        //    "tfar_core",
        //    "MRHSatellite",
        //    "ace_gforces",
        //    "ace_movement",
        //    "ace_medical_feedback",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
        //    "CUP_Worlds_DustEffects",
        //    "A3_Map_Abramia",
        //    "pja310",
        //    "pja305",
        //    "pja314",
        //    "ibr_panthera_c",
        //    "hebontes",
        //    "ace_thermals",
        //    "zen_attributes",
        //   "ace_refuel",
        //    "CUP_Core",
        //    "cba_xeh",
            "Echo_Company_Armory",
            "V_FZ_Vehicles",
            "OPTRE_Vehicles_Warthog",
        //    "OPTRE_ACE_Compat",
            "A3_Soft_F",
            "A3_Soft_F_Gamma_Hatchback_01",
        //    "fxp_VehCar",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F_ParticleEffects",
        //    "babe_int_EHs",
        //    "A3_Map_Winthera3",
        //    "MRHMilsimTools",
        //    "ace_interaction",
        //    "ace_cargo",
            "A3_Armor_F_Beta",
            "LM_OPCAN_UNSC_VEH",
            "OPTRE_Vehicles_Pelican",
            "OPAEX_Pelican",
            "A3_Air_F",
            "A3_Air_F_Heli_Light_01",
            "A3_Air_F_Heli_Light_02",
            "A3_Air_F_Beta_Heli_Transport_01",
            "OPTRE_Vehicles_Falcon",
            "OPTRE_Vehicles_Hornet",
            "OPAEX_Falcon",
            "OPAEX_Sparrowhawk",
        //    "ace_logistics_uavbattery",
        //    "TFAR_IntercomDummy",
        //    "fxp_VehHeli",
            "A3_Armor_F_Beta_APC_Wheeled_01",
        //    "ace_realisticnames",
        //    "fxp_VehTankWhe",
        //    "ace_vehicles",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
        //    "ace_cookoff",
            "OPTRE_Vehicles_Scorpion",
            "OPTRE_Vehicles_Grizzly",
            "OPAEX_Scorpion",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02",
        //    "ConstructionCrane",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
        //    "fxp_VehTank",
            "A3_Soft_F_Enoch_UGV_02",
            "OPTRE_Vehicles_Elephant" */
        };
        author = "SSgt. C. Varner";
        authors[] = {"SSgt. C. Varner"};
    };
};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 200.146773 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_UNSCArmy_DES {
        displayName = "[105th] Echo Company";
        side = 1;
        flag = "\Echo_Company_Armory\data\Echo_logo.paa";
        icon = "\Echo_Company_Armory\data\Echo_logo.paa";
        priority = 0;
    };
};

class CfgGroups {
    class WEST {

        class B_UNSCArmy_DES {
            name = "[105th] Echo Company";

            class Infantry {
                name = "Infantry";

                class b_bunscarmydes_infantry_squad {
                    name = "Squad";
                    side = 1;
                    faction = "B_UNSCArmy_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Autorifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Grenadier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Marksman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Radio_Telephone_Operator_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Medic_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Rifleman_AT_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Rifleman_AA_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Rifleman_01";
                    };
                };

                class b_bunscarmydes_infantry_at_fireteam {
                    name = "AT Fireteam";
                    side = 1;
                    faction = "B_UNSCArmy_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Autorifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Rifleman_AT_01";
                    };
                };

                class b_bunscarmydes_infantry_aa_fireteam {
                    name = "AA Fireteam";
                    side = 1;
                    faction = "B_UNSCArmy_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Autorifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Rifleman_AA_01";
                    };
                };

                class b_bunscarmydes_infantry_fireteam {
                    name = "Fireteam";
                    side = 1;
                    faction = "B_UNSCArmy_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Grenadier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Autorifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Rifleman_01";
                    };
                };

                class b_bunscarmydes_infantry_sniper_team {
                    name = "Sniper Team";
                    side = 1;
                    faction = "B_UNSCArmy_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Sniper_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNSCArmyDES_Marksman_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class LM_OPCAN_UNSCA_Assaultman_DES;
    class LM_OPCAN_UNSCA_Assaultman_DES_OCimport_01 : LM_OPCAN_UNSCA_Assaultman_DES { scope = 0; class EventHandlers; };
    class LM_OPCAN_UNSCA_Assaultman_DES_OCimport_02 : LM_OPCAN_UNSCA_Assaultman_DES_OCimport_01 { class EventHandlers; };

    class Echo_Warthog_LRV;
    class Echo_Warthog_LRV_OCimport_01 : Echo_Warthog_LRV { scope = 0; class EventHandlers; class Turrets; };
    class Echo_Warthog_LRV_OCimport_02 : Echo_Warthog_LRV_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class LM_OPCAN_HOG_AA_AR_DES;
    class LM_OPCAN_HOG_AA_AR_DES_OCimport_01 : LM_OPCAN_HOG_AA_AR_DES { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_HOG_AA_AR_DES_OCimport_02 : LM_OPCAN_HOG_AA_AR_DES_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class Echo_Warthog_TT;
    class Echo_Warthog_TT_OCimport_01 : Echo_Warthog_TT { scope = 0; class EventHandlers; class Turrets; };
    class Echo_Warthog_TT_OCimport_02 : Echo_Warthog_TT_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoGunner_02;
            class CargoGunner_03;
            class CargoGunner_04;
            class CargoGunner_05;
            class CargoGunner_06;
            class CargoGunner_07;
        };
    };

    class Echo_Warthog_FAV;
    class Echo_Warthog_FAV_OCimport_01 : Echo_Warthog_FAV { scope = 0; class EventHandlers; class Turrets; };
    class Echo_Warthog_FAV_OCimport_02 : Echo_Warthog_FAV_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class Echo_Pelican_ARMY;
    class Echo_Pelican_ARMY_OCimport_01 : Echo_Pelican_ARMY { scope = 0; class EventHandlers; class Turrets; };
    class Echo_Pelican_ARMY_OCimport_02 : Echo_Pelican_ARMY_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class Echo_Pelican_Jaeger;
    class Echo_Pelican_Jaeger_OCimport_01 : Echo_Pelican_Jaeger { scope = 0; class EventHandlers; class Turrets; };
    class Echo_Pelican_Jaeger_OCimport_02 : Echo_Pelican_Jaeger_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class Echo_Pelican_Huck;
    class Echo_Pelican_Huck_OCimport_01 : Echo_Pelican_Huck { scope = 0; class EventHandlers; class Turrets; };
    class Echo_Pelican_Huck_OCimport_02 : Echo_Pelican_Huck_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class Echo_Pelican_Roland;
    class Echo_Pelican_Roland_OCimport_01 : Echo_Pelican_Roland { scope = 0; class EventHandlers; class Turrets; };
    class Echo_Pelican_Roland_OCimport_02 : Echo_Pelican_Roland_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class LM_OPCAN_AFV102_AR_DES;
    class LM_OPCAN_AFV102_AR_DES_OCimport_01 : LM_OPCAN_AFV102_AR_DES { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_AFV102_AR_DES_OCimport_02 : LM_OPCAN_AFV102_AR_DES_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class LM_OPCAN_AFV102_AR_U_DES;
    class LM_OPCAN_AFV102_AR_U_DES_OCimport_01 : LM_OPCAN_AFV102_AR_U_DES { scope = 0; class EventHandlers; };
    class LM_OPCAN_AFV102_AR_U_DES_OCimport_02 : LM_OPCAN_AFV102_AR_U_DES_OCimport_01 { scope = 0; class EventHandlers; };

    class Echo_Falcon_Armed;
    class Echo_Falcon_Armed_OCimport_01 : Echo_Falcon_Armed { scope = 0; class EventHandlers; class Turrets; };
    class Echo_Falcon_Armed_OCimport_02 : Echo_Falcon_Armed_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class Echo_M808;
    class Echo_M808_OCimport_01 : Echo_M808 { scope = 0; class EventHandlers; class Turrets; };
    class Echo_M808_OCimport_02 : Echo_M808_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret1;
            class CargoTurret2;
            class CargoTurret3;
            class CargoTurret4;
            class CargoTurret5;
            class CargoTurret6;
            class CargoTurret7;
            class CargoTurret8;
            class MainTurret;
        };
    };

    class Echo_M808B2;
    class Echo_M808B2_OCimport_01 : Echo_M808B2 { scope = 0; class EventHandlers; class Turrets; };
    class Echo_M808B2_OCimport_02 : Echo_M808B2_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret1;
            class CargoTurret2;
            class CargoTurret3;
            class CargoTurret4;
            class CargoTurret5;
            class CargoTurret6;
            class CargoTurret7;
            class CargoTurret8;
            class MainTurret;
        };
    };


    class B_BUNSCArmyDES_Rifleman_01 : LM_OPCAN_UNSCA_Assaultman_DES_OCimport_02 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 1;
        faction = "B_UNSCArmy_DES";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_SLIM_UNSCA_DES_1_UNI";

        linkedItems[] = {"Echo_M52A_R_B_B","Echo_CH252_H1_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};
        respawnlinkedItems[] = {"Echo_M52A_R_B_B","Echo_CH252_H1_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};

        weapons[] = {"OPTRE_MA37","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_MA37","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Echo_Rucksack_Soft";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_SLIM_UNSCA_DES_1_UNI",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",1,1}}},{"Echo_M52A_R_B_B",{{"OPTRE_Biofoam",2},{"ACE_packingBandage",5},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_bloodIV_250",1},{"ACE_EarPlugs",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_personalAidKit",1},{"ACE_tourniquet",4},{"OPTRE_32Rnd_762x51_Mag",8,32},{"OPTRE_8Rnd_127x40_Mag",3,8},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1}}},{"Echo_Rucksack_Soft",{{"VES_TacSpraycan",2},{"ACE_splint",4},{"MRH_KeyCard_BLUFOR",1},{"ACE_RangeCard",1},{"ACE_personalAidKit",2},{"MRH_SoldierTab",1},{"ACE_morphine",5},{"ACE_MRE_BeefStew",1},{"ACE_M26_Clacker",1},{"ACE_IR_Strobe_Item",1},{"ACE_epinephrine",5},{"ACE_EntrenchingTool",1},{"ACE_Canteen",1},{"ACE_Flashlight_MX991",1}}},"Echo_CH252_H1_T","LM_OPCAN_BRW_Shemagheye",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Autorifleman_01 : B_BUNSCArmyDES_Rifleman_01 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman";
        side = 1;
        faction = "B_UNSCArmy_DES";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_SLIM_UNSCA_DES_1_UNI";

        linkedItems[] = {"Echo_M52A_AR_B","Echo_CH252_H1_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};
        respawnlinkedItems[] = {"Echo_M52A_AR_B","Echo_CH252_H1_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};

        weapons[] = {"v105_HOW_M247SSW","OPTRE_M6G_SF"};
        respawnWeapons[] = {"v105_HOW_M247SSW","OPTRE_M6G_SF"};

        magazines[] = {"HOW_200Rnd_93x64_Box","OPTRE_8Rnd_127x40_Mag","HOW_200Rnd_93x64_Box","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"HOW_200Rnd_93x64_Box","OPTRE_8Rnd_127x40_Mag","HOW_200Rnd_93x64_Box","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Echo_Rucksack_Soft_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"v105_HOW_M247SSW","","OPTRE_M45_Flashlight","OPTRE_M392_Scope_v2",{"HOW_200Rnd_93x64_Box",200},{},"bipod_01_F_blk"},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_SLIM_UNSCA_DES_1_UNI",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",1,1},{"HOW_200Rnd_93x64_Mixed_Box",3,200}}},{"Echo_M52A_AR_B",{{"OPTRE_Biofoam",2},{"ACE_packingBandage",5},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_bloodIV_250",1},{"ACE_EarPlugs",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_personalAidKit",1},{"ACE_tourniquet",4},{"OPTRE_8Rnd_127x40_Mag",3,8},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"HOW_200Rnd_93x64_Mixed_Box",1,200}}},{"Echo_Rucksack_Soft_Heavy",{{"VES_TacSpraycan",2},{"ACE_splint",4},{"MRH_KeyCard_BLUFOR",1},{"ACE_RangeCard",1},{"ACE_personalAidKit",2},{"MRH_SoldierTab",1},{"ACE_morphine",5},{"ACE_MRE_BeefStew",1},{"ACE_M26_Clacker",1},{"ACE_IR_Strobe_Item",1},{"ACE_epinephrine",5},{"ACE_EntrenchingTool",1},{"ACE_Canteen",1},{"ACE_Flashlight_MX991",1},{"HOW_200Rnd_93x64_Mixed_Box",6,200}}},"Echo_CH252_H1_T","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Grenadier_01 : B_BUNSCArmyDES_Rifleman_01 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 1;
        faction = "B_UNSCArmy_DES";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_SLIM_UNSCA_DES_1_UNI";

        linkedItems[] = {"Echo_M52A_GRE_B","Echo_CH252_H2_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};
        respawnlinkedItems[] = {"Echo_M52A_GRE_B","Echo_CH252_H2_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};

        weapons[] = {"OPTRE_MA37GL","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_MA37GL","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","UGL_8Gauge_Pellet","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","UGL_8Gauge_Pellet","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","UGL_8Gauge_Pellet","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","UGL_8Gauge_Pellet","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Echo_Rucksack_Soft";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37GL","","","",{"OPTRE_32Rnd_762x51_Mag",32},{"UGL_8Gauge_Pellet",1},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_SLIM_UNSCA_DES_1_UNI",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",1,1},{"OPTRE_32Rnd_762x51_Mag",3,32},{"UGL_8Gauge_Pellet",3,1}}},{"Echo_M52A_GRE_B",{{"OPTRE_Biofoam",2},{"ACE_packingBandage",5},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_bloodIV_250",1},{"ACE_EarPlugs",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_personalAidKit",1},{"ACE_tourniquet",4},{"OPTRE_8Rnd_127x40_Mag",3,8},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_32Rnd_762x51_Mag",8,32},{"1Rnd_HE_Grenade_shell",4,1}}},{"Echo_Rucksack_Soft",{{"VES_TacSpraycan",2},{"ACE_splint",4},{"MRH_KeyCard_BLUFOR",1},{"ACE_RangeCard",1},{"ACE_personalAidKit",2},{"MRH_SoldierTab",1},{"ACE_morphine",5},{"ACE_MRE_BeefStew",1},{"ACE_M26_Clacker",1},{"ACE_IR_Strobe_Item",1},{"ACE_epinephrine",5},{"ACE_EntrenchingTool",1},{"ACE_Canteen",1},{"ACE_Flashlight_MX991",1}}},"Echo_CH252_H2_T","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Squad_Leader_01 : B_BUNSCArmyDES_Rifleman_01 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 1;
        faction = "B_UNSCArmy_DES";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_SLIM_UNSCA_DES_1_UNI";

        linkedItems[] = {"Echo_M52A_NCO_B_A","Echo_Patrolcap_MCAM","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2"};
        respawnlinkedItems[] = {"Echo_M52A_NCO_B_A","Echo_Patrolcap_MCAM","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2"};

        weapons[] = {"OPTRE_MA37","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_MA37","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Echo_Rucksack_Soft";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_SLIM_UNSCA_DES_1_UNI",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",1,1}}},{"Echo_M52A_NCO_B_A",{{"OPTRE_Biofoam",2},{"ACE_packingBandage",5},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_bloodIV_250",1},{"ACE_EarPlugs",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_personalAidKit",1},{"ACE_tourniquet",4},{"OPTRE_32Rnd_762x51_Mag",8,32},{"OPTRE_8Rnd_127x40_Mag",3,8},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1}}},{"Echo_Rucksack_Soft",{{"VES_TacSpraycan",2},{"ACE_splint",4},{"MRH_KeyCard_BLUFOR",1},{"ACE_RangeCard",1},{"ACE_personalAidKit",2},{"MRH_SoldierTab",1},{"ACE_morphine",5},{"ACE_MRE_BeefStew",1},{"ACE_M26_Clacker",1},{"ACE_IR_Strobe_Item",1},{"ACE_epinephrine",5},{"ACE_EntrenchingTool",1},{"ACE_Canteen",1},{"ACE_Flashlight_MX991",1}}},"Echo_Patrolcap_MCAM","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Marksman_01 : B_BUNSCArmyDES_Rifleman_01 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 1;
        faction = "B_UNSCArmy_DES";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_SLIM_UNSCA_DES_1_UNI";

        linkedItems[] = {"Echo_M52A_MRK_B","Echo_Tactical_Boonie_Khk","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2"};
        respawnlinkedItems[] = {"Echo_M52A_MRK_B","Echo_Tactical_Boonie_Khk","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2"};

        weapons[] = {"OPTRE_M392_DMR","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M392_DMR","OPTRE_M6G_SF"};

        magazines[] = {"HOW_15Rnd_762x51_338_API_Mag","OPTRE_8Rnd_127x40_Mag","HOW_15Rnd_762x51_338_API_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"HOW_15Rnd_762x51_338_API_Mag","OPTRE_8Rnd_127x40_Mag","HOW_15Rnd_762x51_338_API_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Echo_Rucksack_Soft";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M392_DMR","","OPTRE_BMR_Laser","OPTRE_BMR_Scope_v2",{"HOW_15Rnd_762x51_338_API_Mag",15},{},"bipod_01_F_blk"},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_SLIM_UNSCA_DES_1_UNI",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",1,1},{"HOW_15Rnd_762x51_338_API_Mag",3,15}}},{"Echo_M52A_MRK_B",{{"OPTRE_Biofoam",2},{"ACE_packingBandage",5},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_bloodIV_250",1},{"ACE_EarPlugs",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_personalAidKit",1},{"ACE_tourniquet",4},{"OPTRE_8Rnd_127x40_Mag",3,8},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"HOW_15Rnd_762x51_338_Magnum_Mag",9,15}}},{"Echo_Rucksack_Soft",{{"VES_TacSpraycan",2},{"ACE_splint",4},{"MRH_KeyCard_BLUFOR",1},{"ACE_RangeCard",1},{"ACE_personalAidKit",2},{"MRH_SoldierTab",1},{"ACE_morphine",5},{"ACE_MRE_BeefStew",1},{"ACE_M26_Clacker",1},{"ACE_IR_Strobe_Item",1},{"ACE_epinephrine",5},{"ACE_EntrenchingTool",1},{"ACE_Canteen",1},{"ACE_Flashlight_MX991",1}}},"Echo_Tactical_Boonie_Khk","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Sniper_01 : B_BUNSCArmyDES_Marksman_01 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 1;
        faction = "B_UNSCArmy_DES";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_SLIM_UNSCA_DES_1_UNI";

        linkedItems[] = {"Echo_M52A_SNI_B","Echo_Tactical_Boonie_Khk","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2"};
        respawnlinkedItems[] = {"Echo_M52A_SNI_B","Echo_Tactical_Boonie_Khk","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2"};

        weapons[] = {"v105_408_SRSC","OPTRE_M6G_SF"};
        respawnWeapons[] = {"v105_408_SRSC","OPTRE_M6G_SF"};

        magazines[] = {"ACE_7Rnd_408_305gr_Mag","OPTRE_8Rnd_127x40_Mag","ACE_7Rnd_408_305gr_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"ACE_7Rnd_408_305gr_Mag","OPTRE_8Rnd_127x40_Mag","ACE_7Rnd_408_305gr_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Echo_Rucksack_Soft";

        ALiVE_orbatCreator_loadout[] = {{"v105_408_SRSC","","","OPTRE_SRS99C_Scope",{"ACE_7Rnd_408_305gr_Mag",7},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_SLIM_UNSCA_DES_1_UNI",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",1,1},{"ACE_7Rnd_408_305gr_Mag",3,7}}},{"Echo_M52A_SNI_B",{{"OPTRE_Biofoam",2},{"ACE_packingBandage",5},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_bloodIV_250",1},{"ACE_EarPlugs",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_personalAidKit",1},{"ACE_tourniquet",4},{"OPTRE_8Rnd_127x40_Mag",3,8},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"7Rnd_408_Mag",6,7}}},{"Echo_Rucksack_Soft",{{"VES_TacSpraycan",2},{"ACE_splint",4},{"MRH_KeyCard_BLUFOR",1},{"ACE_RangeCard",1},{"ACE_personalAidKit",2},{"MRH_SoldierTab",1},{"ACE_morphine",5},{"ACE_MRE_BeefStew",1},{"ACE_M26_Clacker",1},{"ACE_IR_Strobe_Item",1},{"ACE_epinephrine",5},{"ACE_EntrenchingTool",1},{"ACE_Canteen",1},{"ACE_Flashlight_MX991",1}}},"Echo_Tactical_Boonie_Khk","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Crewman_01 : B_BUNSCArmyDES_Rifleman_01 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 1;
        faction = "B_UNSCArmy_DES";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_SLIM_UNSCA_DES_1_UNI";

        linkedItems[] = {"Echo_M52A_CRE_B","Echo_CH252_Armor_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};
        respawnlinkedItems[] = {"Echo_M52A_CRE_B","Echo_CH252_Armor_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};

        weapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","",{"OPTRE_60Rnd_5x23mm_Mag",60},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_SLIM_UNSCA_DES_1_UNI",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",1,1},{"OPTRE_60Rnd_5x23mm_Mag",3,60}}},{"Echo_M52A_CRE_B",{{"OPTRE_Biofoam",2},{"ACE_packingBandage",5},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_bloodIV_250",1},{"ACE_EarPlugs",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_personalAidKit",1},{"ACE_tourniquet",4},{"OPTRE_8Rnd_127x40_Mag",3,8},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_60Rnd_5x23mm_Mag_FMJ",12,60}}},{},"Echo_CH252_Armor_T","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Aviator_01 : B_BUNSCArmyDES_Crewman_01 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Aviator";
        side = 1;
        faction = "B_UNSCArmy_DES";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_SLIM_UNSCA_DES_1_UNI";

        linkedItems[] = {"Echo_M52A_AVI_B","Echo_VX16_Jaeger_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};
        respawnlinkedItems[] = {"Echo_M52A_AVI_B","Echo_VX16_Jaeger_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};

        weapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","",{"OPTRE_60Rnd_5x23mm_Mag",60},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_SLIM_UNSCA_DES_1_UNI",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",1,1},{"OPTRE_60Rnd_5x23mm_Mag",3,60}}},{"Echo_M52A_AVI_B",{{"OPTRE_Biofoam",2},{"ACE_packingBandage",5},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_bloodIV_250",1},{"ACE_EarPlugs",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_personalAidKit",1},{"ACE_tourniquet",4},{"OPTRE_8Rnd_127x40_Mag",3,8},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1},{"OPTRE_60Rnd_5x23mm_Mag_FMJ",12,60}}},{},"Echo_VX16_Jaeger_T","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Medic_01 : B_BUNSCArmyDES_Rifleman_01 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 1;
        faction = "B_UNSCArmy_DES";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_SLIM_UNSCA_DES_1_UNI";

        linkedItems[] = {"Echo_M52A_MED_B_B","Echo_CH252_H_M_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};
        respawnlinkedItems[] = {"Echo_M52A_MED_B_B","Echo_CH252_H_M_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};

        weapons[] = {"OPTRE_MA37","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_MA37","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Echo_Rucksack_Soft_Medical";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_SLIM_UNSCA_DES_1_UNI",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",1,1}}},{"Echo_M52A_MED_B_B",{{"OPTRE_Biofoam",2},{"ACE_packingBandage",5},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_bloodIV_250",1},{"ACE_EarPlugs",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_personalAidKit",1},{"ACE_tourniquet",4},{"OPTRE_32Rnd_762x51_Mag",8,32},{"OPTRE_8Rnd_127x40_Mag",3,8},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1}}},{"Echo_Rucksack_Soft_Medical",{{"VES_TacSpraycan",2},{"ACE_splint",4},{"MRH_KeyCard_BLUFOR",1},{"ACE_RangeCard",1},{"ACE_personalAidKit",2},{"MRH_SoldierTab",1},{"ACE_morphine",5},{"ACE_MRE_BeefStew",1},{"ACE_M26_Clacker",1},{"ACE_IR_Strobe_Item",1},{"ACE_epinephrine",5},{"ACE_EntrenchingTool",1},{"ACE_Canteen",1},{"ACE_Flashlight_MX991",1},{"ACE_packingBandage",25},{"ACE_elasticBandage",25},{"ACE_fieldDressing",25},{"ACE_quikclot",25},{"OPTRE_Biofoam",2},{"ACE_bloodIV",1},{"ACE_bloodIV_250",1},{"ACE_bloodIV_500",1},{"ACE_surgicalKit",1},{"ACE_WaterBottle",2}}},"Echo_CH252_H_M_T","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Radio_Telephone_Operator_01 : B_BUNSCArmyDES_Rifleman_01 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Radio Telephone Operator";
        side = 1;
        faction = "B_UNSCArmy_DES";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_SLIM_UNSCA_DES_1_UNI";

        linkedItems[] = {"Echo_M52A_RTO_B","Echo_CH252_H_RTO_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};
        respawnlinkedItems[] = {"Echo_M52A_RTO_B","Echo_CH252_H_RTO_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};

        weapons[] = {"OPTRE_MA37","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_MA37","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Echo_ANPRC_521_Standard";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_SLIM_UNSCA_DES_1_UNI",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",1,1}}},{"Echo_M52A_RTO_B",{{"OPTRE_Biofoam",2},{"ACE_packingBandage",5},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_bloodIV_250",1},{"ACE_EarPlugs",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_personalAidKit",1},{"ACE_tourniquet",4},{"OPTRE_32Rnd_762x51_Mag",8,32},{"OPTRE_8Rnd_127x40_Mag",3,8},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1}}},{"Echo_ANPRC_521_Standard",{{"VES_TacSpraycan",2},{"ACE_splint",4},{"MRH_KeyCard_BLUFOR",1},{"ACE_RangeCard",1},{"ACE_personalAidKit",2},{"MRH_SoldierTab",1},{"ACE_morphine",5},{"ACE_MRE_BeefStew",1},{"ACE_M26_Clacker",1},{"ACE_IR_Strobe_Item",1},{"ACE_epinephrine",5},{"ACE_EntrenchingTool",1},{"ACE_Canteen",1},{"ACE_Flashlight_MX991",1}}},"Echo_CH252_H_RTO_T","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Warthog_LAAG_01 : Echo_Warthog_LRV_OCimport_02 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Warthog LAAG";
        side = 1;
        faction = "B_UNSCArmy_DES";
        crew = "VES_Rifleman_MA5B_MAR";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = ""; };
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Warthog_AA_01 : LM_OPCAN_HOG_AA_AR_DES_OCimport_02 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Warthog AA";
        side = 1;
        faction = "B_UNSCArmy_DES";
        crew = "B_BUNSCArmyDES_Rifleman_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "B_BUNSCArmyDES_Grenadier_01"; };
            class MainTurret : MainTurret { gunnerType = "B_BUNSCArmyDES_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles\Warthog\data\warthog_black_co.paa'];_unit setObjectTextureGlobal [1,'OPTRE_Vehicles\Warthog\data\warthog_aa_black_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorblack";

    };

    class B_BUNSCArmyDES_Rifleman_AT_01 : B_BUNSCArmyDES_Rifleman_01 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman AT";
        side = 1;
        faction = "B_UNSCArmy_DES";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_SLIM_UNSCA_DES_1_UNI";

        linkedItems[] = {"Echo_M52A_R_B_B","Echo_CH252_H1_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};
        respawnlinkedItems[] = {"Echo_M52A_R_B_B","Echo_CH252_H1_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};

        weapons[] = {"OPTRE_MA37","OPTRE_M48_PAW","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_MA37","OPTRE_M48_PAW","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_1Rnd_50x137_HEAT","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_1Rnd_50x137_HEAT","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Echo_Rucksack_Soft";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{"OPTRE_M48_PAW","","","",{"OPTRE_1Rnd_50x137_HEAT",1},{},""},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_SLIM_UNSCA_DES_1_UNI",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",1,1}}},{"Echo_M52A_R_B_B",{{"OPTRE_Biofoam",2},{"ACE_packingBandage",5},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_bloodIV_250",1},{"ACE_EarPlugs",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_personalAidKit",1},{"ACE_tourniquet",4},{"OPTRE_32Rnd_762x51_Mag",8,32},{"OPTRE_8Rnd_127x40_Mag",3,8},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1}}},{"Echo_Rucksack_Soft",{{"VES_TacSpraycan",2},{"ACE_splint",4},{"MRH_KeyCard_BLUFOR",1},{"ACE_RangeCard",1},{"ACE_personalAidKit",2},{"MRH_SoldierTab",1},{"ACE_morphine",5},{"ACE_MRE_BeefStew",1},{"ACE_M26_Clacker",1},{"ACE_IR_Strobe_Item",1},{"ACE_epinephrine",5},{"ACE_EntrenchingTool",1},{"ACE_Canteen",1},{"ACE_Flashlight_MX991",1},{"OPTRE_1Rnd_50x137_HEAT",3,1},{"OPTRE_1Rnd_50x137_PEN",3,1}}},"Echo_CH252_H1_T","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Rifleman_AA_01 : B_BUNSCArmyDES_Rifleman_AT_01 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman AA";
        side = 1;
        faction = "B_UNSCArmy_DES";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_SLIM_UNSCA_DES_1_UNI";

        linkedItems[] = {"Echo_M52A_R_B_B","Echo_CH252_H1_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};
        respawnlinkedItems[] = {"Echo_M52A_R_B_B","Echo_CH252_H1_T","ItemMap","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"};

        weapons[] = {"OPTRE_MA37","MatGrp_M41_SSR_AA","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_MA37","MatGrp_M41_SSR_AA","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","MatGrp_M41_Twin_HEAT_AA","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","MatGrp_M41_Twin_HEAT_AA","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "Echo_Rucksack_Soft";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{"MatGrp_M41_SSR_AA","","","",{"MatGrp_M41_Twin_HEAT_AA",2},{},""},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_SLIM_UNSCA_DES_1_UNI",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",1,1}}},{"Echo_M52A_R_B_B",{{"OPTRE_Biofoam",2},{"ACE_packingBandage",5},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_bloodIV_250",1},{"ACE_EarPlugs",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_personalAidKit",1},{"ACE_tourniquet",4},{"OPTRE_32Rnd_762x51_Mag",8,32},{"OPTRE_8Rnd_127x40_Mag",3,8},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",2,1}}},{"Echo_Rucksack_Soft",{{"VES_TacSpraycan",2},{"ACE_splint",4},{"MRH_KeyCard_BLUFOR",1},{"ACE_RangeCard",1},{"ACE_personalAidKit",2},{"MRH_SoldierTab",1},{"ACE_morphine",5},{"ACE_MRE_BeefStew",1},{"ACE_M26_Clacker",1},{"ACE_IR_Strobe_Item",1},{"ACE_epinephrine",5},{"ACE_EntrenchingTool",1},{"ACE_Canteen",1},{"ACE_Flashlight_MX991",1},{"MatGrp_M41_Twin_HEAT_AA",3,2}}},"Echo_CH252_H1_T","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","A3_TVG_S_F2_HURS"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Warthog_TT_01 : Echo_Warthog_TT_OCimport_02 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Warthog TT";
        side = 1;
        faction = "B_UNSCArmy_DES";
        crew = "VES_Rifleman_MA5B_MAR";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = ""; };
            class CargoGunner_02 : CargoGunner_02 { gunnerType = ""; };
            class CargoGunner_03 : CargoGunner_03 { gunnerType = ""; };
            class CargoGunner_04 : CargoGunner_04 { gunnerType = ""; };
            class CargoGunner_05 : CargoGunner_05 { gunnerType = ""; };
            class CargoGunner_06 : CargoGunner_06 { gunnerType = ""; };
            class CargoGunner_07 : CargoGunner_07 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Warthog_Unarmed_01 : Echo_Warthog_FAV_OCimport_02 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Warthog Unarmed";
        side = 1;
        faction = "B_UNSCArmy_DES";
        crew = "VES_Rifleman_MA5B_MAR";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_D77H_TCI_AV_Pelican_01 : Echo_Pelican_ARMY_OCimport_02 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "D77H-TCI/AV Pelican";
        side = 1;
        faction = "B_UNSCArmy_DES";
        crew = "B_BUNSCArmyDES_Aviator_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_BUNSCArmyDES_Aviator_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_D77H_TCI_AV_Pelican_Jaeger_01 : Echo_Pelican_Jaeger_OCimport_02 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "D77H-TCI/AV Pelican [Jaeger]";
        side = 1;
        faction = "B_UNSCArmy_DES";
        crew = "OPTRE_UNSC_Marine_Pilot";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_D77H_TCI_AV_Pelican_Huck_01 : Echo_Pelican_Huck_OCimport_02 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "D77H-TCI/AV Pelican [Huck]";
        side = 1;
        faction = "B_UNSCArmy_DES";
        crew = "OPTRE_UNSC_Marine_Pilot";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_D77H_TCI_AV_Pelican_Roland_01 : Echo_Pelican_Roland_OCimport_02 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "D77H-TCI/AV Pelican [Roland]";
        side = 1;
        faction = "B_UNSCArmy_DES";
        crew = "OPTRE_UNSC_Marine_Pilot";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Hound_01 : LM_OPCAN_AFV102_AR_DES_OCimport_02 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hound";
        side = 1;
        faction = "B_UNSCArmy_DES";
        crew = "B_BUNSCArmyDES_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_BUNSCArmyDES_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Hound_Unarmed_01 : LM_OPCAN_AFV102_AR_U_DES_OCimport_02 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hound Unarmed";
        side = 1;
        faction = "B_UNSCArmy_DES";
        crew = "B_BUNSCArmyDES_Crewman_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Falcon_Armed_01 : Echo_Falcon_Armed_OCimport_02 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Falcon Armed";
        side = 1;
        faction = "B_UNSCArmy_DES";
        crew = "OPTRE_UNSC_Airforce_Soldier_Airman";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Scorpion_01 : Echo_M808_OCimport_02 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Scorpion";
        side = 1;
        faction = "B_UNSCArmy_DES";
        crew = "VES_Rifleman_MA5B_MAR";

        class Turrets : Turrets {
            class CargoTurret1 : CargoTurret1 { gunnerType = ""; };
            class CargoTurret2 : CargoTurret2 { gunnerType = ""; };
            class CargoTurret3 : CargoTurret3 { gunnerType = ""; };
            class CargoTurret4 : CargoTurret4 { gunnerType = ""; };
            class CargoTurret5 : CargoTurret5 { gunnerType = ""; };
            class CargoTurret6 : CargoTurret6 { gunnerType = ""; };
            class CargoTurret7 : CargoTurret7 { gunnerType = ""; };
            class CargoTurret8 : CargoTurret8 { gunnerType = ""; };
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNSCArmyDES_Sun_Devil_01 : Echo_M808B2_OCimport_02 {
        author = "SSgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sun Devil";
        side = 1;
        faction = "B_UNSCArmy_DES";
        crew = "VES_Rifleman_MA5B_MAR";

        class Turrets : Turrets {
            class CargoTurret1 : CargoTurret1 { gunnerType = ""; };
            class CargoTurret2 : CargoTurret2 { gunnerType = ""; };
            class CargoTurret3 : CargoTurret3 { gunnerType = ""; };
            class CargoTurret4 : CargoTurret4 { gunnerType = ""; };
            class CargoTurret5 : CargoTurret5 { gunnerType = ""; };
            class CargoTurret6 : CargoTurret6 { gunnerType = ""; };
            class CargoTurret7 : CargoTurret7 { gunnerType = ""; };
            class CargoTurret8 : CargoTurret8 { gunnerType = ""; };
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};