//Scope Masterlist - Black variants specifically
//  OPTRE Scopes
"OPTRE_BR45_Scope",
"OPTRE_BR55HB_Scope",
"OPTRE_SRS99C_Scope",
"OPTRE_SRS99_Scope",
"OPTRE_M393_EOTECH",
"OPTRE_SRM_Sight",
"OPTRE_M392_Scope",
"OPTRE_HMG38_CarryHandle",
"OPTRE_M12_Optic",
"OPTRE_M393_ACOG",
"OPTRE_BMR_Scope",
"OPTRE_M7_Scope",
"OPTRE_M73_SmartLink",
"OPTRE_MA5_SmartLink",
"OPTRE_MA5_BUIS",  // Alternate Iron Sights for MA5
"OPTRE_MA5C_SmartLink",
"OPTRE_MA5C_SmartLink_legacy",
// OPTRE Pistol Sights
"OPTRE_M6S_Scope",
"OPTRE_M6G_Scope",
"OPTRE_M6GX_Scope",
"OPTR_M6D_Smartlink",
"OPTRE_M6C_Scope",
// OPTRE V2
"OPTRE_MA5C_SmartLink_v2",
"OPTRE_M73_Smartlink_v2",
"OPTRE_M7_Sight_v2",
"OPTRE_BMR_Scope_v2",
"OPTRE_M393_ACOG_v2",
"OPTRE_M393_EOTECH_v2",
"OPTRE_M392_Scope_v2",
"OPTRE_SRS99_Scope_v2",
"OPTRE_BR55HB_Scope_v2",
"OPTRE_SRS99C_Scope_v2",
//  A3 Scopes
"optic_Yorris",
"optic_DMS",
"optic_DMS_weathered_F",
"optic_Arco_blk_F",
"optic_Aco",
"optic_ACO_grn",
"optic_ACO_grn_smg",
"optic_ACO_smg",
"optic_Arco_blk_F",
"optic_Holosight_blk_F",
"optic_Holosight_smg_blk_F",
"optic_MRCO",
"optic_KHS_blk",
"optic_Hamr",
"optic_SOS",
"optic_MRD_black",
"optic_LRPS",
"optic_Nightstalker",
"optic_NVS",
"optic_ico_01_black_f",
"optic_ERCO_blk_F",
"optic_tws",
"optic_tws_mg",
"optic_AMS",
// ACE Scopes
"ACE_optic_Arco_2D",
"ACE_optic_Arco_PIP",
"ACE_optic_LRPS_2D",
"ACE_optic_LRPS_PIP",
"ACE_optic_Hamr_2D",
"ACE_optic_Hamr_PIP",
"ACE_optic_SOS_2D",
"ACE_optic_SOS_PIP",
"ACE_optic_MRCO_2D",