//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_URFArmy_ARID {
        displayName = "[105th] United Rebel Front (Arid Climate)";
        side = 0;
        flag = "ca\Ca_E\data\flag_opfor_co.paa";
        icon = "ca\Ca_E\data\flag_opfor_co.paa";
        priority = 0;
    };
};