//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups 
{
    class EAST 
    {
        class O_URFArmy_ARID 
        {
            name = "[105th] United Rebel Front (Arid Climate)";

            class Infantry 
            {
                name = "Infantry";
                class O_URFArmy_ARID_infantry_regular_patrol {
                    name = "Infantry Patrol";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                };
                class O_URFArmy_ARID_infantry_regular_fireteam {
                    name = "Infantry Fireteam";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                };
                class O_URFArmy_ARID_infantry_regular_at_fireteam {
                    name = "Infantry AT Fireteam";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Heavy_AT_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Light_AT_01";
                    };
                };

                class O_URFArmy_ARID_infantry_regular_aa_fireteam {
                    name = "Infantry AA Fireteam";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Anti_Air_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Autorifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                };

                class O_URFArmy_ARID_infantry_regular_squad_1 {
                    name = "Infantry Squad 1";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Grenadier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Autorifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Medic_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Light_AT_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Grenadier_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Marksman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Autorifleman_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                };
                class O_URFArmy_ARID_infantry_regular_squad_2 {
                    name = "Infantry Squad 2";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Team_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Autorifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Medic_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Light_AT_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Team_Leader_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Light_AT_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Autorifleman_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                };
                class O_URFArmy_ARID_infantry_regular_squad_3 {
                    name = "Infantry Squad 3";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Team_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Light_AT_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Autorifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Medic_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Grenadier_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Heavy_AT_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Marksman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Light_AT_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Heavy_AT_01";
                    };
                };
                

                class O_URFArmy_ARID_infantry_regular_command_squad {
                    name = "Infantry Command Squad";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Officer_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Grenadier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Marksman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                };

            }; // Infantry
            class Support 
            {
                name = "Support Infantry";

                class O_URFArmy_ARID_support_assault_infantry {
                    name = "Rifle Squad";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                };
                class O_URFArmy_ARID_support_weapons_squad {
                    name = "Weapons Squad";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Autorifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Autorifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit9 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Autorifleman_01";
                    };
                };
                class O_URFArmy_ARID_support_weapons_fireteam {
                    name = "Weapons Fireteam";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Autorifleman_01";
                    };
                };

            }; // End Support Infantry


            class SpecOps {
                name = "Special Forces";

                class O_URFArmy_ARID_specops_regular_sniper_team {
                    name = "Sniper Team";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Sniper_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Sniper_01";
                    };
                };
                class O_URFArmy_ARID_specops_assaultsquad_fireteam {
                    name = "Assault Fireteam";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Assault_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Assault_Marksman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Assault_Breacher_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Assault_Grenadier_01";
                    };
                };

            
                class O_URFArmy_ARID_specops_battlejumper_fireteam {
                    name = "Battlejumper Fireteam";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Battlejumper_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Battlejumper_AutoRifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Battlejumper_Assaultman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Battlejumper_Breacher_01";
                    };
                };
            }; //End Spec Force
            class Motorized 
            {
                name = "Motorized Infantry";

                class O_URFArmy_ARID_motorized_motorized_infantry_fireteam {
                    name = "Motorized Infantry Fireteam";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_M12_APC_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Team_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Autorifleman_01";
                    };
                    class Unit4 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Marksman_01";
                    };
                };

                class O_URFArmy_ARID_motorized_motorized_infantry_recon_team {
                    name = "Motorized MG Infantry Recon Team";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rake_V5_HMG_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Assault_Leader_01";
                    };
                    class Unit2 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Assault_Marksman_01";
                    };
                };

                class O_URFArmy_ARID_motorized_motorized_infantry_at_recon_team {
                    name = "Motorized Infantry Recon Team";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rake_V5_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Assault_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Assault_Breacher_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Assault_Marksman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Assault_Leader_01";
                    };
                };

                class O_URFArmy_ARID_motorized_motorized_infantry_squad {
                    name = "Motorized Infantry Squad";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_M1069_Burro_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Autorifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Marksman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Medic_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Light_AT_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Light_AT_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Grenadier_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit12 {
                        position[] = {-30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                };
                class O_URFArmy_ARID_motorized_motorized_rifle_squad {
                    name = "Motorized Rifle Squad";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_M1069_Burro_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit12 {
                        position[] = {-30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                };
                class O_URFArmy_ARID_motorized_warthog__patrol {
                    name = "Warthog LAAG/APC Patrol";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_M12_LRV_LAAG_01";
                    };
                    class Unit1 {
                        position[] = {0,-7,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_M12_APC_01";
                    };
                    class Unit2 {
                        position[] = {7,-7,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {9,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-7,-7,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {-9,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };

                };
                class O_URFArmy_ARID_motorized_warthog_laag_patrol {
                    name = "Warthog LAAG Patrol";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_M12_LRV_LAAG_01";
                    };
                };

                class O_URFArmy_ARID_motorized_warthog_atgm_patrol {
                    name = "Warthog ATGM Patrol";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_M12A1_LRV_Rocket_01";
                    };
                };
                
                

            }; // End Motorized Infantry

            
            class Mechanized
            {
                name = "Mechanized Infantry";

                class O_URFArmy_ARID_mechanized_mechanized_infantry_squad {
                    name = "Mechanized Infantry Squad";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_APC_112_Fox_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Team_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Grenadier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Grenadier_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Autorifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Medic_01";
                    };
                };

                class O_URFArmy_ARID_mechanized_apc112_fox_patrol {
                    name = "APC-112 Fox Patrol";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_APC_112_Fox_01";
                    };
                    class Unit1 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_APC_112_Fox_01";
                    };
                };
                class O_URFArmy_ARID_mechanized_mgs32_timberwolf_section {
                    name = "MGS-32 Timberwolf Section";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_MGS_32_TimberWolf_01";
                    };
                    class Unit1 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_MGS_32_TimberWolf_01";
                    };
                };

                class O_URFArmy_ARID_mechanized_zsu_35_tigris_patrol {
                    name = "ZSU 35 Tigris Patrol";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_ZSU_35_Tigris_01";
                    };
                };

            }; // End Mechanized

            class Armored 
            {
                name = "Armor";

                class O_URFArmy_ARID_armored_m1022_beetle_section {
                    name = "M1022 Beetle Section";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_M1022_Beetle_01";
                    };
                    class Unit1 {
                        position[] = {10,-10,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_M1022_Beetle_01";
                    };
                };
                class O_URFArmy_ARID_armored_m808b_scorpion_section {
                    name = "M808B Scorpion Section";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_M808B_Scorpion_MBT_01";
                    };
                    class Unit1 {
                        position[] = {10,-10,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_M808B_Scorpion_MBT_01";
                    };
                };
            }; // End Armored

            class Artillery 
            {
                name = "Artillery";

                class O_URFArmy_ARID_artillery_2s9_sochor_section {
                    name = "2S9 Sochor Section";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_2S9_Sochor_01";
                    };
                    class Unit1 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_2S9_Sochor_01";
                    };
                };
                class O_URFArmy_ARID_artillery_kamaz_mrl_section {
                    name = "Kamaz MRL Section";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Kamaz_MRL_01";
                    };
                    class Unit1 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_Kamaz_MRL_01";
                    };
                };

            }; // End Artillery

            class Air 
            {
                name = "Air";

                class O_URFArmy_ARID_air_hornet_helicopter_patrol {
                    name = "Hornet Helicopter Patrol";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_AV_14_Hornet_01";
                    };
                    class Unit1 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_AV_14_Hornet_01";
                    };
                };

                class O_URFArmy_ARID_air_pelican_gunship_patrol {
                    name = "Pelican Gunship Patrol";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_D77H_TCI_AV_Pelican_Gunship_01"
                    };
                };
                class O_URFArmy_ARID_air_pelican_transport_patrol {
                    name = "Pelican Transport Patrol";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_D77H_TCI_Pelican_01"
                    };
                    class Unit1 {
                        position[] = {0,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_D77H_TCI_Pelican_01"
                    };
                };
                class O_URFArmy_ARID_air_hornet_vtol_wing {
                    name = "Hornet VTOL Wing";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_AV_14_Hornet_VTOL_01";
                    };
                    class Unit1 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_AV_14_Hornet_VTOL_01";
                    };
                };

                class O_URFArmy_ARID_air_shikra_wing {
                    name = "Shikra Wing";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_TO_201_Shikra_01";
                    };
                    class Unit1 {
                        position[] = {0,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_TO_201_Shikra_01";
                    };
                };

                class O_URFArmy_ARID_air_alca_wing {
                    name = "Alca Wing";
                    side = 0;
                    faction = "O_URFArmy_ARID";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_L159_ALCA_01";
                    };
                    class Unit1 {
                        position[] = {0,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OURFArmy_ARID_L159_ALCA_01";
                    };
                };




            };//End Air
        };
    };
};