#define item_xx(a,b) class _xx_##a {name=a; count=b;}

item_xx(ACE_bloodIV,5);
item_xx(ACE_bloodIV_250,5);
item_xx(ACE_bloodIV_500,5);
item_xx(ACE_morphine,10);
item_xx(ACE_epinephrine,10);
item_xx(ACE_adenosine,10);
item_xx(ACE_splint,16);
item_xx(ACE_tourniquet,16);
item_xx(ACE_quikclot,40);
item_xx(ACE_packingBandage,40);
item_xx(ACE_elasticBandage,40);
item_xx(ACE_fieldDressing,40);
item_xx(OPTRE_32Rnd_762x51_Mag,30);
item_xx(OPTRE_100Rnd_95x40_Box,8);
item_xx(OPTRE_MA5C,3);
item_xx(OPTRE_M48_PAW,1);
item_xx(OPTRE_1Rnd_50x137_PEN,2);
item_xx(OPTRE_M9_Frag,5);
item_xx(OPTRE_M2_Smoke,5);
item_xx(OPTRE_M2_Smoke_Red,5);
item_xx(OPTRE_M2_Smoke_Blue,5);
item_xx(OPTRE_M2_Smoke_Purple,5);
item_xx(OPAEX_M41_Launcher,1);
item_xx(OPAEX_M41_Twin_HEAT_Thermal,2);
item_xx(ACE_wirecutter,1);
item_xx(ToolKit,1);
item_xx(ACE_IR_Strobe_Item,8);
