//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class O_URFArmy {
            name = "[105th] United Rebel Front";

            class Infantry {
                name = "Infantry";

                class o_urfarmy_infantry_militia_patrol_1 {
                    name = "Militia Patrol 1";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_02";
                    };
                };

                class o_urfarmy_infantry_militia_patrol_2 {
                    name = "Militia Patrol 2";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_03";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_04";
                    };
                };

                class o_urfarmy_infantry_militia_patrol_3 {
                    name = "Militia Patrol 3";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_05";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_06";
                    };
                };

                class o_urfarmy_infantry_militia_patrol_4 {
                    name = "Militia Patrol 4";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_07";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_08";
                    };
                };

                class o_urfarmy_infantry_militia_fireteam_1 {
                    name = "Militia Fireteam 1";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Marksman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Medic_01";
                    };
                };

                class o_urfarmy_infantry_militia_fireteam_2 {
                    name = "Militia Fireteam 2";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Autorifleman_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Marksman_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Medic_02";
                    };
                };

                class o_urfarmy_infantry_militia_fireteam_3 {
                    name = "Militia Fireteam 3";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_05";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Autorifleman_03";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Marksman_03";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Medic_03";
                    };
                };

                class o_urfarmy_infantry_militia_fireteam_4 {
                    name = "Militia Fireteam 4";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_08";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Autorifleman_04";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Marksman_04";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Medic_02";
                    };
                };

                class o_urfarmy_infantry_militia_command_squad {
                    name = "Militia Command Squad";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Warlord_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AT_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_RTO_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Autorifleman_03";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Medic_03";
                    };
                };

                class o_urfarmy_infantry_militia_squad_1 {
                    name = "Militia Squad 1";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Warlord_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_03";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_04";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_06";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_08";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Autorifleman_02";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Marksman_02";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Medic_02";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_RTO_02";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Shotgunner_02";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AT_02";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_05";
                    };
                };

                class o_urfarmy_infantry_militia_squad_2 {
                    name = "Militia Squad 2";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Warlord_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_03";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_07";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_05";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Autorifleman_04";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Marksman_03";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Medic_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_RTO_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Shotgunner_03";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AT_02";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AT_01";
                    };
                };

                class o_urfarmy_infantry_militia_squad_3 {
                    name = "Militia Squad 3";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Warlord_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_05";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_07";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_03";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Autorifleman_05";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Marksman_04";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Medic_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Shotgunner_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_RTO_02";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AT_02";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_02";
                    };
                };

                class o_urfarmy_infantry_militia_squad_4 {
                    name = "Militia Squad 4";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Warlord_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_06";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_08";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_03";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_04";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_05";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Autorifleman_02";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Marksman_02";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Medic_02";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_RTO_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Shotgunner_03";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AT_02";
                    };
                    class Unit12 {
                        position[] = {-30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_01";
                    };
                };

                class o_urfarmy_infantry_militia_weapons_squad {
                    name = "Militia Weapons Squad";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Warlord_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AT_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AA_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AT_01";
                    };
                };

                class o_urfarmy_infantry_militia_hunter_killer_rpg_team {
                    name = "Militia Hunter Killer RPG Team";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AT_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AT_01";
                    };
                };

                class o_urfarmy_infantry_militia_aa_team {
                    name = "Militia AA Team";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AA_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AA_02";
                    };
                };

                class o_urfarmy_infantry_militia_sniper_team {
                    name = "Militia Sniper Team";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Marksman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Marksman_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Marksman_03";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Marksman_04";
                    };
                };

                class o_urfarmy_infantry_militia_assault_squad_1 {
                    name = "Militia Assault Squad 1";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_03";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_04";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_05";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_06";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_07";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AT_01";
                    };
                };

                class o_urfarmy_infantry_militia_assault_squad_2 {
                    name = "Militia Assault Squad 2";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_08";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_07";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_06";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_AT_02";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_04";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_03";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_02";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Militia_Rifleman_01";
                    };
                };

                class o_urfarmy_infantry_regular_patrol {
                    name = "Regular Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                };

                class o_urfarmy_infantry_regular_at_fireteam {
                    name = "Regular AT Fireteam";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_AT_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_RTO_01";
                    };
                };

                class o_urfarmy_infantry_regular_aa_fireteam {
                    name = "Regular AA Fireteam";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_AA_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Autorifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_RTO_01";
                    };
                };

                class o_urfarmy_infantry_regular_squad_1 {
                    name = "Regular Squad 1";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Marksman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Autorifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Medic_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_RTO_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_AT_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_AT_01";
                    };
                };

                class o_urfarmy_infantry_regular_squad_2 {
                    name = "Regular Squad 2";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Grenadier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Medic_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Marksman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_RTO_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_AT_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_AT_01";
                    };
                };

                class o_urfarmy_infantry_regular_command_squad {
                    name = "Regular Command Squad";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Officer_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Grenadier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Marksman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_RTO_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class o_urfarmy_specops_regular_sniper_team {
                    name = "Regular Sniper Team";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Sniper_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Sniper_01";
                    };
                };

                class o_urfarmy_specops_battlejumper_fireteam {
                    name = "Battlejumper Fireteam";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Battlejumper_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_URFArmy_Battlejumper_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Battlejumper_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Battlejumper_02";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

                class o_urfarmy_motorized_motorized_infantry_fireteam {
                    name = "Motorized Infantry Fireteam";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Warthog_APC_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                };

                class o_urfarmy_motorized_motorized_infantry_recon_team {
                    name = "Motorized Infantry Recon Team";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Meerkat_Minigun_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                };

                class o_urfarmy_motorized_motorized_infantry_at_recon_team {
                    name = "Motorized infantry AT Recon Team";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Meerkat_AT_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                };

                class o_urfarmy_motorized_motorized_infantry_squad {
                    name = "Motorized Infantry Squad";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Mule_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Autorifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Marksman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Medic_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_RTO_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_AT_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_AA_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Grenadier_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit12 {
                        position[] = {-30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                };

                class o_urfarmy_motorized_offroad_hmg_patrol {
                    name = "Offroad HMG Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Offroad_HMG_01";
                    };
                };

                class o_urfarmy_motorized_offroad_at_patrol {
                    name = "Offroad AT Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Offroad_AT_01";
                    };
                };

                class o_urfarmy_motorized_warthog_laag_patrol {
                    name = "Warthog LAAG Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Warthog_LAAG_01";
                    };
                };

                class o_urfarmy_motorized_warthog_atgm_patrol {
                    name = "Warthog ATGM Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Warthog_ATGM_01";
                    };
                };

                class o_urfarmy_motorized_warthog_aa_patrol {
                    name = "Warthog AA Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Warthog_AA_01";
                    };
                };

                class o_urfarmy_motorized_karatel_hmg_patrol {
                    name = "Karatel HMG Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Karatel_HMG_01";
                    };
                };

                class o_urfarmy_motorized_karatel_gmg_patrol {
                    name = "Karatel GMG Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Karatel_GMG_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

                class o_urfarmy_motorized_mtp_motorized_infantry_squad {
                    name = "Motorized Infantry Squad";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Mule_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Autorifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Marksman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Medic_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_RTO_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_AT_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_AA_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Grenadier_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit12 {
                        position[] = {-30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                };

            };

            class Support {
                name = "Support Infantry";

                class o_urfarmy_support_assault_infantry {
                    name = "Assault Infantry";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                };

                class o_urfarmy_support_weapons_fireteam {
                    name = "Weapons Fireteam";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Grenadier_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_AT_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_AA_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_RTO_01";
                    };
                };

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class o_urfarmy_mechanized_mechanized_infantry_squad {
                    name = "Mechanized Infantry Squad";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Otokor_Arma_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Grenadier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Grenadier_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Autorifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_URFArmy_Regular_Medic_01";
                    };
                };

                class o_urfarmy_mechanized_bm2_stalker_patrol {
                    name = "BM2 Stalker Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_BM2_Stalker_01";
                    };
                };

                class o_urfarmy_mechanized_zsu_35_tigris_patrol {
                    name = "ZSU 35 Tigris Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_ZSU_35_Tigris_01";
                    };
                };

            };

            class Armored {
                name = "Armor";

                class o_urfarmy_armored_m350_recluse_team {
                    name = "M350 Recluse Team";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_M350_Recluse_01";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

                class o_urfarmy_artillery_2s9_sochor_team {
                    name = "2S9 Sochor Team";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_2S9_Sochor_01";
                    };
                };

            };

            class Naval {
                name = "Naval";

                class o_urfarmy_naval_speedboat_hmg_team {
                    name = "Speedboat HMG Team";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_naval.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Speedboat_HMG_01";
                    };
                };

            };

            class Air {
                name = "Air";

                class o_urfarmy_air_mi48_kajman_air_assault_team {
                    name = "MI48 Kajman Air Assault Team";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_MI48_Kajman_01";
                    };
                };

                class o_urfarmy_air_hornet_helicopter_patrol {
                    name = "Hornet Helicopter Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Hornet_Helicopter_Variant_01";
                    };
                };

                class o_urfarmy_air_uh_101_eagle_patrol {
                    name = "UH 101 Eagle Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_UH_101_Eagle_01";
                    };
                };

                class o_urfarmy_air_pelican_gunship_patrol {
                    name = "Pelican Gunship Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Pelican_Gunship_01";
                    };
                };

                class o_urfarmy_air_UH144_patrol {
                    name = "UH144 Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_VES_UH144_A_01";
                    };
                };

                class o_urfarmy_air_hornet_vtol_patrol {
                    name = "Hornet VTOL Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Hornet_VTOL_Variant_01";
                    };
                };

                class o_urfarmy_air_xi_an_patrol {
                    name = "Xi'an Patrol";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Xi_an_Gunship_01";
                    };
                };

                class o_urfarmy_air_yak_130_wing {
                    name = "Yak 130 Wing";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_Yak_130_01";
                    };
                };

                class o_urfarmy_air_shikra_wing {
                    name = "Shikra Wing";
                    side = 0;
                    faction = "O_URFArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_URFArmy_To_201_Shikra_01";
                    };
                };
            };
        };
    };
};