class CfgPatches {
    class O_URFArmy {
        units[] = {
            "O_URFArmy_Militia_Rifleman_01",
            "O_URFArmy_Militia_Rifleman_02",
            "O_URFArmy_Militia_Rifleman_03",
            "O_URFArmy_Militia_Rifleman_04",
            "O_URFArmy_Militia_Rifleman_05",
            "O_URFArmy_Militia_Rifleman_06",
            "O_URFArmy_Militia_Rifleman_07",
            "O_URFArmy_Militia_Rifleman_08",
            "O_URFArmy_Local_Police_01",
            "O_URFArmy_Militia_Autorifleman_01",
            "O_URFArmy_Militia_Autorifleman_02",
            "O_URFArmy_Militia_Autorifleman_03",
            "O_URFArmy_Militia_Autorifleman_04",
            "O_URFArmy_Militia_Autorifleman_05",
            "O_URFArmy_Militia_Marksman_01",
            "O_URFArmy_Militia_Marksman_02",
            "O_URFArmy_Militia_Marksman_03",
            "O_URFArmy_Militia_Marksman_04",
            "O_URFArmy_Militia_Medic_01",
            "O_URFArmy_Militia_Medic_02",
            "O_URFArmy_Militia_Medic_03",
            "O_URFArmy_Militia_RTO_01",
            "O_URFArmy_Militia_RTO_02",
            "O_URFArmy_Militia_Shotgunner_01",
            "O_URFArmy_Militia_Shotgunner_02",
            "O_URFArmy_Militia_Shotgunner_03",
            "O_URFArmy_Militia_AT_01",
            "O_URFArmy_Militia_AT_02",
            "O_URFArmy_Militia_AT_03",
            "O_URFArmy_Militia_AT_04",
            "O_URFArmy_Militia_AT_05",
            "O_URFArmy_Militia_AA_01",
            "O_URFArmy_Militia_AA_02",
            "O_URFArmy_Militia_Warlord_01",
            "O_URFArmy_Regular_Rifleman_01",
            "O_URFArmy_Regular_Autorifleman_01",
            "O_URFArmy_Regular_Marksman_01",
            "O_URFArmy_Regular_Medic_01",
            "O_URFArmy_Regular_RTO_01",
            "O_URFArmy_Regular_AT_01",
            "O_URFArmy_Regular_AA_01",
            "O_URFArmy_Regular_Grenadier_01",
            "O_URFArmy_Regular_Officer_01",
            "O_URFArmy_Battlejumper_01",
            "O_URFArmy_Crewman_01",
            "O_URFArmy_Pilot_01",
            "O_URFArmy_Warthog_APC_01",
            "O_URFArmy_Warthog_LAAG_01",
            "O_URFArmy_Warthog_ATGM_01",
            "O_URFArmy_Warthog_AA_01",
            "O_URFArmy_Mule_01",
            "O_URFArmy_Meerkat_Minigun_01",
            "O_URFArmy_Meerkat_AT_01",
            "O_URFArmy_Offroad_AT_01",
            "O_URFArmy_Offroad_HMG_01",
            "O_URFArmy_Otokor_Arma_01",
            "O_URFArmy_BM2_Stalker_01",
            "O_URFArmy_ZSU_35_Tigris_01",
            "O_URFArmy_2S9_Sochor_01",
            "O_URFArmy_Karatel_HMG_01",
            "O_URFArmy_Karatel_GMG_01",
            "O_URFArmy_Speedboat_HMG_01",
            "O_URFArmy_MAKO_Drone_01",
            "O_URFArmy_MI48_Kajman_01",
            "O_URFArmy_KA60_Kasatka_01",
            "O_URFArmy_KA60_Kasatka_Transport_01",
            "O_URFArmy_MI29_Taru_01",
            "O_URFArmy_Pelican_Transport_01",
            "O_URFArmy_Pelican_Gunship_01",
            "O_URFArmy_UH_101_Eagle_01",
            "O_URFArmy_Xi_an_Gunship_01",
            "O_URFArmy_Yak_130_01",
            "O_URFArmy_To_201_Shikra_01",
            "O_URFArmy_To_201_Shikra_Stealth_01",
            "O_URFArmy_M350_Recluse_01",
            "O_URFArmy_Hornet_Helicopter_Variant_01",
            "O_URFArmy_Hornet_VTOL_Variant_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
              "A3_Characters_F",
            "OPTRE_UNSC_Units",
           // "lambs_danger",
            "OPTRE_UNSC_Units_Army",
            "OPTRE_Ins_Units_BJ",
            "OPTRE_Ins_Units_URF",
            "OPTRE_MJOLNIR",
            "OPTRE_UNSC_Units_ONI",
           // "functions_f_gearf",
            "A3_Sounds_F",
          //  "3rdView",
            "A3_Sounds_F_Exp",
         //   "jsrs_soundmod_complete_edition",
          //  "MRHSatellite",
          //  "ace_gforces",
          //  "ace_movement",
          //  "ace_medical_feedback",
          //  "CAData",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
          //  "CUP_Worlds_DustEffects",
          //  "ace_thermals",
          //  "tfar_core",
          //  "ace_refuel",
          //  "CUP_Core",
          //  "cba_xeh",
            "A3_Soft_F_Beta_Truck_01",
            "A3_Soft_F_Exp_Truck_01",
          //  "ace_realisticnames",
          // "ace_cargo",
            "A3_Soft_F_Gamma_Truck_01",
          //  "ace_vehicles",
            "A3_Soft_F",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_EPC_Truck_03",
          //  "rds_A2_Civilians",
            "A3_Soft_F_Orange_Van_02",
          //  "ace_repair",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F_ParticleEffects",
          //  "babe_int_EHs",
          //  "MRHMilsimTools",
            "A3_Armor_F_Beta",
            "LM_OPCAN_UNSC_VEH",
            "OPTRE_Vehicles_Warthog",
            "OPTRE_ACE_Compat",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
            "A3_Sounds_F_Tank",
          //  "TFAR_IntercomDummy",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
          //  "ace_cookoff",
            "OPAEX_Pelican",
            "OPTRE_Vehicles_Pelican",
            "A3_Air_F",
            "A3_Air_F_Heli_Light_01",
            "A3_Air_F_Heli_Light_02",
            "A3_Air_F_Beta_Heli_Transport_01",
            "OPTRE_Vehicles_Falcon",
            "OPTRE_Vehicles_Hornet",
            "OPAEX_Falcon",
            "OPAEX_Sparrowhawk",
          //  "ace_logistics_uavbattery",
           // "ace_interaction",
            "OPAEX_Hornet",
            "OPTRE_Vehicles_Scorpion",
            "OPTRE_Vehicles_Grizzly",
            "OPAEX_Scorpion",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "OPTRE_Vehicles_Elephant",
            "A3_Boat_F_Boat_Armed_01",
            "A3_Boat_F",
            "A3_Air_F_EPC_Plane_CAS_01",
          //  "ace_aircraft",
            "A3_Air_F_Beta",
            "A3_Air_F_Gamma_Plane_Fighter_03",
            "A3_Air_F_EPC_Plane_CAS_02",
            "A3_Air_F_Exp_Plane_Civil_01",
            "A3_Air_F_Jets_Plane_Fighter_01",
            "A3_Air_F_Jets_Plane_Fighter_02",
            "A3_Air_F_Jets_Plane_Fighter_04",
            "A3_Air_F_Jets_UAV_05",
            "OPTRE_Vehicles_Pod",
          //  "MatGrp_Unmanned",
            "OPTRE_FC_Vehicles_Banshee",
            "A3_Air_F_Exp_VTOL_01",
            "A3_Air_F_Exp",
           // "ace_fastroping",
            "A3_Air_F_Heli_Heli_Transport_03"
        };
        author = "CPO. W. Cunningham";
        authors[] = {"CPO. W. Cunningham"};
    };
};
