//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_UNSCArmy {
        displayName = "[105th] UNSC Army";
        side = 1;
        flag = "ca\Ca_E\data\flag_blufor_co.paa";
        icon = "ca\Ca_E\data\flag_blufor_co.paa";
        priority = 0;
    };
};