//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class WEST {

        class B_UNSCArmy {
            name = "[105th] UNSC Army";

            class Infantry {
                name = "Infantry";

                class b_unscarmy_infantry_patrol {
                    name = "Patrol";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                };

                class b_unscarmy_infantry_fireteam {
                    name = "Fireteam";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_AT_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Corpsman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Autorifleman_01";
                    };
                };

                class b_unscarmy_infantry_squad {
                    name = "Squad";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Marksman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Corpsman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_AT_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_AA_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit12 {
                        position[] = {-30,-30,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                };

                class b_unscarmy_infantry_at_team {
                    name = "AT Team";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_AT_01";
                    };
                };

                class b_unscarmy_infantry_aa_team {
                    name = "AA Team";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_AA_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class b_unscarmy_specops_sniper_team {
                    name = "Sniper Team";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_Marksman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Marksman_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

                class b_unscarmy_motorized_motorized_infantry_squad {
                    name = "Motorized Infantry Squad";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_HEMTT_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Autorifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Marksman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Corpsman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_AT_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_AA_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit12 {
                        position[] = {-30,-30,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                };

                class b_unscarmy_motorized_warthog_laag_patrol {
                    name = "Warthog LAAG Patrol";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_Warthog_LAAG_01";
                    };
                };

                class b_unscarmy_motorized_warthog_at_patrol {
                    name = "Warthog AT Patrol";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_Warthog_AT_01";
                    };
                };

                class b_unscarmy_motorized_warthog_aa_patrol {
                    name = "Warthog AA Patrol";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_Warthog_AA_01";
                    };
                };

                class b_unscarmy_motorized_warthog_gauss_patrol {
                    name = "Warthog Gauss Patrol";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_Warthog_Gauss_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

                class b_unscarmy_support_assault_infantry {
                    name = "Assault Infantry";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                };

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class b_unscarmy_mechanized_mechanized_infantry_squad {
                    name = "Mechanized Infantry Squad";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_AFV102_Hound_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Autorifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_AT_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Rifleman_AA_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNSCArmy_Corpsman_01";
                    };
                };

            };

            class Armored {
                name = "Armor";

                class b_unscarmy_armored_timberwolf_patrol {
                    name = "Timberwolf Patrol";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_MGS32_Timberwolf_01";
                    };
                };

                class b_unscarmy_armored_scorpion_patrol {
                    name = "Scorpion Patrol";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_M808_Scorpion_01";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

                class b_unscarmy_artillery_seara {
                    name = "Seara";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_Seara_01";
                    };
                };

            };

            class Naval {
                name = "Naval";

                class b_unscarmy_naval_speedboat_hmg {
                    name = "Speedboat HMG";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_naval.paa";
                    rarityGroup = 0.5;

                };

            };

            class Air {
                name = "Air";

                class b_unscarmy_air_hornet {
                    name = "Hornet";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_AV14_Hornet_01";
                    };
                };

                class b_unscarmy_air_pelican_armed {
                    name = "Pelican Armed";
                    side = 1;
                    faction = "B_UNSCArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNSCArmy_Pelican_Gunship_01";
                    };
                };

            };


        };

    };
};