class CfgPatches {
    class B_UNSCArmy {
        units[] = {
            "B_UNSCArmy_Rifleman_01",
            "B_UNSCArmy_Autorifleman_01",
            "B_UNSCArmy_Marksman_01",
            "B_UNSCArmy_Corpsman_01",
            "B_UNSCArmy_Rifleman_AT_01",
            "B_UNSCArmy_Rifleman_AA_01",
            "B_UNSCArmy_Crewman_01",
            "B_UNSCArmy_Pilot_01",
            "B_UNSCArmy_HEMTT_01",
            "B_UNSCArmy_Warthog_LAAG_01",
            "B_UNSCArmy_Warthog_AT_01",
            "B_UNSCArmy_Warthog_AA_01",
            "B_UNSCArmy_Warthog_Gauss_01",
            "B_UNSCArmy_MGS32_Timberwolf_01",
            "B_UNSCArmy_AFV102_Hound_01",
            "B_UNSCArmy_Pelican_Transport_01",
            "B_UNSCArmy_Pelican_Gunship_01",
            "B_UNSCArmy_AV14_Hornet_01",
            "B_UNSCArmy_M808_Scorpion_01",
            "B_UNSCArmy_Bardelas_01",
            "B_UNSCArmy_Seara_01",
            "B_UNSCArmy_Speedboat_HMG_01",
            "B_UNSCArmy_Thunderbolt_01",
            "B_UNSCArmy_V44_Blackfish_01",
            "B_UNSCArmy_Black_Wasp_01",
            "B_UNSCArmy_UH80_Ghost_Hawk_01",
            "B_UNSCArmy_CH47_Chinook_01",
            "B_UNSCArmy_CH47_Chinook_Transport_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
           "A3_Characters_F",
          //  "OPTRE_UNSC_Units",
           // "lambs_danger",
            "OPTRE_UNSC_Units_Army",
           "OPTRE_Ins_Units_BJ",
            "OPTRE_Ins_Units_URF",
           // "OPTRE_MJOLNIR",
           // "OPTRE_UNSC_Units_ONI",
           // "functions_f_gearf",
            "A3_Sounds_F",
          //  "3rdView",
            "A3_Sounds_F_Exp",
         //   "jsrs_soundmod_complete_edition",
          //  "MRHSatellite",
          //  "ace_gforces",
          //  "ace_movement",
          //  "ace_medical_feedback",
          //  "CAData",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
          //  "CUP_Worlds_DustEffects",
          //  "ace_thermals",
          //  "tfar_core",
          //  "ace_refuel",
          //  "CUP_Core",
          //  "cba_xeh",
            "A3_Soft_F_Beta_Truck_01",
            "A3_Soft_F_Exp_Truck_01",
          //  "ace_realisticnames",
          // "ace_cargo",
            "A3_Soft_F_Gamma_Truck_01",
          //  "ace_vehicles",
            "A3_Soft_F",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_EPC_Truck_03",
          //  "rds_A2_Civilians",
            "A3_Soft_F_Orange_Van_02",
          //  "ace_repair",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F_ParticleEffects",
          //  "babe_int_EHs",
          //  "MRHMilsimTools",
            "A3_Armor_F_Beta",
            "LM_OPCAN_UNSC_VEH",
            "OPTRE_Vehicles_Warthog",
           // "OPTRE_ACE_Compat",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
            "A3_Sounds_F_Tank",
          //  "TFAR_IntercomDummy",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
          //  "ace_cookoff",
            "OPAEX_Pelican",
            "OPTRE_Vehicles_Pelican",
            "A3_Air_F",
            "A3_Air_F_Heli_Light_01",
            "A3_Air_F_Heli_Light_02",
            "A3_Air_F_Beta_Heli_Transport_01",
            "OPTRE_Vehicles_Falcon",
            "OPTRE_Vehicles_Hornet",
            "OPAEX_Falcon",
           "OPAEX_Sparrowhawk",
          //  "ace_logistics_uavbattery",
           // "ace_interaction",
            "OPAEX_Hornet",
            "OPTRE_Vehicles_Scorpion",
            "OPTRE_Vehicles_Grizzly",
            "OPAEX_Scorpion",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "OPTRE_Vehicles_Elephant",
            "A3_Boat_F_Boat_Armed_01",
            "A3_Boat_F",
            "A3_Air_F_EPC_Plane_CAS_01",
          //  "ace_aircraft",
            "A3_Air_F_Beta",
            "A3_Air_F_Gamma_Plane_Fighter_03",
            "A3_Air_F_EPC_Plane_CAS_02",
            "A3_Air_F_Exp_Plane_Civil_01",
            "A3_Air_F_Jets_Plane_Fighter_01",
            "A3_Air_F_Jets_Plane_Fighter_02",
            "A3_Air_F_Jets_Plane_Fighter_04",
            "A3_Air_F_Jets_UAV_05",
           // "OPTRE_Vehicles_Pod",
          //  "MatGrp_Unmanned",
          //  "OPTRE_FC_Vehicles_Banshee",
            "A3_Air_F_Exp_VTOL_01",
            "A3_Air_F_Exp",
           // "ace_fastroping",
            "A3_Air_F_Heli_Heli_Transport_03"
        };
        author = "CPO. W. Cunningham";
        authors[] = {"CPO. W. Cunningham"};
    };
};
