//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class B_Soldier_F;
    class B_Soldier_F_OCimport_01 : B_Soldier_F { scope = 0; class EventHandlers; };
    class B_Soldier_F_OCimport_02 : B_Soldier_F_OCimport_01 { class EventHandlers; };

    class B_Truck_01_covered_F;
    class B_Truck_01_covered_F_OCimport_01 : B_Truck_01_covered_F { scope = 0; class EventHandlers; class Turrets; };
    class B_Truck_01_covered_F_OCimport_02 : B_Truck_01_covered_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class LM_OPCAN_HOG_MG_AR_WDL;
    class LM_OPCAN_HOG_MG_AR_WDL_OCimport_01 : LM_OPCAN_HOG_MG_AR_WDL { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_HOG_MG_AR_WDL_OCimport_02 : LM_OPCAN_HOG_MG_AR_WDL_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class LM_OPCAN_HOG_AT_AR_WDL;
    class LM_OPCAN_HOG_AT_AR_WDL_OCimport_01 : LM_OPCAN_HOG_AT_AR_WDL { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_HOG_AT_AR_WDL_OCimport_02 : LM_OPCAN_HOG_AT_AR_WDL_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class LM_OPCAN_HOG_AA_AR_WDL;
    class LM_OPCAN_HOG_AA_AR_WDL_OCimport_01 : LM_OPCAN_HOG_AA_AR_WDL { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_HOG_AA_AR_WDL_OCimport_02 : LM_OPCAN_HOG_AA_AR_WDL_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class LM_OPCAN_HOG_G_AR_WDL;
    class LM_OPCAN_HOG_G_AR_WDL_OCimport_01 : LM_OPCAN_HOG_G_AR_WDL { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_HOG_G_AR_WDL_OCimport_02 : LM_OPCAN_HOG_G_AR_WDL_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class LM_OPCAN_MGS_AR_WDL;
    class LM_OPCAN_MGS_AR_WDL_OCimport_01 : LM_OPCAN_MGS_AR_WDL { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_MGS_AR_WDL_OCimport_02 : LM_OPCAN_MGS_AR_WDL_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class LM_OPCAN_AFV102_AR_WDL;
    class LM_OPCAN_AFV102_AR_WDL_OCimport_01 : LM_OPCAN_AFV102_AR_WDL { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_AFV102_AR_WDL_OCimport_02 : LM_OPCAN_AFV102_AR_WDL_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class LM_OPCAN_D77_U_AR_WDL;
    class LM_OPCAN_D77_U_AR_WDL_OCimport_01 : LM_OPCAN_D77_U_AR_WDL { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_D77_U_AR_WDL_OCimport_02 : LM_OPCAN_D77_U_AR_WDL_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class LM_OPCAN_D77_A_AR_WDL;
    class LM_OPCAN_D77_A_AR_WDL_OCimport_01 : LM_OPCAN_D77_A_AR_WDL { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_D77_A_AR_WDL_OCimport_02 : LM_OPCAN_D77_A_AR_WDL_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class LM_OPCAN_AV14_AR;
    class LM_OPCAN_AV14_AR_OCimport_01 : LM_OPCAN_AV14_AR { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_AV14_AR_OCimport_02 : LM_OPCAN_AV14_AR_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class LM_OPCAN_M808_AR_WDL;
    class LM_OPCAN_M808_AR_WDL_OCimport_01 : LM_OPCAN_M808_AR_WDL { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_M808_AR_WDL_OCimport_02 : LM_OPCAN_M808_AR_WDL_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret1;
            class CargoTurret2;
            class CargoTurret3;
            class CargoTurret4;
            class CargoTurret5;
            class CargoTurret6;
            class CargoTurret7;
            class CargoTurret8;
        };
    };

    class B_APC_Tracked_01_AA_F;
    class B_APC_Tracked_01_AA_F_OCimport_01 : B_APC_Tracked_01_AA_F { scope = 0; class EventHandlers; class Turrets; };
    class B_APC_Tracked_01_AA_F_OCimport_02 : B_APC_Tracked_01_AA_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class B_MBT_01_mlrs_F;
    class B_MBT_01_mlrs_F_OCimport_01 : B_MBT_01_mlrs_F { scope = 0; class EventHandlers; class Turrets; };
    class B_MBT_01_mlrs_F_OCimport_02 : B_MBT_01_mlrs_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class B_Boat_Armed_01_minigun_F;
    class B_Boat_Armed_01_minigun_F_OCimport_01 : B_Boat_Armed_01_minigun_F { scope = 0; class EventHandlers; class Turrets; };
    class B_Boat_Armed_01_minigun_F_OCimport_02 : B_Boat_Armed_01_minigun_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class FrontTurret;
            class RearTurret;
        };
    };

    class B_Plane_CAS_01_dynamicLoadout_F;
    class B_Plane_CAS_01_dynamicLoadout_F_OCimport_01 : B_Plane_CAS_01_dynamicLoadout_F { scope = 0; class EventHandlers; };
    class B_Plane_CAS_01_dynamicLoadout_F_OCimport_02 : B_Plane_CAS_01_dynamicLoadout_F_OCimport_01 { scope = 0; class EventHandlers; };

    class B_T_VTOL_01_armed_F;
    class B_T_VTOL_01_armed_F_OCimport_01 : B_T_VTOL_01_armed_F { scope = 0; class EventHandlers; class Turrets; };
    class B_T_VTOL_01_armed_F_OCimport_02 : B_T_VTOL_01_armed_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class GunnerTurret_01;
            class GunnerTurret_02;
        };
    };

    class B_Plane_Fighter_01_F;
    class B_Plane_Fighter_01_F_OCimport_01 : B_Plane_Fighter_01_F { scope = 0; class EventHandlers; };
    class B_Plane_Fighter_01_F_OCimport_02 : B_Plane_Fighter_01_F_OCimport_01 { scope = 0; class EventHandlers; };

    class B_Heli_Transport_01_F;
    class B_Heli_Transport_01_F_OCimport_01 : B_Heli_Transport_01_F { scope = 0; class EventHandlers; class Turrets; };
    class B_Heli_Transport_01_F_OCimport_02 : B_Heli_Transport_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class MainTurret;
            class RightDoorGun;
        };
    };

    class B_Heli_Transport_03_F;
    class B_Heli_Transport_03_F_OCimport_01 : B_Heli_Transport_03_F { scope = 0; class EventHandlers; class Turrets; };
    class B_Heli_Transport_03_F_OCimport_02 : B_Heli_Transport_03_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class MainTurret;
            class RightDoorGun;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class B_Heli_Transport_03_unarmed_F;
    class B_Heli_Transport_03_unarmed_F_OCimport_01 : B_Heli_Transport_03_unarmed_F { scope = 0; class EventHandlers; class Turrets; };
    class B_Heli_Transport_03_unarmed_F_OCimport_02 : B_Heli_Transport_03_unarmed_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class MainTurret;
            class RightDoorGun;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };


    class B_UNSCArmy_Rifleman_01 : B_Soldier_F_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 1;
        faction = "B_UNSCArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "VES_BDU_MulticamBlack_Slim";

        linkedItems[] = {"Echo_M52A_Armor_Infantry_B","Echo_CH252_Helmet_Infantry","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};
        respawnlinkedItems[] = {"Echo_M52A_Armor_Infantry_B","Echo_CH252_Helmet_Infantry","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};

        weapons[] = {"OPTRE_MA37"};
        respawnWeapons[] = {"OPTRE_MA37"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{},{"VES_BDU_MulticamBlack_Slim",{{"FirstAidKit",1},{"MRH_Map",1},{"ACE_fieldDressing",2},{"ACE_elasticBandage",2},{"ACE_packingBandage",2},{"OPTRE_Biofoam",1},{"ACE_CableTie",1},{"ACE_morphine",1}}},{"Echo_M52A_Armor_Infantry_B",{{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1},{"HandGrenade",2,1},{"OPTRE_32Rnd_762x51_Mag",12,32}}},{},"Echo_CH252_Helmet_Infantry","LM_OPCAN_DES_Shemagheye",{},{"","","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Autorifleman_01 : B_UNSCArmy_Rifleman_01 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman";
        side = 1;
        faction = "B_UNSCArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "VES_BDU_MulticamBlack_Slim";

        linkedItems[] = {"Echo_M52A_Armor_Infantry_B","Echo_CH252_Helmet_Infantry","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};
        respawnlinkedItems[] = {"Echo_M52A_Armor_Infantry_B","Echo_CH252_Helmet_Infantry","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};

        weapons[] = {"OPTRE_M73"};
        respawnWeapons[] = {"OPTRE_M73"};

        magazines[] = {"OPTRE_36Rnd_95x40_Mag","OPTRE_36Rnd_95x40_Mag"};
        respawnMagazines[] = {"OPTRE_36Rnd_95x40_Mag","OPTRE_36Rnd_95x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M73","","","REC_HOLO",{"OPTRE_36Rnd_95x40_Mag",36},{},""},{},{},{"VES_BDU_MulticamBlack_Slim",{{"FirstAidKit",1},{"MRH_Map",1},{"ACE_fieldDressing",2},{"ACE_elasticBandage",2},{"ACE_packingBandage",2},{"OPTRE_Biofoam",1},{"ACE_CableTie",1},{"ACE_morphine",1},{"ACE_EarPlugs",1},{"OPTRE_36Rnd_95x40_Mag",3,36}}},{"Echo_M52A_Armor_Infantry_B",{{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1},{"HandGrenade",2,1},{"OPTRE_60Rnd_762x51_Mag_Tracer",12,60}}},{"OPTRE_UNSC_Rucksack",{{"OPTRE_100Rnd_95x40_Box",5,100},{"OPTRE_M2_Smoke",3,1}}},"Echo_CH252_Helmet_Infantry","LM_OPCAN_DES_Shemagheye",{},{"","","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Marksman_01 : B_UNSCArmy_Rifleman_01 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 1;
        faction = "B_UNSCArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "VES_BDU_MulticamBlack_Slim";

        linkedItems[] = {"Echo_M52A_Armor_Infantry_B","Echo_CH252_Helmet_Infantry","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};
        respawnlinkedItems[] = {"Echo_M52A_Armor_Infantry_B","Echo_CH252_Helmet_Infantry","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};

        weapons[] = {"OPTRE_SRS99C"};
        respawnWeapons[] = {"OPTRE_SRS99C"};

        magazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_4Rnd_145x114_APFSDS_Mag"};
        respawnMagazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_4Rnd_145x114_APFSDS_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_SRS99C","","","OPTRE_SRS99C_Scope",{"OPTRE_4Rnd_145x114_APFSDS_Mag",4},{},""},{},{},{"VES_BDU_MulticamBlack_Slim",{{"FirstAidKit",1},{"MRH_Map",1},{"ACE_fieldDressing",2},{"ACE_elasticBandage",2},{"ACE_packingBandage",2},{"OPTRE_Biofoam",1},{"ACE_CableTie",1},{"ACE_morphine",1},{"ACE_EarPlugs",1},{"OPTRE_4Rnd_145x114_APFSDS_Mag",3,4}}},{"Echo_M52A_Armor_Infantry_B",{{"SmokeShellGreen",1,1},{"Chemlight_green",2,1},{"HandGrenade",2,1},{"OPTRE_60Rnd_762x51_Mag_Tracer",12,60}}},{"OPTRE_UNSC_Rucksack",{{"OPTRE_4Rnd_145x114_APFSDS_Mag",12,4}}},"Echo_CH252_Helmet_Infantry","LM_OPCAN_DES_Shemagheye",{},{"","","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Corpsman_01 : B_UNSCArmy_Rifleman_01 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Corpsman";
        side = 1;
        faction = "B_UNSCArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "VES_BDU_MulticamBlack_Slim";

        linkedItems[] = {"Echo_M52A_Armor_Medic_B","Echo_CH252_Helmet_Medic","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};
        respawnlinkedItems[] = {"Echo_M52A_Armor_Medic_B","Echo_CH252_Helmet_Medic","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};

        weapons[] = {"OPTRE_MA37"};
        respawnWeapons[] = {"OPTRE_MA37"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{},{"VES_BDU_MulticamBlack_Slim",{{"FirstAidKit",1},{"MRH_Map",1},{"ACE_fieldDressing",2},{"ACE_elasticBandage",2},{"ACE_packingBandage",2},{"OPTRE_Biofoam",1},{"ACE_CableTie",1},{"ACE_morphine",1},{"ACE_EarPlugs",1}}},{"Echo_M52A_Armor_Medic_B",{{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1},{"HandGrenade",2,1},{"OPTRE_32Rnd_762x51_Mag",12,32}}},{"OPTRE_UNSC_Rucksack",{{"ACE_fieldDressing",25},{"ACE_elasticBandage",25},{"ACE_packingBandage",25},{"OPTRE_Biofoam",10},{"ACE_bloodIV_500",4},{"ACE_bloodIV_250",2},{"ACE_CableTie",10},{"ACE_epinephrine",8},{"ACE_morphine",8},{"ACE_personalAidKit",2},{"ACE_splint",8},{"ACE_tourniquet",8},{"ACE_surgicalKit",1}}},"Echo_CH252_Helmet_Medic","LM_OPCAN_DES_Shemagheye",{},{"","","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Rifleman_AT_01 : B_UNSCArmy_Rifleman_01 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman AT";
        side = 1;
        faction = "B_UNSCArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "VES_BDU_MulticamBlack_Slim";

        linkedItems[] = {"Echo_M52A_Armor_Infantry_B","Echo_CH252_Helmet_Infantry","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};
        respawnlinkedItems[] = {"Echo_M52A_Armor_Infantry_B","Echo_CH252_Helmet_Infantry","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};

        weapons[] = {"OPTRE_MA37","OPTRE_M48_PAW"};
        respawnWeapons[] = {"OPTRE_MA37","OPTRE_M48_PAW"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_1Rnd_50x137_HEAT","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_1Rnd_50x137_HEAT","OPTRE_32Rnd_762x51_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",60},{},""},{"OPTRE_M48_PAW","","","",{"OPTRE_1Rnd_50x137_HEAT",1},{},""},{},{"VES_BDU_MulticamBlack_Slim",{{"FirstAidKit",1},{"MRH_Map",1},{"ACE_fieldDressing",2},{"ACE_elasticBandage",2},{"ACE_packingBandage",2},{"OPTRE_Biofoam",1},{"ACE_CableTie",1},{"ACE_morphine",1},{"ACE_EarPlugs",1}}},{"Echo_M52A_Armor_Infantry_B",{{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1},{"HandGrenade",2,1},{"OPTRE_32Rnd_762x51_Mag",12,32}}},{"OPTRE_UNSC_Rucksack",{{"OPTRE_1Rnd_50x137_HEAT",2,1}}},"Echo_CH252_Helmet_Infantry","LM_OPCAN_DES_Shemagheye",{},{"","","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Rifleman_AA_01 : B_UNSCArmy_Rifleman_01 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman AA";
        side = 1;
        faction = "B_UNSCArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "VES_BDU_MulticamBlack_Slim";

        linkedItems[] = {"Echo_M52A_Armor_Infantry_B","Echo_CH252_Helmet_Infantry","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};
        respawnlinkedItems[] = {"Echo_M52A_Armor_Infantry_B","Echo_CH252_Helmet_Infantry","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};

        weapons[] = {"OPTRE_MA37","MatGrp_M41_SSR_AA"};
        respawnWeapons[] = {"OPTRE_MA37","MatGrp_M41_SSR_AA"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","MatGrp_M41_Twin_HEAT_AA","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","MatGrp_M41_Twin_HEAT_AA","OPTRE_32Rnd_762x51_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{"MatGrp_M41_SSR_AA","","","",{"MatGrp_M41_Twin_HEAT_AA",2},{},""},{},{"VES_BDU_MulticamBlack_Slim",{{"FirstAidKit",1},{"MRH_Map",1},{"ACE_fieldDressing",2},{"ACE_elasticBandage",2},{"ACE_packingBandage",2},{"OPTRE_Biofoam",1},{"ACE_CableTie",1},{"ACE_morphine",1},{"ACE_EarPlugs",1}}},{"Echo_M52A_Armor_Infantry_B",{{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1},{"HandGrenade",2,1},{"OPTRE_32Rnd_762x51_Mag",12,32}}},{"OPTRE_UNSC_Rucksack",{{"MatGrp_M41_Twin_HEAT_AA",2,2}}},"Echo_CH252_Helmet_Infantry","G_Combat",{},{"","","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Crewman_01 : B_UNSCArmy_Rifleman_01 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 1;
        faction = "B_UNSCArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "VES_BDU_MulticamBlack_Slim";

        linkedItems[] = {"Echo_M52A_Armor_Infantry_B","VES_CH252_CEA_Crew","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};
        respawnlinkedItems[] = {"Echo_M52A_Armor_Infantry_B","VES_CH252_CEA_Crew","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};

        weapons[] = {"OPTRE_MA5B"};
        respawnWeapons[] = {"OPTRE_MA5B"};

        magazines[] = {"OPTRE_60Rnd_762x51_Mag","OPTRE_60Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_762x51_Mag","OPTRE_60Rnd_762x51_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","OPTRE_MA5_SmartLink_legacy",{"OPTRE_60Rnd_762x51_Mag",60},{},""},{},{},{"VES_BDU_MulticamBlack_Slim",{{"FirstAidKit",1},{"MRH_Map",1},{"ACE_fieldDressing",2},{"ACE_elasticBandage",2},{"ACE_packingBandage",2},{"OPTRE_Biofoam",1},{"ACE_CableTie",1},{"ACE_morphine",1},{"ACE_EarPlugs",1}}},{"Echo_M52A_Armor_Infantry_B",{{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1},{"HandGrenade",2,1},{"OPTRE_60Rnd_762x51_Mag_Tracer",12,60}}},{},"VES_CH252_CEA_Crew","G_Tactical_Clear",{},{"","","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Pilot_01 : B_UNSCArmy_Rifleman_01 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 1;
        faction = "B_UNSCArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "VES_BDU_MulticamBlack_Slim";

        linkedItems[] = {"Echo_M52A_Armor_Infantry_B","VES_CH252_CEA_Vacuum","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};
        respawnlinkedItems[] = {"Echo_M52A_Armor_Infantry_B","VES_CH252_CEA_Vacuum","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"};

        weapons[] = {"OPTRE_MA5B"};
        respawnWeapons[] = {"OPTRE_MA5B"};

        magazines[] = {"OPTRE_60Rnd_762x51_Mag","OPTRE_60Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_762x51_Mag","OPTRE_60Rnd_762x51_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","","OPTRE_MA5_SmartLink_legacy",{"OPTRE_60Rnd_762x51_Mag",60},{},""},{},{},{"VES_BDU_MulticamBlack_Slim",{{"FirstAidKit",1},{"MRH_Map",1},{"ACE_fieldDressing",2},{"ACE_elasticBandage",2},{"ACE_packingBandage",2},{"OPTRE_Biofoam",1},{"ACE_CableTie",1},{"ACE_morphine",1},{"ACE_EarPlugs",1}}},{"Echo_M52A_Armor_Infantry_B",{{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1},{"HandGrenade",2,1},{"OPTRE_60Rnd_762x51_Mag_Tracer",12,60}}},{},"VES_CH252_CEA_Vacuum","",{},{"","","ItemRadio","ItemCompass","ItemWatch","VES_NVG_Collar"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_HEMTT_01 : B_Truck_01_covered_F_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "HEMTT";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Rifleman_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Warthog_LAAG_01 : LM_OPCAN_HOG_MG_AR_WDL_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Warthog LAAG";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Rifleman_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "B_UNSCArmy_Rifleman_01"; };
            class MainTurret : MainTurret { gunnerType = "B_UNSCArmy_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Warthog_AT_01 : LM_OPCAN_HOG_AT_AR_WDL_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Warthog AT";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Rifleman_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "B_UNSCArmy_Rifleman_01"; };
            class MainTurret : MainTurret { gunnerType = "B_UNSCArmy_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Warthog_AA_01 : LM_OPCAN_HOG_AA_AR_WDL_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Warthog AA";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Rifleman_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "B_UNSCArmy_Rifleman_01"; };
            class MainTurret : MainTurret { gunnerType = "B_UNSCArmy_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Warthog_Gauss_01 : LM_OPCAN_HOG_G_AR_WDL_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Warthog Gauss";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Rifleman_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "B_UNSCArmy_Rifleman_01"; };
            class MainTurret : MainTurret { gunnerType = "B_UNSCArmy_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_MGS32_Timberwolf_01 : LM_OPCAN_MGS_AR_WDL_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "MGS32 Timberwolf";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_UNSCArmy_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_AFV102_Hound_01 : LM_OPCAN_AFV102_AR_WDL_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "AFV102 Hound";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_UNSCArmy_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Pelican_Transport_01 : LM_OPCAN_D77_U_AR_WDL_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pelican Transport";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_UNSCArmy_Pilot_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Pelican_Gunship_01 : LM_OPCAN_D77_A_AR_WDL_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pelican Gunship";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_UNSCArmy_Pilot_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_AV14_Hornet_01 : LM_OPCAN_AV14_AR_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "AV14 Hornet";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Pilot_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_M808_Scorpion_01 : LM_OPCAN_M808_AR_WDL_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "M808 Scorpion";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_UNSCArmy_Crewman_01"; };
            class CargoTurret1 : CargoTurret1 { gunnerType = ""; };
            class CargoTurret2 : CargoTurret2 { gunnerType = ""; };
            class CargoTurret3 : CargoTurret3 { gunnerType = ""; };
            class CargoTurret4 : CargoTurret4 { gunnerType = ""; };
            class CargoTurret5 : CargoTurret5 { gunnerType = ""; };
            class CargoTurret6 : CargoTurret6 { gunnerType = ""; };
            class CargoTurret7 : CargoTurret7 { gunnerType = ""; };
            class CargoTurret8 : CargoTurret8 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Bardelas_01 : B_APC_Tracked_01_AA_F_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Bardelas";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_UNSCArmy_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'A3\Armor_F_exp\APC_Tracked_01\Data\apc_tracked_01_aa_body_olive_co.paa'];_unit setObjectTextureGlobal [1,'A3\Armor_F_exp\APC_Tracked_01\Data\mbt_01_body_olive_co.paa'];_unit setObjectTextureGlobal [2,'A3\Armor_F_exp\APC_Tracked_01\Data\apc_tracked_01_aa_tower_olive_co.paa'];_unit setObjectTextureGlobal [3,'a3\Armor_F\Data\camonet_NATO_Green_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class B_UNSCArmy_Seara_01 : B_MBT_01_mlrs_F_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Seara";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_UNSCArmy_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'A3\Armor_F_Exp\MBT_01\data\MBT_01_body_olive_CO.paa'];_unit setObjectTextureGlobal [1,'A3\Armor_F_Exp\MBT_01\data\MBT_01_MLRS_olive_co.paa'];_unit setObjectTextureGlobal [2,'A3\Armor_F\Data\camonet_NATO_Green_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class B_UNSCArmy_Speedboat_HMG_01 : B_Boat_Armed_01_minigun_F_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Speedboat HMG";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Crewman_01";

        class Turrets : Turrets {
            class FrontTurret : FrontTurret { gunnerType = "B_UNSCArmy_Crewman_01"; };
            class RearTurret : RearTurret { gunnerType = "B_UNSCArmy_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_Thunderbolt_01 : B_Plane_CAS_01_dynamicLoadout_F_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Thunderbolt";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Pilot_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_V44_Blackfish_01 : B_T_VTOL_01_armed_F_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "V44 Blackfish";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_UNSCArmy_Pilot_01"; };
            class GunnerTurret_01 : GunnerTurret_01 { gunnerType = "B_UNSCArmy_Pilot_01"; };
            class GunnerTurret_02 : GunnerTurret_02 { gunnerType = "B_UNSCArmy_Pilot_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Air_F_Exp\VTOL_01\Data\VTOL_01_EXT01_olive_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\Air_F_Exp\VTOL_01\Data\VTOL_01_EXT02_olive_CO.paa'];_unit setObjectTextureGlobal [2,'\A3\Air_F_Exp\VTOL_01\Data\VTOL_01_EXT03_olive_CO.paa'];_unit setObjectTextureGlobal [3,'\A3\Air_F_Exp\VTOL_01\Data\VTOL_01_EXT04_olive_CO.paa'];_unit setObjectTextureGlobal [4,'\A3\Air_F_Exp\VTOL_01\Data\VTOL_01_signs_CA.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class B_UNSCArmy_Black_Wasp_01 : B_Plane_Fighter_01_F_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "Black Wasp";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Pilot_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_UH80_Ghost_Hawk_01 : B_Heli_Transport_01_F_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "UH80 Ghost Hawk";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_UNSCArmy_Pilot_01"; };
            class MainTurret : MainTurret { gunnerType = "B_helicrew_F"; };
            class RightDoorGun : RightDoorGun { gunnerType = "B_helicrew_F"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_CH47_Chinook_01 : B_Heli_Transport_03_F_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "CH47 Chinook";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_UNSCArmy_Pilot_01"; };
            class MainTurret : MainTurret { gunnerType = "B_helicrew_F"; };
            class RightDoorGun : RightDoorGun { gunnerType = "B_helicrew_F"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "B_UNSCArmy_Pilot_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "B_UNSCArmy_Pilot_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNSCArmy_CH47_Chinook_Transport_01 : B_Heli_Transport_03_unarmed_F_OCimport_02 {
        author = "CPO. W. Cunningham";
        scope = 2;
        scopeCurator = 2;
        displayName = "CH47 Chinook Transport";
        side = 1;
        faction = "B_UNSCArmy";
        crew = "B_UNSCArmy_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_UNSCArmy_Pilot_01"; };
            class MainTurret : MainTurret { gunnerType = "B_helicrew_F"; };
            class RightDoorGun : RightDoorGun { gunnerType = "B_helicrew_F"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "B_UNSCArmy_Pilot_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "B_UNSCArmy_Pilot_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};