class CfgPatches {
    class I_ArcadiaArcadianIndependentMilitia {
        units[] = {
            "I_ArcadiaArcadian_Independent_Militia_Militia_01",
            "I_ArcadiaArcadian_Independent_Militia_Medic_01",
            "I_ArcadiaArcadian_Independent_Militia_Machine_Gunner_01",
            "I_ArcadiaArcadian_Independent_Militia_Commander_01",
            "I_IArcadiaArcadianIndependentMilitia_Rocketman_01",
            "I_ArcadiaArcadian_Independent_Militia_RTO_01",
            "I_ArcadiaArcadian_Independent_Militia_Squad_Leader_01",
            "I_ArcadiaArcadian_Independent_Militia_Special_Operative_01",
            "I_IArcadiaArcadianIndependentMilitia_Marksman_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "A3_Characters_F",
        //    "lambs_danger",
        //    "kka3_gestures_ace",
            "A3_Sounds_F",
        //   "3rdView",
            "A3_Sounds_F_Exp",
        //    "jsrs_soundmod_complete_edition",
            "tfar_core",
        //    "MRHSatellite",
        //    "ace_gforces",
        //    "ace_movement",
        //    "ace_medical_feedback",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
        //    "CUP_Worlds_DustEffects",
        //    "A3_Map_Abramia",
        //    "pja310",
        //    "pja305",
        //    "pja314",
        //    "ibr_panthera_c",
        //    "hebontes",
        //    "ace_thermals",
        //    "zen_attributes",
        //    "ace_refuel",
        //    "CUP_Core",
        //    "cba_xeh"
        };
        author = "Sgt. K. Bulck";
        authors[] = {"Sgt. K. Bulck"};
    };
};
//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 200.146773 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_ArcadiaArcadianIndependentMilitia {
        displayName = "AIM";
        side = 2;
        flag = "\A3\ui_f\data\map\markers\flags\Altis_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\Altis_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class Indep {

        class I_ArcadiaArcadianIndependentMilitia {
            name = "AIM";

            class Infantry {
                name = "Infantry";

                class i_arcadiaarcadian_independent_militia_infantry_fireteam {
                    name = "Fireteam";
                    side = 2;
                    faction = "I_ArcadiaArcadianIndependentMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Militia_01";
                    };
                    class Unit2 {
                        position[] = {-5,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Machine_Gunner_01";
                    };
                    class Unit3 {
                        position[] = {5,-15,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Medic_01";
                    };
                    class Unit4 {
                        position[] = {-5,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IArcadiaArcadianIndependentMilitia_Rocketman_01";
                    };
                };

                class i_arcadiaarcadian_independent_militia_infantry_squad {
                    name = "Squad";
                    side = 2;
                    faction = "I_ArcadiaArcadianIndependentMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Militia_01";
                    };
                    class Unit2 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Machine_Gunner_01";
                    };
                    class Unit3 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Machine_Gunner_01";
                    };
                    class Unit4 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_RTO_01";
                    };
                    class Unit5 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Medic_01";
                    };
                    class Unit6 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IArcadiaArcadianIndependentMilitia_Rocketman_01";
                    };
                    class Unit7 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IArcadiaArcadianIndependentMilitia_Marksman_01";
                    };
                };

                class i_arcadiaarcadian_independent_militia_infantry_command_team {
                    name = "Command Team";
                    side = 2;
                    faction = "I_ArcadiaArcadianIndependentMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Commander_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Special_Operative_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_RTO_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Special_Operative_01";
                    };
                };

                class i_arcadiaarcadian_independent_militia_infantry_spec_op_fireteam {
                    name = "Spec OP Fireteam";
                    side = 2;
                    faction = "I_ArcadiaArcadianIndependentMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Special_Operative_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Special_Operative_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Special_Operative_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ArcadiaArcadian_Independent_Militia_Special_Operative_01";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_recon_F;
    class O_recon_F_OCimport_01 : O_recon_F { scope = 0; class EventHandlers; };
    class O_recon_F_OCimport_02 : O_recon_F_OCimport_01 { class EventHandlers; };


    class I_ArcadiaArcadian_Independent_Militia_Militia_01 : O_recon_F_OCimport_02 {
        author = "Sgt. K. Bulck";
        scope = 2;
        scopeCurator = 2;
        displayName = "Militia";
        side = 2;
        faction = "I_ArcadiaArcadianIndependentMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F","G_IRAN_default"};

        uniformClass = "LM_OPCAN_KOS_Gorka4_uni_Base";

        linkedItems[] = {"V_BandollierB_ghex_F","H_Bandanna_sgg","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_BandollierB_ghex_F","H_Bandanna_sgg","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA32","OPTRE_M33","Binocular"};
        respawnWeapons[] = {"OPTRE_MA32","OPTRE_M33","Binocular"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_6Rnd_127x40_Cyl","OPTRE_32Rnd_762x51_Mag","OPTRE_6Rnd_127x40_Cyl"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_6Rnd_127x40_Cyl","OPTRE_32Rnd_762x51_Mag","OPTRE_6Rnd_127x40_Cyl"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M33","","","",{"OPTRE_6Rnd_127x40_Cyl",6},{},""},{"LM_OPCAN_KOS_Gorka4_uni_Base",{{"FirstAidKit",1},{"OPTRE_32Rnd_762x51_Mag",3,32},{"OPTRE_6Rnd_127x40_Cyl",1,6}}},{"V_BandollierB_ghex_F",{{"MiniGrenade",3,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"OPTRE_6Rnd_127x40_Cyl",2,6},{"OPTRE_32Rnd_762x51_Mag",4,32}}},{},"H_Bandanna_sgg","",{"Binocular","","","",{},{},""},{"ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ArcadiaArcadian_Independent_Militia_Medic_01 : I_ArcadiaArcadian_Independent_Militia_Militia_01 {
        author = "Sgt. K. Bulck";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 2;
        faction = "I_ArcadiaArcadianIndependentMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F","G_IRAN_default"};

        uniformClass = "LM_OPCAN_KOS_Gorka4_uni_Base";

        linkedItems[] = {"V_Pocketed_coyote_F","H_Bandanna_cbr","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_Pocketed_coyote_F","H_Bandanna_cbr","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA5K","MatGrp_M6C_Auto","Binocular"};
        respawnWeapons[] = {"OPTRE_MA5K","MatGrp_M6C_Auto","Binocular"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","MatGrp_20Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","MatGrp_20Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","MatGrp_20Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","MatGrp_20Rnd_127x40_Mag"};

        backpack = "B_Messenger_IDAP_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5K","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"MatGrp_M6C_Auto","","","",{"MatGrp_20Rnd_127x40_Mag",20},{},""},{"LM_OPCAN_KOS_Gorka4_uni_Base",{{"FirstAidKit",1},{"OPTRE_32Rnd_762x51_Mag",3,32},{"MatGrp_20Rnd_127x40_Mag",3,20}}},{"V_Pocketed_coyote_F",{{"MiniGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"OPTRE_32Rnd_762x51_Mag",3,32},{"MatGrp_20Rnd_127x40_Mag_Tracer",1,20}}},{"B_Messenger_IDAP_F",{{"ACE_elasticBandage",40},{"ACE_surgicalKit",1},{"ACE_tourniquet",4},{"ACE_splint",10},{"ACE_salineIV",3},{"ACE_salineIV_500",2},{"ACE_packingBandage",20}}},"H_Bandanna_cbr","",{"Binocular","","","",{},{},""},{"ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ArcadiaArcadian_Independent_Militia_Machine_Gunner_01 : I_ArcadiaArcadian_Independent_Militia_Militia_01 {
        author = "Sgt. K. Bulck";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machine Gunner";
        side = 2;
        faction = "I_ArcadiaArcadianIndependentMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F","G_IRAN_default"};

        uniformClass = "LM_OPCAN_KOS_Gorka4_uni_Base";

        linkedItems[] = {"V_TacChestrig_oli_F","H_Bandanna_sgg","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_TacChestrig_oli_F","H_Bandanna_sgg","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA37B","OPTRE_M33","Binocular"};
        respawnWeapons[] = {"OPTRE_MA37B","OPTRE_M33","Binocular"};

        magazines[] = {"OPTRE_60Rnd_762x51_Mag","OPTRE_6Rnd_127x40_Cyl","OPTRE_60Rnd_762x51_Mag","OPTRE_6Rnd_127x40_Cyl"};
        respawnMagazines[] = {"OPTRE_60Rnd_762x51_Mag","OPTRE_6Rnd_127x40_Cyl","OPTRE_60Rnd_762x51_Mag","OPTRE_6Rnd_127x40_Cyl"};

        backpack = "B_AssaultPack_tna_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37B","","","",{"OPTRE_60Rnd_762x51_Mag",60},{},""},{},{"OPTRE_M33","","","",{"OPTRE_6Rnd_127x40_Cyl",6},{},""},{"LM_OPCAN_KOS_Gorka4_uni_Base",{{"FirstAidKit",1},{"OPTRE_6Rnd_127x40_Cyl",1,6},{"OPTRE_60Rnd_762x51_Mag",3,60}}},{"V_TacChestrig_oli_F",{{"MiniGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"OPTRE_6Rnd_127x40_Cyl",2,6},{"OPTRE_60Rnd_762x51_Mag",6,60}}},{"B_AssaultPack_tna_F",{{"ACE_fieldDressing",5},{"OPTRE_60Rnd_762x51_Mag",7,60},{"MiniGrenade",2,1}}},"H_Bandanna_sgg","",{"Binocular","","","",{},{},""},{"ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ArcadiaArcadian_Independent_Militia_Special_Operative_01 : I_ArcadiaArcadian_Independent_Militia_Militia_01 {
        author = "Sgt. K. Bulck";
        scope = 2;
        scopeCurator = 2;
        displayName = "Special Operative";
        side = 2;
        faction = "I_ArcadiaArcadianIndependentMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_BJ_Undersuit";

        linkedItems[] = {"OPTRE_Ins_BJ_Armor","OPTRE_Ins_BJ_Helmet","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch","VES_NVG_UAB_UL_CNM"};
        respawnlinkedItems[] = {"OPTRE_Ins_BJ_Armor","OPTRE_Ins_BJ_Helmet","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch","VES_NVG_UAB_UL_CNM"};

        weapons[] = {"OPTRE_MA5CGL","OPTRE_M48_PAW","OPTRE_M6D","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_MA5CGL","OPTRE_M48_PAW","OPTRE_M6D","OPTRE_Smartfinder"};

        magazines[] = {"HOW_32Rnd_762x51_IRDM_Mag","UGL_8Gauge_Pellet","OPTRE_1Rnd_50x137_HEAT","OPTRE_12Rnd_127x40_Mag","Laserbatteries","HOW_32Rnd_762x51_IRDM_Mag","UGL_8Gauge_Pellet","OPTRE_12Rnd_127x40_Mag","Laserbatteries"};
        respawnMagazines[] = {"HOW_32Rnd_762x51_IRDM_Mag","UGL_8Gauge_Pellet","OPTRE_1Rnd_50x137_HEAT","OPTRE_12Rnd_127x40_Mag","Laserbatteries","HOW_32Rnd_762x51_IRDM_Mag","UGL_8Gauge_Pellet","OPTRE_12Rnd_127x40_Mag","Laserbatteries"};

        backpack = "OPTRE_ILCS_Rucksack_Black";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5CGL","OPTRE_MA5Suppressor","OPTRE_BMR_Laser","OPTRE_M6S_Scope",{"HOW_32Rnd_762x51_IRDM_Mag",32},{"UGL_8Gauge_Pellet",1},""},{"OPTRE_M48_PAW","","","",{"OPTRE_1Rnd_50x137_HEAT",1},{},""},{"OPTRE_M6D","","OPTRE_M6D_Flashlight","OPTRE_M6D_Smartlink",{"OPTRE_12Rnd_127x40_Mag",12},{},""},{"OPTRE_Ins_BJ_Undersuit",{{"FirstAidKit",1},{"HOW_32Rnd_762x51_IRDM_Mag",3,32},{"UGL_8Gauge_Pellet",2,1}}},{"OPTRE_Ins_BJ_Armor",{{"ACE_fieldDressing",10},{"MiniGrenade",3,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"OPTRE_1Rnd_50x137_HEAT",1,1},{"ACE_40mm_Flare_green",2,1},{"OPTRE_32Rnd_762x51_Mag",4,32},{"3Rnd_HE_Grenade_shell",2,3}}},{"OPTRE_ILCS_Rucksack_Black",{{"OPTRE_1Rnd_50x137_HEAT",6,1}}},"OPTRE_Ins_BJ_Helmet","",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch","VES_NVG_UAB_UL_CNM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ArcadiaArcadian_Independent_Militia_Commander_01 : I_ArcadiaArcadian_Independent_Militia_Special_Operative_01 {
        author = "Sgt. K. Bulck";
        scope = 2;
        scopeCurator = 2;
        displayName = "Commander";
        side = 2;
        faction = "I_ArcadiaArcadianIndependentMilitia";

        identityTypes[] = {"Tanker","LanguagePER_F","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_BJ_Undersuit";

        linkedItems[] = {"OPTRE_Ins_BJ_Armor","ACOMP_CO_JAmbrose_MAR","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch","VES_NVG_UAB"};
        respawnlinkedItems[] = {"OPTRE_Ins_BJ_Armor","ACOMP_CO_JAmbrose_MAR","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch","VES_NVG_UAB"};

        weapons[] = {"OPTRE_HMG38","OPTRE_M6G","ACE_VectorDay"};
        respawnWeapons[] = {"OPTRE_HMG38","OPTRE_M6G","ACE_VectorDay"};

        magazines[] = {"OPTRE_40Rnd_30x06_Mag","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_Mag","OPTRE_40Rnd_30x06_Mag","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_40Rnd_30x06_Mag","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_Mag","OPTRE_40Rnd_30x06_Mag","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_ILCS_Rucksack_Black";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_HMG38","muzzle_snds_65_TI_blk_F","","OPTRE_HMG38_CarryHandle",{"OPTRE_40Rnd_30x06_Mag",40},{"1Rnd_HE_Grenade_shell",1},"bipod_02_F_blk"},{},{"OPTRE_M6G","OPTRE_M6C_compensator","OPTRE_M6G_Flashlight","OPTRE_M6GX_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"OPTRE_Ins_BJ_Undersuit",{{"FirstAidKit",1},{"OPTRE_40Rnd_30x06_Mag",3,40},{"1Rnd_HE_Grenade_shell",3,1}}},{"OPTRE_Ins_BJ_Armor",{{"ACE_fieldDressing",10},{"MiniGrenade",3,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"OPTRE_8Rnd_127x40_Mag",3,8},{"OPTRE_40Rnd_30x06_Mag",4,40}}},{"OPTRE_ILCS_Rucksack_Black",{}},"ACOMP_CO_JAmbrose_MAR","OPTRE_EyePiece",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch","VES_NVG_UAB"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_IArcadiaArcadianIndependentMilitia_Rocketman_01 : I_ArcadiaArcadian_Independent_Militia_Militia_01 {
        author = "Sgt. K. Bulck";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rocketman";
        side = 2;
        faction = "I_ArcadiaArcadianIndependentMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F","G_IRAN_default"};

        uniformClass = "LM_OPCAN_KOS_Gorka4_uni_Base";

        linkedItems[] = {"V_BandollierB_ghex_F","H_Bandanna_sgg","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_BandollierB_ghex_F","H_Bandanna_sgg","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA32","OPTRE_M48_PAW","OPTRE_M33","Binocular"};
        respawnWeapons[] = {"OPTRE_MA32","OPTRE_M48_PAW","OPTRE_M33","Binocular"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_1Rnd_50x137_HEAT","OPTRE_6Rnd_127x40_Cyl","OPTRE_32Rnd_762x51_Mag","OPTRE_6Rnd_127x40_Cyl"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_1Rnd_50x137_HEAT","OPTRE_6Rnd_127x40_Cyl","OPTRE_32Rnd_762x51_Mag","OPTRE_6Rnd_127x40_Cyl"};

        backpack = "B_AssaultPack_tna_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{"OPTRE_M48_PAW","","","",{"OPTRE_1Rnd_50x137_HEAT",1},{},""},{"OPTRE_M33","","","",{"OPTRE_6Rnd_127x40_Cyl",6},{},""},{"LM_OPCAN_KOS_Gorka4_uni_Base",{{"FirstAidKit",1},{"OPTRE_32Rnd_762x51_Mag",3,32},{"OPTRE_6Rnd_127x40_Cyl",1,6}}},{"V_BandollierB_ghex_F",{{"MiniGrenade",3,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"OPTRE_6Rnd_127x40_Cyl",2,6},{"OPTRE_32Rnd_762x51_Mag",4,32}}},{"B_AssaultPack_tna_F",{{"OPTRE_1Rnd_50x137_HEAT",4,1}}},"H_Bandanna_sgg","",{"Binocular","","","",{},{},""},{"ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ArcadiaArcadian_Independent_Militia_RTO_01 : I_ArcadiaArcadian_Independent_Militia_Militia_01 {
        author = "Sgt. K. Bulck";
        scope = 2;
        scopeCurator = 2;
        displayName = "RTO";
        side = 2;
        faction = "I_ArcadiaArcadianIndependentMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F","G_IRAN_default"};

        uniformClass = "LM_OPCAN_KOS_Gorka4_uni_Base";

        linkedItems[] = {"V_TacChestrig_oli_F","H_Bandanna_sgg","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_TacChestrig_oli_F","H_Bandanna_sgg","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA32","OPTRE_M33","Binocular"};
        respawnWeapons[] = {"OPTRE_MA32","OPTRE_M33","Binocular"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_6Rnd_127x40_Cyl","OPTRE_32Rnd_762x51_Mag","OPTRE_6Rnd_127x40_Cyl"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_6Rnd_127x40_Cyl","OPTRE_32Rnd_762x51_Mag","OPTRE_6Rnd_127x40_Cyl"};

        backpack = "TFAR_bussole";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M33","","","",{"OPTRE_6Rnd_127x40_Cyl",6},{},""},{"LM_OPCAN_KOS_Gorka4_uni_Base",{{"FirstAidKit",1},{"OPTRE_32Rnd_762x51_Mag",3,32},{"OPTRE_6Rnd_127x40_Cyl",1,6}}},{"V_TacChestrig_oli_F",{{"MiniGrenade",3,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"OPTRE_6Rnd_127x40_Cyl",2,6},{"OPTRE_32Rnd_762x51_Mag",4,32}}},{"TFAR_bussole",{}},"H_Bandanna_sgg","",{"Binocular","","","",{},{},""},{"ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ArcadiaArcadian_Independent_Militia_Squad_Leader_01 : I_ArcadiaArcadian_Independent_Militia_Militia_01 {
        author = "Sgt. K. Bulck";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 2;
        faction = "I_ArcadiaArcadianIndependentMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F","G_IRAN_default"};

        uniformClass = "LM_OPCAN_KOS_Gorka4_uni_Base";

        linkedItems[] = {"VES_M52A_WDL_Rifleman_D","OPTRE_Ins_URF_Helmet1","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"VES_M52A_WDL_Rifleman_D","OPTRE_Ins_URF_Helmet1","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA5AGL","MatGrp_M6C_Auto","Binocular"};
        respawnWeapons[] = {"OPTRE_MA5AGL","MatGrp_M6C_Auto","Binocular"};

        magazines[] = {"OPTRE_60Rnd_762x51_Mag","UGL_8Gauge_Pellet","MatGrp_20Rnd_127x40_Mag","OPTRE_60Rnd_762x51_Mag","UGL_8Gauge_Pellet","MatGrp_20Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_762x51_Mag","UGL_8Gauge_Pellet","MatGrp_20Rnd_127x40_Mag","OPTRE_60Rnd_762x51_Mag","UGL_8Gauge_Pellet","MatGrp_20Rnd_127x40_Mag"};

        backpack = "B_Messenger_Olive_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5AGL","OPTRE_MA5Suppressor","OPTRE_BMR_Laser","OPTRE_BR55HB_Scope",{"OPTRE_60Rnd_762x51_Mag",60},{"UGL_8Gauge_Pellet",1},""},{},{"MatGrp_M6C_Auto","OPTRE_M6C_compensator","OPTRE_M6C_Laser","OPTRE_M7_Sight_v2",{"MatGrp_20Rnd_127x40_Mag",20},{},""},{"LM_OPCAN_KOS_Gorka4_uni_Base",{{"FirstAidKit",1},{"UGL_8Gauge_Pellet",1,1}}},{"VES_M52A_WDL_Rifleman_D",{{"ACE_fieldDressing",15},{"MiniGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellRed",1,1},{"Chemlight_red",2,1},{"OPTRE_60Rnd_762x51_Mag",10,60}}},{"B_Messenger_Olive_F",{{"3Rnd_HE_Grenade_shell",4,3}}},"OPTRE_Ins_URF_Helmet1","",{"Binocular","","","",{},{},""},{"ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_IArcadiaArcadianIndependentMilitia_Marksman_01 : I_ArcadiaArcadian_Independent_Militia_Militia_01 {
        author = "Sgt. K. Bulck";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 2;
        faction = "I_ArcadiaArcadianIndependentMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F","G_IRAN_default"};

        uniformClass = "LM_OPCAN_KOS_Gorka4_uni_Base";

        linkedItems[] = {"V_Rangemaster_Belt","H_Bandanna_sgg","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_Rangemaster_Belt","H_Bandanna_sgg","ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M393S_DMR","OPTRE_M33","Binocular"};
        respawnWeapons[] = {"OPTRE_M393S_DMR","OPTRE_M33","Binocular"};

        magazines[] = {"HOW_15Rnd_762x51_338_API_Mag","OPTRE_6Rnd_127x40_Cyl","HOW_15Rnd_762x51_338_API_Mag","OPTRE_6Rnd_127x40_Cyl"};
        respawnMagazines[] = {"HOW_15Rnd_762x51_338_API_Mag","OPTRE_6Rnd_127x40_Cyl","HOW_15Rnd_762x51_338_API_Mag","OPTRE_6Rnd_127x40_Cyl"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M393S_DMR","","","OPTRE_M393_Scope_v2",{"HOW_15Rnd_762x51_338_API_Mag",15},{},""},{},{"OPTRE_M33","","","",{"OPTRE_6Rnd_127x40_Cyl",6},{},""},{"LM_OPCAN_KOS_Gorka4_uni_Base",{{"FirstAidKit",1},{"OPTRE_6Rnd_127x40_Cyl",1,6},{"HOW_15Rnd_762x51_338_API_Mag",3,15}}},{"V_Rangemaster_Belt",{{"OPTRE_6Rnd_127x40_Cyl",1,6},{"HOW_15Rnd_762x51_338_Magnum_Mag",3,15}}},{},"H_Bandanna_sgg","",{"Binocular","","","",{},{},""},{"ItemMap","ItemAndroid","TFAR_rf7800str","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};