
//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 204.147719 on Stable branch
// Generated with ALiVE version 1.14.1.2105061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_BIAArmy {
        displayName = "[105th] Biko Independence Army";
        side = 2;
        flag = "\a3\Data_F_Exp\Flags\flag_SYND_CO.paa";
        icon = "\a3\Data_F_Exp\Flags\flag_SYND_CO.paa";
        priority = 0;
    };
};
class CfgPatches {
    class I_BIAArmy {
        units[] = {
            "I_BIAArmy_Guerilla_Rifleman_01",
            "I_BIAArmy_Guerilla_Shotgunner_01",
            "I_BIAArmy_Guerilla_AT_EOD_01",
            "I_BIAArmy_Guerilla_Light_AT_01",
            "I_BIAArmy_Guerilla_Warlord_01",
            "I_BIAArmy_Guerilla_Spotter_01",
            "I_BIAArmy_Guerilla_Anti_Air_01",
            "I_BIAArmy_Guerilla_Sniper_01",
            "I_BIAArmy_Guerilla_Suicide_Bomber_01",
            "I_BIAArmy_Guerilla_Autorifleman_01",
            "I_BIAArmy_Guerilla_Techie_01",
            "I_BIAArmy_Guerilla_Techie_02",
            "I_BIAArmy_Guerilla_Techie_AT_01",
            "I_BIAArmy_Guerilla_Techie_Repair_01",
            "I_BIAArmy_Truck_01",
            "I_BIAArmy_M2_HMG_01",
            "I_BIAArmy_Mk6_Mortar_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "A3_Characters_F",
            "lambs_danger",
            "kka3_gestures_ace",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "tfar_core",
            "MRHSatellite",
            "ace_gforces",
            "ace_movement",
            "ace_medical_feedback",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "CUP_Worlds_DustEffects",
            "A3_Map_Abramia",
            "pja310",
            "pja305",
            "pja314",
            "ibr_panthera_c",
            "hebontes",
            "tem_vinjesvingenc",
            "ace_thermals",
            "lambs_formations",
            "zen_attributes",
            "ace_refuel",
            "CUP_Core",
            "cba_xeh",
            "A3_Soft_F_Offroad_01",
            "A3_Soft_F_Enoch_Offroad_01",
            "A3_Soft_F",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F_ParticleEffects",
            "babe_int_EHs",
            "A3_Map_Winthera3",
            "MRHMilsimTools",
            "ace_interaction",
            "ace_cargo",
            "A3_Armor_F_Beta",
            "ace_repair",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_Bootcamp_Van_01",
            "A3_Soft_F_Beta_Truck_01",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Truck_01",
            "A3_Soft_F_EPC_Truck_03",
            "Jbad_Cat_Dumper",
            "Jbad_Forklift",
            "A3_Soft_F_Orange_Van_02",
            "A3_Static_F_HMG_02",
            "ace_csw",
            "A3_Static_F",
            "A3_Static_F_AA_01",
            "A3_Static_F_AT_01",
            "CUP_WarfareBuildings",
            "ace_dragging",
            "A3_Static_F_Mortar_01",
            "ace_mk6mortar",
            "ace_artillerytables"
        };
        author = "GySgt. C. Varner";
        authors[] = {"GySgt. C. Varner"};
    };
};
class CfgGroups {
    class Indep {

        class I_BIAArmy {
            name = "[105th] Biko Independence Army";

            class Infantry {
                name = "Infantry";

                class i_biaarmy_infantry_guerilla_patrol {
                    name = "Guerilla Patrol";
                    side = 2;
                    faction = "I_BIAArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Shotgunner_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Light_AT_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Spotter_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Anti_Air_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Autorifleman_01";
                    };
                };

                class i_biaarmy_infantry_guerilla_hunter_killer_rpg_team {
                    name = "Guerilla Hunter-Killer RPG Team";
                    side = 2;
                    faction = "I_BIAArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_AT_EOD_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Light_AT_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Anti_Air_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Spotter_01";
                    };
                };

                class i_biaarmy_infantry_guerilla_leadership_team {
                    name = "Guerilla Leadership Team";
                    side = 2;
                    faction = "I_BIAArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CAPTAIN";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Warlord_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Spotter_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Rifleman_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class i_biaarmy_infantry_sniper_team {
                    name = "Sniper Team";
                    side = 2;
                    faction = "I_BIAArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Sniper_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_BIAArmy_Guerilla_Sniper_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_G_Soldier_F;
    class I_G_Soldier_F_OCimport_01 : I_G_Soldier_F { scope = 0; class EventHandlers; };
    class I_G_Soldier_F_OCimport_02 : I_G_Soldier_F_OCimport_01 { class EventHandlers; };

    class I_G_Offroad_01_armed_F;
    class I_G_Offroad_01_armed_F_OCimport_01 : I_G_Offroad_01_armed_F { scope = 0; class EventHandlers; class Turrets; };
    class I_G_Offroad_01_armed_F_OCimport_02 : I_G_Offroad_01_armed_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class M2_Turret;
        };
    };

    class I_G_Offroad_01_F;
    class I_G_Offroad_01_F_OCimport_01 : I_G_Offroad_01_F { scope = 0; class EventHandlers; class Turrets; };
    class I_G_Offroad_01_F_OCimport_02 : I_G_Offroad_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class I_G_Offroad_01_AT_F;
    class I_G_Offroad_01_AT_F_OCimport_01 : I_G_Offroad_01_AT_F { scope = 0; class EventHandlers; class Turrets; };
    class I_G_Offroad_01_AT_F_OCimport_02 : I_G_Offroad_01_AT_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class AT_Turret;
        };
    };

    class I_G_Offroad_01_repair_F;
    class I_G_Offroad_01_repair_F_OCimport_01 : I_G_Offroad_01_repair_F { scope = 0; class EventHandlers; };
    class I_G_Offroad_01_repair_F_OCimport_02 : I_G_Offroad_01_repair_F_OCimport_01 { scope = 0; class EventHandlers; };

    class I_G_Van_01_transport_F;
    class I_G_Van_01_transport_F_OCimport_01 : I_G_Van_01_transport_F { scope = 0; class EventHandlers; class Turrets; };
    class I_G_Van_01_transport_F_OCimport_02 : I_G_Van_01_transport_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_L1;
            class CargoTurret_L2;
            class CargoTurret_L3;
            class CargoTurret_L4;
            class CargoTurret_L5;
            class CargoTurret_R1;
            class CargoTurret_R2;
            class CargoTurret_R3;
            class CargoTurret_R4;
            class CargoTurret_R5;
        };
    };

    class I_G_HMG_02_high_F;
    class I_G_HMG_02_high_F_OCimport_01 : I_G_HMG_02_high_F { scope = 0; class EventHandlers; class Turrets; };
    class I_G_HMG_02_high_F_OCimport_02 : I_G_HMG_02_high_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_G_Mortar_01_F;
    class I_G_Mortar_01_F_OCimport_01 : I_G_Mortar_01_F { scope = 0; class EventHandlers; class Turrets; };
    class I_G_Mortar_01_F_OCimport_02 : I_G_Mortar_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };


    class I_BIAArmy_Guerilla_Rifleman_01 : I_G_Soldier_F_OCimport_02 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Rifleman";
        side = 2;
        faction = "I_BIAArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "OPTRE_Ins_ER_uniform_GGgrey";

        linkedItems[] = {"V_Chestrig_oli","H_Shemag_olive","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_Chestrig_oli","H_Shemag_olive","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_BR45"};
        respawnWeapons[] = {"OPTRE_BR45"};

        magazines[] = {"OPTRE_36Rnd_95x40_Mag","OPTRE_36Rnd_95x40_Mag"};
        respawnMagazines[] = {"OPTRE_36Rnd_95x40_Mag","OPTRE_36Rnd_95x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_BR45","","acc_flashlight","OPTRE_BR45_Scope",{"OPTRE_36Rnd_95x40_Mag",36},{},"OPTRE_BR45Grip"},{},{},{"OPTRE_Ins_ER_uniform_GGgrey",{{"FirstAidKit",1},{"OPTRE_36Rnd_95x40_Mag",3,36}}},{"V_Chestrig_oli",{{"OPTRE_Biofoam",2},{"ACE_M26_Clacker",1},{"HandGrenade",1,1},{"MiniGrenade",1,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_blue",1,1},{"OPTRE_36Rnd_95x40_Mag_JHP",8,36},{"M41_IED_Remote_Mag",1,1}}},{},"H_Shemag_olive","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_BIAArmy_Guerilla_Shotgunner_01 : I_BIAArmy_Guerilla_Rifleman_01 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Shotgunner";
        side = 2;
        faction = "I_BIAArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "OPTRE_Ins_ER_uniform_GGod";

        linkedItems[] = {"VES_M52A_URB_Vest_A","H_Cap_headphones","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"VES_M52A_URB_Vest_A","H_Cap_headphones","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M90A"};
        respawnWeapons[] = {"OPTRE_M90A"};

        magazines[] = {"OPTRE_6Rnd_8Gauge_Tungsten_Buckshot","OPTRE_6Rnd_8Gauge_Tungsten_Buckshot"};
        respawnMagazines[] = {"OPTRE_6Rnd_8Gauge_Tungsten_Buckshot","OPTRE_6Rnd_8Gauge_Tungsten_Buckshot"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M90A","","OPTRE_M45_Flashlight","",{"OPTRE_6Rnd_8Gauge_Tungsten_Buckshot",6},{},""},{},{},{"OPTRE_Ins_ER_uniform_GGod",{{"FirstAidKit",1},{"ACE_quikclot",10}}},{"VES_M52A_URB_Vest_A",{{"OPTRE_Biofoam",2},{"ACE_M26_Clacker",1},{"HandGrenade",1,1},{"MiniGrenade",1,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_blue",1,1},{"M41_IED_Remote_Mag",1,1},{"OPTRE_12Rnd_8Gauge_Slug",3,12},{"OPTRE_12Rnd_8Gauge_Tungsten_Buckshot",3,12},{"OPTRE_12Rnd_8Gauge_Tungsten_Slug",3,12}}},{},"H_Cap_headphones","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_BIAArmy_Guerilla_AT_EOD_01 : I_BIAArmy_Guerilla_Rifleman_01 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla AT EOD";
        side = 2;
        faction = "I_BIAArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_BG_Guerilla2_3";

        linkedItems[] = {"V_SmershVest_01_radio_F","LM_OPCAN_CGC_CH230_Combo_CAM","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_SmershVest_01_radio_F","LM_OPCAN_CGC_CH230_Combo_CAM","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA5B","105_CRCKT_PEN","OPTRE_M6B"};
        respawnWeapons[] = {"OPTRE_MA5B","105_CRCKT_PEN","OPTRE_M6B"};

        magazines[] = {"OPTRE_60Rnd_762x51_Mag","CRCKT_PEN","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_762x51_Mag","CRCKT_PEN","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "B_Carryall_green_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5B","","OPTRE_M45_Flashlight","",{"OPTRE_60Rnd_762x51_Mag",60},{},""},{"105_CRCKT_PEN","","","",{"CRCKT_PEN",1},{},""},{"OPTRE_M6B","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"U_BG_Guerilla2_3",{{"FirstAidKit",1},{"OPTRE_60Rnd_762x51_Mag",1,60},{"OPTRE_8Rnd_127x40_Mag",1,8}}},{"V_SmershVest_01_radio_F",{{"OPTRE_Biofoam",2},{"ACE_M26_Clacker",1},{"ACE_DeadManSwitch",1},{"ACE_Clacker",1},{"HandGrenade",1,1},{"SmokeShell",1,1},{"OPTRE_60Rnd_762x51_Mag",6,60},{"OPTRE_8Rnd_127x40_Mag",2,8}}},{"B_Carryall_green_F",{{"M41_IED_Remote_Mag",5,1},{"DemoCharge_Remote_Mag",5,1},{"IEDLandSmall_Remote_Mag",2,1},{"APERSMine_Range_Mag",1,1},{"C7_Remote_Mag",2,1},{"CRCKT_PEN",1,1}}},"LM_OPCAN_CGC_CH230_Combo_CAM","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_BIAArmy_Guerilla_Light_AT_01 : I_BIAArmy_Guerilla_Rifleman_01 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Light AT";
        side = 2;
        faction = "I_BIAArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_I_L_Uniform_01_tshirt_black_F";

        linkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Shemag_olive_hs","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Shemag_olive_hs","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA32","OPTRE_M48_PAW"};
        respawnWeapons[] = {"OPTRE_MA32","OPTRE_M48_PAW"};

        magazines[] = {"v105_32Rnd_762x51_IRDM_Mag","OPTRE_1Rnd_50x137_HEAT","v105_32Rnd_762x51_IRDM_Mag"};
        respawnMagazines[] = {"v105_32Rnd_762x51_IRDM_Mag","OPTRE_1Rnd_50x137_HEAT","v105_32Rnd_762x51_IRDM_Mag"};

        backpack = "B_Carryall_green_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32","ACE_muzzle_mzls_B","","OPTRE_M393_EOTECH_v2",{"v105_32Rnd_762x51_IRDM_Mag",32},{},""},{"OPTRE_M48_PAW","","","",{"OPTRE_1Rnd_50x137_HEAT",1},{},""},{},{"U_I_L_Uniform_01_tshirt_black_F",{{"FirstAidKit",1},{"v105_32Rnd_762x51_IRDM_Mag",1,32}}},{"LM_OPCAN_ACTV_CGC_VEST",{{"OPTRE_Biofoam",2},{"ACE_M26_Clacker",1},{"HandGrenade",1,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"OPTRE_32Rnd_762x51_Mag",8,32},{"OPTRE_M9_Frag",2,1}}},{"B_Carryall_green_F",{{"OPTRE_1Rnd_50x137_HEAT",9,1}}},"H_Shemag_olive_hs","LM_OPCAN_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_BIAArmy_Guerilla_Warlord_01 : I_BIAArmy_Guerilla_Rifleman_01 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Warlord";
        side = 2;
        faction = "I_BIAArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "OPTRE_Ins_ER_jacket_surplus_OD";

        linkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_MilCap_grn","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_MilCap_grn","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_HMG38","OPTRE_M6B"};
        respawnWeapons[] = {"OPTRE_HMG38","OPTRE_M6B"};

        magazines[] = {"OPTRE_40Rnd_30x06_Mag","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_Mag","OPTRE_40Rnd_30x06_Mag","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_40Rnd_30x06_Mag","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_Mag","OPTRE_40Rnd_30x06_Mag","1Rnd_HE_Grenade_shell","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_HMG38","","","OPTRE_BR45_Scope",{"OPTRE_40Rnd_30x06_Mag",40},{"1Rnd_HE_Grenade_shell",1},"bipod_01_F_blk"},{},{"OPTRE_M6B","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"OPTRE_Ins_ER_jacket_surplus_OD",{{"FirstAidKit",1},{"OPTRE_40Rnd_30x06_Mag",1,40},{"OPTRE_8Rnd_127x40_Mag",1,8}}},{"LM_OPCAN_ACTV_CGC_VEST",{{"OPTRE_Biofoam",2},{"ACE_M26_Clacker",1},{"SmokeShellGreen",1,1},{"M41_IED_Remote_Mag",1,1},{"OPTRE_40Rnd_30x06_Mag",5,40},{"ACE_Chemlight_HiRed",3,1},{"OPTRE_M9_Frag",3,1},{"OPTRE_M2_Smoke_Red",2,1},{"OPTRE_M2_Smoke_Purple",2,1},{"OPTRE_M2_Smoke",2,1},{"ACE_M84",1,1}}},{"OPTRE_UNSC_Rucksack",{{"OPTRE_8Rnd_127x40_Mag",2,8}}},"H_MilCap_grn","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_BIAArmy_Guerilla_Spotter_01 : I_BIAArmy_Guerilla_Rifleman_01 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Spotter";
        side = 2;
        faction = "I_BIAArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_C_Uniform_Farmer_01_F";

        linkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Shemag_olive_hs","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Shemag_olive_hs","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_BR45"};
        respawnWeapons[] = {"OPTRE_BR45"};

        magazines[] = {"OPTRE_36Rnd_95x40_Mag","OPTRE_36Rnd_95x40_Mag"};
        respawnMagazines[] = {"OPTRE_36Rnd_95x40_Mag","OPTRE_36Rnd_95x40_Mag"};

        backpack = "OPTRE_ANPRC_515";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_BR45","","acc_flashlight","OPTRE_BR45_Scope",{"OPTRE_36Rnd_95x40_Mag",36},{},"OPTRE_BR45Grip"},{},{},{"U_C_Uniform_Farmer_01_F",{{"FirstAidKit",1},{"OPTRE_36Rnd_95x40_Mag",2,36}}},{"LM_OPCAN_ACTV_CGC_VEST",{{"OPTRE_Biofoam",2},{"ACE_M26_Clacker",1},{"HandGrenade",1,1},{"MiniGrenade",1,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_blue",1,1},{"OPTRE_36Rnd_95x40_Mag_JHP",8,36},{"M41_IED_Remote_Mag",1,1}}},{"OPTRE_ANPRC_515",{}},"H_Shemag_olive_hs","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_BIAArmy_Guerilla_Anti_Air_01 : I_BIAArmy_Guerilla_Light_AT_01 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Anti-Air";
        side = 2;
        faction = "I_BIAArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_I_L_Uniform_01_tshirt_black_F";

        linkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Shemag_olive_hs","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Shemag_olive_hs","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA32","MatGrp_M41_SSR_AA"};
        respawnWeapons[] = {"OPTRE_MA32","MatGrp_M41_SSR_AA"};

        magazines[] = {"v105_32Rnd_762x51_IRDM_Mag","MatGrp_M41_Twin_HEAT_AA","v105_32Rnd_762x51_IRDM_Mag"};
        respawnMagazines[] = {"v105_32Rnd_762x51_IRDM_Mag","MatGrp_M41_Twin_HEAT_AA","v105_32Rnd_762x51_IRDM_Mag"};

        backpack = "B_Carryall_green_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32","ACE_muzzle_mzls_B","","OPTRE_M393_EOTECH_v2",{"v105_32Rnd_762x51_IRDM_Mag",32},{},""},{"MatGrp_M41_SSR_AA","","","",{"MatGrp_M41_Twin_HEAT_AA",2},{},""},{},{"U_I_L_Uniform_01_tshirt_black_F",{{"FirstAidKit",1},{"v105_32Rnd_762x51_IRDM_Mag",1,32}}},{"LM_OPCAN_ACTV_CGC_VEST",{{"OPTRE_Biofoam",2},{"ACE_M26_Clacker",1},{"HandGrenade",1,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"OPTRE_32Rnd_762x51_Mag",8,32},{"OPTRE_M9_Frag",2,1}}},{"B_Carryall_green_F",{{"MatGrp_M41_Twin_HEAT_AA",4,2}}},"H_Shemag_olive_hs","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_BIAArmy_Guerilla_Sniper_01 : I_BIAArmy_Guerilla_Spotter_01 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Sniper";
        side = 2;
        faction = "I_BIAArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_B_CTRG_Soldier_2_F";

        linkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Shemag_olive_hs","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Shemag_olive_hs","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_SRM77_S1"};
        respawnWeapons[] = {"OPTRE_SRM77_S1"};

        magazines[] = {"OPTRE_10Rnd_127x99","OPTRE_10Rnd_127x99"};
        respawnMagazines[] = {"OPTRE_10Rnd_127x99","OPTRE_10Rnd_127x99"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_SRM77_S1","","acc_pointer_IR","OPTRE_SRM_Sight",{"OPTRE_10Rnd_127x99",10},{},"bipod_01_F_blk"},{},{},{"U_B_CTRG_Soldier_2_F",{{"FirstAidKit",1},{"OPTRE_10Rnd_127x99",2,10}}},{"LM_OPCAN_ACTV_CGC_VEST",{{"OPTRE_Biofoam",2},{"ACE_M26_Clacker",1},{"SmokeShellGreen",1,1},{"Chemlight_blue",1,1},{"M41_IED_Remote_Mag",1,1},{"OPTRE_10Rnd_127x99",8,10},{"ALiVE_Handgrenade_stone",1,1},{"OPTRE_M9_Frag",3,1},{"OPTRE_M8_Flare",1,1},{"OPTRE_M2_Smoke_Red",1,1},{"OPTRE_M2_Smoke_Purple",1,1},{"ACE_M84",2,1},{"ACE_CTS9",1,1}}},{},"H_Shemag_olive_hs","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_BIAArmy_Guerilla_Suicide_Bomber_01 : I_BIAArmy_Guerilla_Spotter_01 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Suicide Bomber";
        side = 2;
        faction = "I_BIAArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_I_L_Uniform_01_deserter_F";

        linkedItems[] = {"V_I_G_resistanceLeader_F","H_ShemagOpen_khk","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_I_G_resistanceLeader_F","H_ShemagOpen_khk","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_I_L_Uniform_01_deserter_F",{{"FirstAidKit",1},{"MRH_Map",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_Flashlight_MX991",1}}},{"V_I_G_resistanceLeader_F",{{"ACE_M26_Clacker",2},{"ACE_Clacker",1},{"ACE_DefusalKit",1},{"ACE_EntrenchingTool",1},{"ACE_wirecutter",1},{"kka3_ace_extension_Land_Wrench_F",1},{"VES_TacSpraycan",1},{"HandGrenade",1,1},{"MiniGrenade",1,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_blue",1,1}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"DemoCharge_Remote_Mag",10,1},{"IEDUrbanBig_Remote_Mag",1,1},{"IEDLandSmall_Remote_Mag",1,1},{"SLAMDirectionalMine_Wire_Mag",1,1},{"M41_IED_Remote_Mag",2,1},{"C7_Remote_Mag",2,1}}},"H_ShemagOpen_khk","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_BIAArmy_Guerilla_Autorifleman_01 : I_BIAArmy_Guerilla_Rifleman_01 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Autorifleman";
        side = 2;
        faction = "I_BIAArmy";

        identityTypes[] = {"Head_TK","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_C_ArtTShirt_01_v5_F";

        linkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_ShemagOpen_tan","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_ShemagOpen_tan","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"v105_M73SAW"};
        respawnWeapons[] = {"v105_M73SAW"};

        magazines[] = {"v105_150Rnd_762x51_Box","v105_150Rnd_762x51_Box"};
        respawnMagazines[] = {"v105_150Rnd_762x51_Box","v105_150Rnd_762x51_Box"};

        backpack = "OPTRE_Rad_Rucksack_2";

        ALiVE_orbatCreator_loadout[] = {{"v105_M73SAW","","OPTRE_M45_Flashlight","OPTRE_M73_SmartLink",{"v105_150Rnd_762x51_Box",150},{},"bipod_01_F_blk"},{},{},{"U_C_ArtTShirt_01_v5_F",{{"FirstAidKit",1}}},{"LM_OPCAN_ACTV_CGC_VEST",{{"OPTRE_Biofoam",2},{"ACE_M26_Clacker",1},{"HandGrenade",1,1},{"MiniGrenade",1,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_blue",1,1},{"M41_IED_Remote_Mag",1,1},{"v105_150Rnd_762x51_Box",2,150}}},{"OPTRE_Rad_Rucksack_2",{{"v105_300Rnd_762x51_Box_Tracer",6,300}}},"H_ShemagOpen_tan","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_BIAArmy_Guerilla_Techie_01 : I_G_Offroad_01_armed_F_OCimport_02 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Techie (LMG)";
        side = 2;
        faction = "I_BIAArmy";
        crew = "I_BIAArmy_Guerilla_Rifleman_01";

        class Turrets : Turrets {
            class M2_Turret : M2_Turret { gunnerType = "I_BIAArmy_Guerilla_Autorifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_grn_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_grn_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Green";

    };

    class I_BIAArmy_Guerilla_Techie_02 : I_G_Offroad_01_F_OCimport_02 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Techie";
        side = 2;
        faction = "I_BIAArmy";
        crew = "I_BIAArmy_Guerilla_Rifleman_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "I_BIAArmy_Guerilla_Spotter_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "I_BIAArmy_Guerilla_Autorifleman_01"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = "I_BIAArmy_Guerilla_Light_AT_01"; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = "I_BIAArmy_Guerilla_Shotgunner_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_grn_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_grn_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Green";

    };

    class I_BIAArmy_Guerilla_Techie_AT_01 : I_G_Offroad_01_AT_F_OCimport_02 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Techie (AT)";
        side = 2;
        faction = "I_BIAArmy";
        crew = "I_BIAArmy_Guerilla_Spotter_01";

        class Turrets : Turrets {
            class AT_Turret : AT_Turret { gunnerType = "I_BIAArmy_Guerilla_Autorifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_grn_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_grn_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Green";

    };

    class I_BIAArmy_Guerilla_Techie_Repair_01 : I_G_Offroad_01_repair_F_OCimport_02 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Techie (Repair)";
        side = 2;
        faction = "I_BIAArmy";
        crew = "I_BIAArmy_Guerilla_AT_EOD_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Soft_F_Bootcamp\Offroad_01\Data\offroad_01_ext_IG_01_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\Soft_F_Bootcamp\Offroad_01\Data\offroad_01_ext_IG_01_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Guerilla_01";

    };

    class I_BIAArmy_Truck_01 : I_G_Van_01_transport_F_OCimport_02 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Truck";
        side = 2;
        faction = "I_BIAArmy";
        crew = "I_BIAArmy_Guerilla_Rifleman_01";

        class Turrets : Turrets {
            class CargoTurret_L1 : CargoTurret_L1 { gunnerType = "I_BIAArmy_Guerilla_Shotgunner_01"; };
            class CargoTurret_L2 : CargoTurret_L2 { gunnerType = "I_BIAArmy_Guerilla_AT_EOD_01"; };
            class CargoTurret_L3 : CargoTurret_L3 { gunnerType = "I_BIAArmy_Guerilla_Light_AT_01"; };
            class CargoTurret_L4 : CargoTurret_L4 { gunnerType = "I_BIAArmy_Guerilla_Warlord_01"; };
            class CargoTurret_L5 : CargoTurret_L5 { gunnerType = "I_BIAArmy_Guerilla_Spotter_01"; };
            class CargoTurret_R1 : CargoTurret_R1 { gunnerType = "I_BIAArmy_Guerilla_Anti_Air_01"; };
            class CargoTurret_R2 : CargoTurret_R2 { gunnerType = "I_BIAArmy_Guerilla_Autorifleman_01"; };
            class CargoTurret_R3 : CargoTurret_R3 { gunnerType = "I_BIAArmy_Guerilla_Rifleman_01"; };
            class CargoTurret_R4 : CargoTurret_R4 { gunnerType = "I_BIAArmy_Guerilla_Rifleman_01"; };
            class CargoTurret_R5 : CargoTurret_R5 { gunnerType = "I_BIAArmy_Guerilla_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Soft_F_Exp\Van_01\Data\Van_01_ext_oli_co.paa'];_unit setObjectTextureGlobal [1,'\A3\soft_f_gamma\van_01\Data\van_01_adds_CO.paa'];_unit setObjectTextureGlobal [2,'\A3\Soft_F_Exp\Van_01\Data\Van_01_int_base_3_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class I_BIAArmy_M2_HMG_01 : I_G_HMG_02_high_F_OCimport_02 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "M2 HMG";
        side = 2;
        faction = "I_BIAArmy";
        crew = "I_G_Soldier_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_BIAArmy_Guerilla_Autorifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_BIAArmy_Mk6_Mortar_01 : I_G_Mortar_01_F_OCimport_02 {
        author = "GySgt. C. Varner";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mk6 Mortar";
        side = 2;
        faction = "I_BIAArmy";
        crew = "I_G_Soldier_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_BIAArmy_Guerilla_Rifleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};